### ISSUE TITLE
[Feature suggestion] Mod Manager Priority

### ISSUE THREAD

**Issue by DakotaWorzella** [Raytwo/ARCropolis#100]
## Feature suggestion
Mod Manager Priority

### What would the feature do?
Having a way for the Mod Manager to be able to load mods based on priority.

### How should it be implemented?
Have a field in the info.toml text file, something along the lines of "priority" and then give it a numerical value, with 1 being the mod that is most prioritized. That way, when the game is loaded, only the files for that mod will be loaded.

### Is there an alternative way of doing things you'd like to suggest?
The preferred way that I can imagine this being implemented is in the Mod Manager itself, being able to order mods in order of their priority and whateve position in that order they are, their info.toml files will be modified to represent that.

### Additional information
Let's say that I have two mods over Captain Falcon, the Cinderace mod, and the Etika mod. The Cinderace mod covers all of captain falcon's skins, and the Etika one only over c05. If I set the Etika mod to have priority over the Cinderace mod, then only the c05 skin (and it's respective files) will load from that mod, whereas c00-c04 & c06-c07 will load from the Cinderace mod, as those don't have any other mods with priority over them.

**Comment by Raytwo** [comment]
Discussions about this topic have taken place, and conflicts are going to be dealt with on a directory basis on boot.
You'll be given a choice if a conflict arises, and the one you didn't pick will be disabled until you turn it back on.

Having too much logic for file discovery contributes to longer boot times and I don't think having all this priority logic is necessary when the user could just disable what they don't use instead (Which would be the logical thing to do).

**Comment by DakotaWorzella** [comment]
That's fair enough
