### ISSUE TITLE
[Incorrect behavior][2.0.0-beta6] Only one custom voice used in dittos

### ISSUE THREAD

**Issue by DakotaWorzella** [Raytwo/ARCropolis#101]
## Bug report
Only one custom voice used in dittos

### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta6``
microSD card format: ``FAT32``

### Expected behavior
One skin would use its voice, and the other skin for the same character would use their different voice

### Reproducibility 
[ultimate.zip](https://github.com/Raytwo/ARCropolis/files/6866243/ultimate.zip)

### What happened and what's the context?
Playing a game with two captain falcons using the Cinderace and Phoenix Wright mod will cause Phoenix Wright to use Cinderace's voice. With Cinderace not in the match, Phoenix Wright's voice gets used normally. 

### Configuration
```[infos]
version = "2.0.0"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "104.248.50.215"
beta_updates = true

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"
```

**Comment by Demonslayerx8** [comment]
That is not a bug, you need nus3bank files for the character voice mods to make them be single slot.

**Comment by DakotaWorzella** [comment]
I apologize if this is a stupid question, but is there an easy way to extract nus3audio files from the nus3bank file? Either that, or if there there is a tutorial on how to properly set this stuff up, I'd appreciate it if you could link it to me. I couldn't find one available on gamebanana.

**Comment by Demonslayerx8** [comment]
join the discord server for smash ultimate modding. All the nus3bank's you need can be found in the resources channel.

**Comment by DakotaWorzella** [comment]
Adding in the nus3bank files worked perfectly! I'll test them out on all the other ones I have. Thanks!
