### ISSUE TITLE
[Crash] [ARCropolis 2.0.0-beta6/7/8] Pokemon Trainer crashes 5-8 player matches

### ISSUE THREAD

**Issue by dgranda22** [Raytwo/ARCropolis#102]
### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta6``
microSD card format: ``FAT32``

### Reproducibility 
Get into an 8-player match with Player 1 as any Pokémon Trainer and the 7 CPUs as Mario. The game should crash on the VS. loading screen. The game doesn't crash if there are 1-4 players, but will if there are 5-8. Starting with either Squirtle, Ivysaur, or Charizard still crashes the game.

### What happened and what's the context?
This happened consistently while I was testing out mods with the 2.0.0 update, testing 8 skins at a time. The game froze on the VS screen and crashed. I narrowed it down to Pokémon Trainer causing the crashing. Even without having any mods enabled, this crash still happens.

### Configuration
https://cdn.discordapp.com/attachments/631319583474843650/868245989356605540/arcropolis.toml

### Crash report
https://cdn.discordapp.com/attachments/631319583474843650/868246024588767322/01627075970_01006a800016e000.log

**Comment by Raytwo** [comment]
The cause is apparently the game just having too much to deal with because of unsharing. I do not thing we'll be able to solve this, it's just too much.
Maybe in the future if the unsharing code is refined to only unshare slots that need it, but that's a lot of work.
