### ISSUE TITLE
[Crash] [2.0.0 Beta-5, 6,7] def_shulk001_nor.nutexb crashes Shulk. Happens with multiple shulk mods.

### ISSUE THREAD

**Issue by Angstdiscord** [Raytwo/ARCropolis#103]
### Your setup
System firmware version: ``12.0.1``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6873359/arcropolis.zip)
``
ARCropolis version: ``2.0.0-beta 5. Also Tested on Beta-6``
microSD card format: `Fat32"

### Reproducibility 
Happens every time, with multiple model imports. Specifically seems to crash on C00. Texture mods do not have this problem, only model imports.
Tested with two model imports
https://gamebanana.com/mods/175144

### What happened and what's the context?
Offline,  almost always crashes on the loading screen before a match, occasionally crashes on CSS after selecting shulk C00.

Attached logs.

**Comment by dgranda22** [comment]
I've been having this issue with more than just c00. Removing the file def_shulk_001_nor.nutexb from the affected costume fixes the crashing issue, albeit the models will look off. I've tested this out with two different skins that usually crash, so I have a good feeling that file is the root of the problem.

**Comment by Demonslayerx8** [comment]
> I've been having this issue with more than just c00. Removing the file def_shulk_001_nor.nutexb from the affected costume fixes the crashing issue, albeit the models will look off. I've tested this out with two different skins that usually crash, so I have a good feeling that file is the root of the problem.

your issue is most likely that texture being bigger than the vanilla size of 0x2AB6B0, so if it's bigger than that, then ofc it'll crash, due to that file being a uncompressed file. Now if it WAS compressed, then it wouldn't be an issue.

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 2.0.0
