### ISSUE TITLE
[Incorrect behavior][ARCropolis version] HERO literally disappeared

### ISSUE THREAD

**Issue by taytwofive** [Raytwo/ARCropolis#105]
i have no problems with crashes or mods, but some characters from the roster completely disappear. Changing the version of ARCropolis changes which characters disappear...its weird. why does this keep happening with Hero? Even Kazuya is fine, its literally just Hero.

And i know it has to do with ARCro because i turned every other mod off and this still happens.

**Comment by Demonslayerx8** [comment]
Care to show an example of what you mean? I have no issues with Hero or any other DLC char at all.

**Comment by Raytwo** [comment]
Please respect the issue templates. We can't do anything we what little information you provided.
