### ISSUE TITLE
[Incorrect behavior] [ 2.0.0 Beta 8 ] R.O.B. switches c01 and c00

### ISSUE THREAD

**Issue by Blabacon** [Raytwo/ARCropolis#107]
### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta 8``
microSD card format: ``FAT32 (I think)``

### What happened and what's the context?
On R.O.B. any mods/files that go on c01 instead go over c00. 
Note: I double and triple-checked my file names also.

### Reproducibility 
This happens every time

### I Dun Goofed
This is apparently an issue with smash bros itself and not ARCropolis. So if someone could delete this issue report, I'd appreciate it. As I can't quite figure out how to myself.

**Comment by Raytwo** [comment]
Thanks for the report anyways!
