### ISSUE TITLE
[Crash] [ARCropolis 2.0 Beta7/Beta8 (Super Mario Maker Stage Crash)

### ISSUE THREAD

**Issue by OmegaHadangeki** [Raytwo/ARCropolis#108]
When entering a match on Super Mario Maker's Normal stage. The game freezes on the loading screen before the Vs. Match screen and it freezes when trying to load the stage via training mode. After freezing it then closes my game with a "The software was closed because of an error occurred" message. 

Picture below is where the game hangs after pressing start to start a fight/training.

![2021080519261800-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/87289918/128438018-a3f40083-b13f-466a-b95c-6d28060eb228.jpg)

I have formatted my SD card and installed only Atmosphere and Acropolis Beta7/Beta8 only and still have the problem. (No Mods at all)

The game still loads when using Battlefield or Omega versions.

**Comment by Raytwo** [comment]
Stage has been blacklisted from ARCropolis 2.0.0 until a fix is found. Thanks for the report!
