### ISSUE TITLE
[Feature suggestion] Add "author" to info.toml

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [Raytwo/ARCropolis#110]
## Feature suggestion
Add "author" to info.toml

### What would the feature do?
Just a small improvement, I think the mod manager should show the name of the author of each mod, if future mod authors create their own info.toml they can put their own name on it.

**Comment by Raytwo** [comment]
Admittedly, I was pretty sure this was already implemented and had to double check to confirm that it isn't.
Thanks for the suggestion

**Comment by Heartbeat-Heartbreak** [comment]
I tried to add "author" to info.toml but it doesn't work...and there is no "author" description in[ this part of the wiki.](https://github.com/Raytwo/ARCropolis/wiki/Mod-manager)

**Comment by jam1garner** [comment]
Should probably be `authors` and be a list of strings

**Comment by Raytwo** [comment]
> 
> 
> I tried to add "author" to info.toml but it doesn't work...and there is no "author" description in[ this part of the wiki.](https://github.com/Raytwo/ARCropolis/wiki/Mod-manager)

Yes, you are right. I was just confirming that it is indeed missing, no worries.

**Comment by Raytwo** [comment]
Implemented as of ARCropolis 3.1.0! Sorry it took so long.
