### ISSUE TITLE
[Feature suggestion] Replace the "news" scrolling text at the top of the main menu by custom news

### ISSUE THREAD

**Issue by Raytwo** [Raytwo/ARCropolis#116]
### What would the feature do?
What it says in the title.

### How should it be implemented?
Locating the URL that fetches the latest message to display in the code, inserting a inline hook with a mutable InlineCtx to edit the register and replace the URL by a custom one pointing to another server capable of distributing messages. For this to work, the replacing server should work the same way as the one used by the game.

### Is there an alternative way of doing things you'd like to suggest?
Inline hook right before the layout.arc's text is edited, like [the current title screen version replacement](https://github.com/Raytwo/ARCropolis/blob/f433c8a35ceacea52182b816b41e8dc73e982f53/src/lib.rs#L401) instead, and fetch the text from an API.

### Additional information
* Should probably have a toggle in the configuration
* Consider localization

**Comment by jozz024** [comment]
Implemented in rewrite, so this issue is no longer needed.
