### ISSUE TITLE
[Crash] [2.1.0-beta3] Game crashes while starting

### ISSUE THREAD

**Issue by KingSlowDown** [Raytwo/ARCropolis#123]
## Crash report
The game straight up crashes after the "Nintendo Switch"-loading screen. No mods are used, everything is freshly installed. (Atmosphere, Hekate and ARCropolis, tested everything separately) - Tested with emuMMC and sysMMC.
Version 1.1.3 works fine, but the freshly installed 2.1.0 beta3 does not. I also run the "Archive Bit Fix" more than once.

### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.1.0-beta3``
microSD card format: ``FAT32``

### Reproducibility 
It always happens when starting Smash Ultimate

### What happened and what's the context?
I downloaded ver. 2.1.0-beta3 and the game crashes, when starting it.

### Configuration
File type isn't allowed here, so here on drive
https://drive.google.com/file/d/1UOr7k41iVpNzDzOR06p4p7f97hBFDXrX/view?usp=sharing

### Crash report
[01629769505_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7042506/01629769505_01006a800016e000.log)

**Comment by KingSlowDown** [comment]
Edit: Deleting arcropolis.toml fixed it

**Comment by Raytwo** [comment]
Please try this and let me know how it goes: https://cdn.discordapp.com/attachments/447940880922574848/880710875839885332/release.zip

**Comment by Sandpie00** [comment]
I went back to the normal build and now it works but it takes two bootups to actually start, the first one always crashes and says the software was closed due to an error

**Comment by KingSlowDown** [comment]
First time it froze when I pressed on something in the menu, second time it just loaded forever and ever.

**Comment by Raytwo** [comment]
Could you please try the latest build (beta4) and close the issue if it fixes your problem?

**Comment by Raytwo** [comment]
Ok well, closing this due to lack of feedback. Please reopen an issue if the problem persists.
