### ISSUE TITLE
[Crash] [2.1.0-beta3] Game crashes on startup, startup is incredibly long

### ISSUE THREAD

**Issue by Sandpie00** [Raytwo/ARCropolis#124]
## Crash report
Game crashes after the Nintendo Switch logo appears. The screen goes black for a very long time and then it says the software was closed due to an error. All my mods worked on 2.0.0 prior to this.

### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.1.0-beta3``
microSD card format: ``FAT32``

### Reproducibility 
Generate a new arcropolis.toml file with this version and then just start up the game.

### What happened and what's the context?
I updated from 2.0.0, but the game was broken. My inputs weren't being recognized and the title screen just displayed the Smash logo. So I tried deleting my arcropolis.toml file and well this happened after it generated a new one. I've tried deleting it again but nothing changes.

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/7060561/arcropolis.zip)

### Crash report
[01629988042_01006a800016e000.zip](https://github.com/Raytwo/ARCropolis/files/7060562/01629988042_01006a800016e000.zip)

**Comment by Raytwo** [comment]
Can’t do much about the long boot times for the time being, however maybe you could try this build and tell me if this fixes the problem?

https://cdn.discordapp.com/attachments/447940880922574848/880710875839885332/release.zip

**Comment by TeriosKrim** [comment]
> 
> 
> Can’t do much about the long boot times for the time being, however maybe you could try this build and tell me if this fixes the problem?
> 
> https://cdn.discordapp.com/attachments/447940880922574848/880710875839885332/release.zip

I'll try it right now

**Comment by Sandpie00** [comment]
> Can’t do much about the long boot times for the time being, however maybe you could try this build and tell me if this fixes the problem?
> 
> https://cdn.discordapp.com/attachments/447940880922574848/880710875839885332/release.zip

I feel like the boot is even longer now. It works though

**Comment by TeriosKrim** [comment]
On my end it still crashes on booting up Smash when the Nintendo Switch logo appears

**Comment by Ethereo** [comment]
I had the same issue, the fix for me was turn on wi-fi (i was on airplane mode), then smash starts normally

**Comment by Sandpie00** [comment]
I went back to the normal build and now it works but it takes two bootups to actually start, the first one always crashes and says the software was closed due to an error. Also wifi on or off is the same thing

**Comment by Raytwo** [comment]
Ok, sorry about that, second run:
https://cdn.discordapp.com/attachments/447940880922574848/881287505343807488/libarcropolis.nro

**Comment by Faketsumi** [comment]
works fine for me aswell, tho did you disable online for that build? Just making sure because cant enter online whatsoever

**Comment by Sandpie00** [comment]
> Ok, sorry about that, second run:
> https://cdn.discordapp.com/attachments/447940880922574848/881287505343807488/libarcropolis.nro

I'll try this one but is the online disabled?

**Comment by Raytwo** [comment]
It isn’t, just removed the auto updater to confirm if the issue comes from there.

**Comment by Sandpie00** [comment]
Nope, same thing. Now it crashes after it finishes loading with the Smash logo in the bottom right corner

**Comment by Raytwo** [comment]
Mhhh, alright, one more time:
https://cdn.discordapp.com/attachments/345670285040680982/881498395850711040/libarcropolis.nro

Although I must say that if even this doesn't work, I'm at a loss.

**Comment by TeriosKrim** [comment]
mines work fine now it doesn't loads up my mods even tho they're in the correct path and folder names

**Comment by Sandpie00** [comment]
Update: it just stopped working altogether. The game ALWAYS crashes after the Nintendo Switch logo, independent of what build or what config file or what have you. It started happening this morning, without me updating or anything. I've also removed all my mods and nothing changes. I don't think it's the new version of Atmosphere because it worked yesterday

**Comment by Raytwo** [comment]
Could you please try the latest build (beta4) and close the issue if it fixes your problem?
