### ISSUE TITLE
[Crash] [ARCropolis v2.1.0-beta3] Crashes after Opening

### ISSUE THREAD

**Issue by iOZMinty** [Raytwo/ARCropolis#125]
## Crash report
Game crashes right after I boot it. It doesn't show the Smash logo at all.
All plugins have been disabled, only ACRopolis was active it still crashed.

### Your setup
System firmware version: 12.1.0
Atmosphère version: 0.20.0 & 0.15.0
Smash version: 11.0.1
ARCropolis version: 2.1.0-beta3
microSD card format: exFAT

### Reproducibility 
Every time I launch the game. No matter what.

### What happened and what's the context?
Tried to launch the game right after I updated Atmosphere to the version 0.20.0.

### Configuration
[arcropolis.txt](https://github.com/Raytwo/ARCropolis/files/7071847/arcropolis.txt)
Doesn't let me upload as toml, so I rename to txt.

### Crash report
[01630207008_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7071850/01630207008_01006a800016e000.log)

**Comment by salomepeach** [comment]
Yup same here. Tried everything the modding discord told me to do. Replaced the libracropolis.nro, removed the xxx600 folder, installed 1.1.3 and removed it and installed 2.1.0-beta3, connect to wifi instead of LAN, anything, but it still crashes.

**Comment by TeriosKrim** [comment]
Yea mines now crashes pass the nintendo switch logo regardless when im wifi or lan

**Comment by KaniDev** [comment]
Same issue here, if arcropolis.toml isn't there yet it gets generated then crashes, otherwise it crashes immediately. It's on a fresh install, emuMMC, AMS v0.20.0, firmware v12.1.0, hekate v5.6.0, game v12.0.0

**Comment by Raytwo** [comment]
Could you please try the latest build (beta4) and close the issue if it fixes your problem?

**Comment by iOZMinty** [comment]
> Could you please try the latest build (beta4) and close the issue if it fixes your problem?

Certainly, once I finish redownloading the game and install everything I'll gladly do it.

**Comment by TeriosKrim** [comment]
I tested beta 4 and it crashed the first time until I disable the libacmd_hook.nro file using arcadia and now it works again and turning libacmd_hook.nro on again crashes the game after it pass the nintendo switch logo

**Comment by Raytwo** [comment]
> I tested beta 4 and it kept on crashing until I disable the libacmd_hook.nro file using arcadia and now it works again and turning libacmd_hook.nro on again crashes the game after it pass the nintendo switch logo

Ok well, other plugins have nothing to do with ARCropolis, so please report it to the others if an issue arise. Glad to hear the game booted though!

**Comment by TeriosKrim** [comment]
Will do!

> 
> 
> > I tested beta 4 and it kept on crashing until I disable the libacmd_hook.nro file using arcadia and now it works again and turning libacmd_hook.nro on again crashes the game after it pass the nintendo switch logo
> 
> Ok well, other plugins have nothing to do with ARCropolis, so please report it to the author if an issue arise. Glad to hear the game booted though!

**Comment by Raytwo** [comment]
Ok well, closing this due to lack of feedback. Please reopen an issue if the problem persists.

**Comment by iOZMinty** [comment]
> Ok well, closing this due to lack of feedback. Please reopen an issue if the problem persists.

Excuse my absence. I've been having a really hard time redownload the game after a huge incident related to both ARCrop and Atmosphère. But I honestly think is my fault, cause it looked like an amalgamation of bad decisions/management of my games. To a point where one of my personal mods somehow turned into my "SD Card?" Which is really strange. 

The problem may be fixed once I get Smash downloaded again. Hopefully today.

**Comment by kagexice** [comment]
im kind of new here so i dont know much about what im doing, but i have an issue with the arcadia app on the swich, it keeps crashing with an error and sending me back to hekate whenever i try to boot it to check what mods i have on/off, this only happened after i updated hekate and atmospere, i only mod super smash bros so this is a small problem i think?

**Comment by Angstdiscord** [comment]
> im kind of new here so i dont know much about what im doing, but i have an issue with the arcadia app on the swich, it keeps crashing with an error and sending me back to hekate whenever i try to boot it to check what mods i have on/off, this only happened after i updated hekate and atmospere, i only mod super smash bros so this is a small problem i think?

well first off, this issue is closed. So I wouldn't post here. Second off this is for ARCropolis, not Arcadia. If you are having an issue with the in-game arcadia which is a part of ARCropolis,, you should create your own issue using the provided template, and not post in already closed, unrelated issues.

**Comment by kagexice** [comment]
oh ok
