### ISSUE TITLE
[Incorrect behavior][ARCropolis 2.1.0-beta3] Voice language is permanently set to English, regardless of language chosen

### ISSUE THREAD

**Issue by notjokr** [Raytwo/ARCropolis#127]
## Bug report
Fighter voices seem to be permanently stuck in English regardless of what language is chosen. This only happens with ARCropolis installed, otherwise the game works as intended.

### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``1.0.0``
Smash version: ``12.0``
ARCropolis version: ``2.1.0-beta3``
microSD card format: ``FAT32``

### Expected behavior
Voices should change with their corresponding language. Japanese should have Japanese voices, for example.

### Reproducibility 
Just choose any language that isn't English, all of the voices stay in English no matter what.

### What happened and what's the context?
It happens in every instance. With mods on, all mods disabled, online, offline, training mode- no matter where you go, the fighter voices are stuck in English

### Screenshot(s)
N/A

### Configuration
N/A

**Comment by Raytwo** [comment]
Mhhhh well there is a configuration field in the template for a reason so could you please provide your configuration so I can confirm if the issue is as I suspect?

**Comment by notjokr** [comment]
> Mhhhh well there is a configuration field in the template for a reason so could you please provide your configuration so I can confirm if the issue is as I suspect?

Is it the arcropolis.toml file? It's the only thing I see so I will attach it just incase it is
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/7165785/arcropolis.zip)

**Comment by Raytwo** [comment]
Sorry for the late reply, but yeah that's the correct file.

Ok so I suspect you just forgot to change the region at the bottom of your configuration file when changing the game's language, which might be the reason why the voices stay in english. (My take is that it's a side effect of early file unsharing, which is in the version of ARCropolis you use).

Please refer to [this section](https://github.com/Raytwo/ARCropolis/wiki/Configuration#miscellaneous) of the wiki for a list of the available options.

**Comment by notjokr** [comment]
Was finally able to test it, changing the value to "jp_ja" works perfectly, thank you :)

**Comment by Raytwo** [comment]
Glad to hear it, have fun!
