### ISSUE TITLE
[Crash] [2.1.0] Game crashes when opening the how to play menu to load up mops 

### ISSUE THREAD

**Issue by SP1o** [Raytwo/ARCropolis#132]
My setup
System firmware version: ``13.0.0``
Atmosphère version: ``1.1.0``
Smash version: ``12.0.0``
ARCropolis version: ``2.1.0``
microSD card format: ``FAT32``

Reproducibility 
I am trying to load mods on smash but everytime I open the How to play menu the game crashes. I have a mods folder inside of my SD card and I don't know what causes it, I have a custom UI for the starting switch screen and that works perfectly fine.

What happened and what's the context?
It was on the load screen whilst trying to load up mods

Configuration
[fewwdwq.txt](https://github.com/Raytwo/ARCropolis/files/7227599/fewwdwq.txt)
(I converted it to txt because github does not support toml files)

Crash report
[01632504781_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7227581/01632504781_01006a800016e000.log)

**Comment by sneakysnakek** [comment]
![E0EE7D81-65FB-4895-A9D1-52058A35EB68](https://user-images.githubusercontent.com/91567963/135317642-2ca765c6-0520-4722-94fa-541ab293dc4d.jpeg)

same thing happened to me, haven’t been able to find anything about it yet

**Comment by Raytwo** [comment]
Hello,
Sorry for the very late reply, I don’t know if your issue has been solved since, but I’ll be closing this to keep relevant issues visible.
If you still encounter this issue, I’d advice to reopen an issue using the new issue template form, as it’d help in narrowing it down.
Thanks!
