### ISSUE TITLE
[Feature suggestion] Allow users to store modpack/presets

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#135]
## Feature suggestion
Allow the user to store modpack/presets for their enabled/disabled mods.

### What would the feature do?
Modpack/presets would enable the user to one-stop-shop toggle a collection of mods all at once and disable everything else.

### How should it be implemented?
There should be preset files in a per-user directory which can be toggled in ARCadia-web. It should enable _only_ the mods listed in the preset, and warn the user if a mod is missing.

### Is there an alternative way of doing things you'd like to suggest?
N/A

### Additional information
N/A

**Comment by Raytwo** [comment]
Implemented as of ARCropolis 3.2.0
