### ISSUE TITLE
[Feature suggestion] Explicit file table manipulation

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#138]
## Feature suggestion
**NOTE: THIS FEATURE IS ONLY INTENDED TO BE USED BY THOSE WHO KNOW WHAT THEY ARE DOING**

The ability to explicitly modify the contents* of file table entries.

*these modifications would be only ones allowed by ARCropolis. For example, modifying unused fields of a `FilePath` entry? Probably allowed. Modifying which `FileInfoIndex` it points to, absolutely not

### What would the feature do?
This feature would allow mod creators to change certain things about the filesystem. These changes are TBD and will be explained in future issues.

### How should it be implemented?
Each file should have a `json` file (or `toml`, TBD) which will contain information about some files in the mod that need to have their entries modified. These modifications _should_ be done after unsharing/file addition, although the exact timing has not yet been worked out.

### Is there an alternative way of doing things you'd like to suggest?
N/A

### Additional information
As stated earlier, explicit manipulation of the file tables is very unsafe, and as such ARCropolis will be greatly limiting it's functionality for those who use it as to not _misuse_ it

**Comment by Raytwo** [comment]
Change of plans, not doing this for a lot of reasons.
