### ISSUE TITLE
[Feature suggestion] Export more valuable information via the API

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#140]
## Feature suggestion
Export more valuable information via the API

### What would the feature do?
Right now, the API exports some control methods, but not really any querying methods.

The following methods would be helpful for other applications to use:
- [ ] Export the `&'static LoadedArc` as immutable
- [x] Export the file system information (what API callbacks are registered and what files are loaded into the patch section)
- [ ] Load a file in-line
- [ ] Request a file to be loaded (with a file descriptor)
- [x] Request a list of all files with a certain extension
- [ ] Request a directory to be loaded (DirInfo version)
- [ ] Request a directory to be loaded (Folder version)
- [ ] Check if a file is currently loaded.

### How should it be implemented?
The API should not allow the client to modify/mutate any of ARCropolis's state (including the filesystem) **period**. It should all be read only. 

The only API calls which should be able to mutate the game's state are the ones which currently allow load callbacks as well as the (potentially) planned methods to request a load from the game.

### Is there an alternative way of doing things you'd like to suggest?
[If what you're suggesting could be made in different ways, please explain. If not, write N/A.]

### Additional information
N/A

**Comment by Raytwo** [comment]
Some of these have been implemented, some are not a good idea (loading requests)
