### ISSUE TITLE
[Incorrect behavior][2.x.x latest one on 10/9/2021] Camera animations are not separate.

### ISSUE THREAD

**Issue by puli2004** [Raytwo/ARCropolis#148]
Just want to point out that camera animation are not separate in 2.x.x. I only have the camera set to c07 but it plays in all slots

**Comment by puli2004** [comment]
Why was the issue closed.

**Comment by Raytwo** [comment]
Because when politely asked on the Discord server to open an issue like everybody else, you threw a tantrum instead of complying so I have no intention of humoring you. Plus your issue does not follow any of the issue templates of when it was opened so I’d have closed it anyways.
