### ISSUE TITLE
[Incorrect behavior][2.1.0-beta.4] Dark Samus c05 T-poses in her Up victory animation

### ISSUE THREAD

**Issue by Sandpie00** [Raytwo/ARCropolis#149]
## Bug report
In her victory animation where she splits and cartwheels, the Dark Samus on the right is in a T-pose until they join back together. She also has the Morph Ball model stuck on her. It's not my mods, I've tried removing them and it still happens. Also I didn't have any mods on c05.

### Your setup
System firmware version: 13.0.0
Atmosphère version: 1.1.1
Smash version: 12.0.0
ARCropolis version: 2.1.0-beta.4
microSD card format: FAT32

### Expected behavior
https://ssb.wiki.gallery/images/2/21/DarkSamusVictoryPose2.gif?download

### Reproducibility 
Win a match as Dark Samus c05 (silver and red alt) and hold Up when "GAME" comes up.

### What happened and what's the context?
I lost online against a Dark Samus and saw it. Then I tried reproducing it offline and the same happened.

### Screenshot(s)
![2021101215131600-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/77105407/136963500-09ab6909-099b-462e-b97f-88b7b6a17a47.jpg)

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/7330265/arcropolis.zip)

**Comment by Raytwo** [comment]
Issue fixed by @ClaudevonRiegan, expect it to be implemented in the next update.
