### ISSUE TITLE
Config file not being created

### ISSUE THREAD

**Issue by RealRakkman** [Raytwo/ARCropolis#15]
I don't know if I'm doing something wrong but I have the skyline plugin in my contents folder the way it says, but even after I launch smash ultimate there is never a config file created

**Comment by RealRakkman** [comment]
Okay I've figured out that you have to change to system settings ini to ease nro restriction, but upon booting smash and getting the pop up saying its creating the config file, is proceeds to crash shortly after pressing close on the pop up

**Comment by Raytwo** [comment]
Sorry to hear, hopefully some of your crashes are going to be solved by the next update. Please bear with it until we figure out all the issues and thanks for using ARCropolis !
