### ISSUE TITLE
Pac-MAN's Sign (Textures) are still shared

### ISSUE THREAD

**Issue by LuckyJero** [Raytwo/ARCropolis#154]
Unfortunately, Pac-Man's Sign in the Victory Screen has shared texture. I provided a mod where you need to test if the c00 slot has the vanilla sign and for c07 a tombstone respectively in Pac-Man's Victory Screen.

Thanks for your support and help! 

[Pac-Man Sign Issue.zip](https://github.com/Raytwo/ARCropolis/files/7396145/Pac-Man.Sign.Issue.zip)
s.

**Comment by blu-dev** [comment]
Resolved in latest commit of the file-replacement branch. Thanks for reporting!
