### ISSUE TITLE
[Crash] [ARCropolis version] Brief description of the issue

### ISSUE THREAD

**Issue by LeonCamero** [Raytwo/ARCropolis#156]
### CFW sysmmc/emummc
System firmware version: 13.1.0
Atmosphère version: 1.2.1 (latest)
Smash version: `13.0.0`
ARCropolis version: ``2.1.0-beta4
microSD card format: ``FAT32``

Error report:

A fatal error occurred (or a panic occurred) when running Atmosphére.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

How to reproduce: Assuming that after you updated your Hetake to 5.6.5 and Atmosphere, which now supports the switch FW 13.1.0, it would work with the latest update of the switch, however, this didn't work. Removing the content folder allows access to smash ultimate, but adding the content crashes atmosphere once again. This crashes every time you try to load the game

### Configuration
Note: .toml files is not supported on Github...

### Crash report
note: .bin files are not supported either...

**Comment by pleasehelpmeeeee** [comment]
does anyone know why my game keeps on saying check for courrupted files every time i try to start the game after im done with all the moding        i need to keep on redownloading the game when that happens

**Comment by Raytwo** [comment]
> does anyone know why my game keeps on saying check for courrupted files every time i try to start the game after im done with all the moding i need to keep on redownloading the game when that happens

Look, would you stop posting on closed issues to get help? Use the Discussions page like everybody else.
