### ISSUE TITLE
Local Wireless / Lan Play Doesn't Work With Newer Versions

### ISSUE THREAD

**Issue by jRiift** [Raytwo/ARCropolis#16]
This has been a thing for a while now. Lan Play doesn't seem to work with any versions past 0.6.0. Not sure why. When you click on the local wireless option the screen goes black for a second but then boots back to the main menu.

**Comment by jRiift** [comment]
This is regarding the local_wireless release btw^^

**Comment by Raytwo** [comment]
Yeah we've been adding the wrong file with it, sorry about that. Latest update (0.9.0) fixes that.
