### ISSUE TITLE
Adding mods with sound folders don't work.

### ISSUE THREAD

**Issue by Mania-616** [Raytwo/ARCropolis#161]
Title.

I've added the "Blaze over Sonic" soundpack. the pathing goes
SD Card Root > ultimate > mods > Blaze over Sonic S3 > sound > bank > fighter_voice > vc_sonic_c02.nus3audio

It's just the default Sonic voicelines. I've tried using different Sonic lines with different skins. Recently installed Metal Sonic and Mecha Sonic, don't work. Tried installing Timeless River Sora's Filtered Voice, don't work. My previously installed mods' voicelines work fine. It's only the newly added ones.

**Comment by Raytwo** [comment]
Please reopen an issue with one of the existing templates, as you're not providing any of the required information for us to help you
