### ISSUE TITLE
[Incorrect behavior][ARCropolis version 2.1.0] Inkling girl's Swing.prc is causing desyncs online

### ISSUE THREAD

**Issue by Err0ne0us** [Raytwo/ARCropolis#162]
### Your setup
System firmware version: ``13.1.0``
Atmosphère version: ``1.2.1``
Smash version: ``13.0.0``
ARCropolis version: ``2.1.0`
microSD card format: ``FAT32``

### Expected behavior
Inkling Girl should have working Swing Bones while online.

### Reproducibility 
It happens whenever I go online with Inkling Girl whenever I have custom swing bones and a swing.prc to match, no matter the values or name of the bones in the nusktb or swing.prc.

### What happened and what's the context?
Whenever I go online with Inkling to test adding Swing bones, in my case giving Agent 3 a cape, it says "A communication error has occured." I have tested this with many tweaks to values and bone names but the result is constant.  However, it only happens if Inkling girl has both the Swing.prc and the Swing bones installed and the values for said bones are in the swing.prc.

Inkling Boy works just fine though. Adding swing bones and whatever work without a single issue.

### Screenshot(s)
Not available at the moment, the constant disconnects have made me unable to go online and preventing further testing.

### Configuration
[Post your configuration file located in ``sd:/atmosphere/contents/01006A800016E000/romfs/arcropolis.toml`` here.]

**Comment by Err0ne0us** [comment]
Here's some examples of both custom bones with a modified .prc and just custom bones with no edits to the prc
[Inkling_Agent 3.zip](https://github.com/Raytwo/ARCropolis/files/7447968/Inkling_Agent.3.zip)
[Ponytail.zip](https://github.com/Raytwo/ARCropolis/files/7447969/Ponytail.zip)

**Comment by Raytwo** [comment]
Sorry but wifi-safeness is not an ARCropolis issue and not a concern to us. You know what you install and do with it.
