### ISSUE TITLE
[Crash] [2.1.0] Smash Crashes upon launch

### ISSUE THREAD

**Issue by Omalight** [Raytwo/ARCropolis#163]
### Your setup
System firmware version: ``13.1.0``
Atmosphère version: ``1.2.4``
Smash version: ``13.0.``
ARCropolis version: ``2.1.0``
microSD card format: ``FAT32``

### Reproducibility 

I was able to repeat it every time I tried to load smash with mods.

### What happened and what's the context?

Smash crashes upon trying to load, before or after switch loading screen.

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/7480094/arcropolis.zip) (arcropolis.toml)

### Crash report
[01636078894_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7480092/01636078894_01006a800016e000.log)
]

**Comment by Raytwo** [comment]
Please refer to #157 and make sure your Skyline install is up to date.

**Comment by Omalight** [comment]
Skyline is updated to the newest version that can be seen on their GitHub page.

**Comment by Raytwo** [comment]
Have you tried disabling some of your mods to see if it goes further than bootup?

**Comment by Omalight** [comment]
I have all mods removed. Even with all mods removed, smash won't boot without holding L. The only plugins currently are the ones that come with the newest builds of acropolis and skyline.

**Comment by Raytwo** [comment]
Welp, the last build works properly for everybody so if you're positive you updated Skyline, I can't help further, I'm sorry.
