### ISSUE TITLE
[Crash] [Ver 2.1.0] Crash when loading specific characters.

### ISSUE THREAD

**Issue by RadioForever** [Raytwo/ARCropolis#164]
### Your setup
System firmware version: ``13.1.0``
Atmosphère version: ``1.2.4``
Smash version: ``13.0.0``
ARCropolis version: ``2.1.0``
microSD card format: ``FAT32``

### Reproducibility 
Consistently happens as soon as these characters are selected. Also at the versus screen before a battle.

### What happened and what's the context?
When selecting Kirby, Daisy, Dark Pit, Snake or Joker on the CSS causes the game to encounter a fatal error. This also happens when on the versus screen before a battle as any other character.

### Configuration
(https://github.com/Raytwo/ARCropolis/files/7489385/arcropolis.zip)
)

### Crash report
Upon selecting Daisy
(https://github.com/Raytwo/ARCropolis/files/7489372/01636155755_01006a800016e000.log)
Upon starting a fight with any other characters.
(https://github.com/Raytwo/ARCropolis/files/7489371/01636156126_01006a800016e000.log

**Comment by Raytwo** [comment]
I literally loaded a match with all of these characters at the same time without issue, so please check your installed mods for them and disable some of them until your crash is gone.
