### ISSUE TITLE
[Only loads workspace called "mods"][ARCropolis Beta 3.0.0] Only workspaces named "mods" will load and test for conflicts.

### ISSUE THREAD

**Issue by antisociable** [Raytwo/ARCropolis#165]
### Your setup
System firmware version: ``13.1.0``
Atmosphère version: ``1.2.4``
Smash version: ``13.0.0``
ARCropolis version: `3.0.0-beta``
microSD card format: ``FAT32``

### Expected behavior
Should load either work space regardless of name.

### Reproducibility 
Have multiple work spaces and name one "mods". Load up your game with "mods" selected as your work space. it'll load them and any conflicts should be either found if you have them if not it'll load up normally. Once in you can play normally of course but once you exit smash and go into arcadia and try to load a new workspace it will let you select it, but when you launch smash it will still have your "mods" workspace selected.

### What happened and what's the context?
I simply opened smash and I found my mods loaded but any conflicts weren't loaded I believe that is normal, but when I tried to select a different work space it would only load my folder named "mods"

### Screenshot(s)
N/A

### Configuration
https://gyazo.com/ea4a9c020be3958912d68f909efa0a9d

this is the correct arc I'm on. I am not on 2.1.0 beta it simply doesn't show up in arcadia. in game it says its on arc 3.0.0 beta.

**Comment by blu-dev** [comment]
Please make sure you are editing the correct config file. If you are on 3.0.0-beta the config file has been moved to `sd:/ultimate/arcropolis/config.toml`. Let me know if modifying that one helps the issue or if the problem persists.
