### ISSUE TITLE
Mod manager not showing up

### ISSUE THREAD

**Issue by AppaTheBison1** [Raytwo/ARCropolis#167]
Everything works fine when I install mods but when I go to the help section and then into the how to play section it's just the regular how to play selection and no mod manager?

**Comment by AwesomeKirito** [comment]
What arcropolis are you using

**Comment by AppaTheBison1** [comment]
> What arcropolis are you using

 v3.0.0-beta.0.2

**Comment by Raytwo** [comment]
Hey there, sorry for the confusion, we omitted to mention that the menus are gone from the beta until reworked.
Also please use the templates properly next time, this is the second issue you open where you delete the entire template.

**Comment by AppaTheBison1** [comment]
sorry about that. im very new to this

**Comment by Raytwo** [comment]
No no, you're all good, this is on us!
