### ISSUE TITLE
[Crash] [ARCropolis version 3.0.0 Beta 3]: Crash on Startup

### ISSUE THREAD

**Issue by Err0ne0us** [Raytwo/ARCropolis#168]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.2

### Smash Version

13.0.0

### ARCropolis Version

3.0.0 Beta 3

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Whenever I start up smash using the 3.0.0 Beta 3, it states "The software was closed because an error occured" before the game can properly load. Previous betas have not caused this issue, nor have I made changes to my modpack from when I last started up the game yesterday. 

I have updated Skyline and attempted to install the new beta manually in case it was the auto-update but with no change. Downgrading to older versions of both stable and beta versions works.

There was another error log stating "[arcropolis::hashes] Failed to read 'sd:/ultimate/arcropolis/hashes.txt' for hashes. Reason: Custom { kind: Other, error: "Result code: 514" }. There won't be any hash lookups in this run's logs." however, including the file changed nothing and the crash still happens.

Removing all mods doesn't fix the issue either.

### Configuration

version = '3.0.0-beta.0.3'
debug = false
auto_update = true
beta_updates = true
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = true

### Crash report

[arcropolis::fs] Cannot get the incoming load because the filesystem is not initialized!
[arcropolis::fs] Cannot get the incoming load because the filesystem is not initialized!

**Comment by blu-dev** [comment]
The crash report is generated in `sd:/atmosphere/crash_reports`. Please attach that, the file you attached is the ARCropolis log which does not contain the necessary crash information.

**Comment by blu-dev** [comment]
Nevermind, the issue has been isolated. Thanks for the report!

**Comment by TripleLJ** [comment]
I don't know if this is the same issue, but I get this whenever I try to use the runtime parcel plugin

**Comment by Raytwo** [comment]
> I don't know if this is the same issue, but I get this whenever I try to use the runtime parcel plugin

Sorry, very late to the party, but please open a separate issue if you’re not sure, I’d rather see duplicates than issues reported in places that we don’t check anymore.

Since blu-dev isolated the issue, I’ll be closing this.

**Comment by TripleLJ** [comment]
> > I don't know if this is the same issue, but I get this whenever I try to use the runtime parcel plugin
> 
> Sorry, very late to the party, but please open a separate issue if you’re not sure, I’d rather see duplicates than issues reported in places that we don’t check anymore.
> 
> Since blu-dev isolated the issue, I’ll be closing this.

https://github.com/Raytwo/ARCropolis/issues/177
