### ISSUE TITLE
[Incorrect behavior][3.0.0-Beta0.3]: Final Smash videos on Non-C00 cause a white flash

### ISSUE THREAD

**Issue by WuBoytH** [Raytwo/ARCropolis#169]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.4

### Smash Version

13.0.0

### ARCropolis Version

3.0.0-beta0.3

### Version channel

Beta

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

Modded Final Smashes on any slot other than C00 should play properly.

However, any modded final smash video slot that _isn't_ on C00 will cause a blinding white light to appear and will stop the game from progressing.

This is probably solvable by forcing all video slots to be unshared.

Feel free to close, since this is something config.json can fix, but I felt like the information should be out there.

### Configuration

version = '3.0.0-beta.0.3'
debug = false
auto_update = true
beta_updates = true
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'rom:/arcropolis/workspaces/The WuBoy Ultimate Modpack/umm/'
extra_paths = []

[logger]
logger_level = 'Off'
log_to_file = true

### Minimal modpack to observe the issue

https://gamebanana.com/mods/38814

**Comment by blu-dev** [comment]
> However, any modded final smash video slot that isn't on C00 will cause a blinding white light to appear and will stop the game from progressing.

Two questions, what do you mean they will "stop the game from progressing" and when you have one on c00 does it play on all slots.

**Comment by WuBoytH** [comment]
Having one on c00 does not play for all other slots, and will cause the white light.

If the white light happens, then you will be stuck in the "final smash movie state" and never leave from it, forcing you to close the game since you can't pause while final smash movies are playing.

**Comment by WuBoytH** [comment]
another thing that happens, if you try and use config.json to blacklist the file from being unshared, is if you aren't on c00, the video will use the original file from the game, and the game will slow down considerably while playing the video, also to the point where you cannot finish watching it because it's slowed down so much.
c00 is unaffected.

**Comment by WuBoytH** [comment]
OK sorry one more update, but it appears I was slightly mistaken

if the first time you load the final smash video, it's c00's final smash video, arcropolis will always use c00's final smash video, even if you pick c04 or something later.

If you load any slot that isn't c00 first, you will get the previous comment's behavior

**Comment by WuBoytH** [comment]
In any case, the behavior of non c00 final smash movies is very strange and I'm not sure how to go about solving it.

**Comment by blu-dev** [comment]
Thank you for the information. I will look into it
