### ISSUE TITLE
Arcropolis Crashes While Loading CSS

### ISSUE THREAD

**Issue by jRiift** [Raytwo/ARCropolis#17]
This one is weird. I have absolutely zero idea what's going on here. While I have my mods installed, arcropolis crashes every single time without fail when loading the css. Assuming there was a bad bntx or something, I decided to go through every single mod I have individually to see which caused crashes, only to find that none of them did. When loading them individually there were no crashes. I've tried disabling all my other skyline and salty plugins and crashes still occur. Removing arcs stops these crashes. Archive bit fix in Hekate also does not works. I'm on latest ams and arcs, as I reformatted and reinstalled everything yesterday, which is when these issues started. I've included a crash report.
[01601006978_01006a800016e000_1.log](https://github.com/Raytwo/ARCropolis/files/5283358/01601006978_01006a800016e000_1.log)

**Comment by Raytwo** [comment]
Please try again with the latest release as it fixes a ton of issues.
