### ISSUE TITLE
[Incorrect behavior][ARCropolis version]: Acropolis does not load, smash mods do not load, after clean install and mod install.

### ISSUE THREAD

**Issue by albyknight** [Raytwo/ARCropolis#170]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

v 1.2.4

### Smash Version

13.0.0

### ARCropolis Version

2.1.1

### Version channel

Stable

### SD card formatting

exFat

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

ARCropolis should have generated a config file and loaded upon the boot of smash to load the mods.  All directories, versions and methods used to install everything were done correctly as instructed in instructions, but it just loads into vanilla smash and ARC does not even work.

### Context

I understand that the Disclaimer states that I should not post an issue if the ARCropolis version does not appear on the title screen.  However, I've been modding and using arc for over 7 months and never had any issue I know how to install mods/arc/atmosphere/sigpatches, etc.  I did a clean format and back up of my working mods that have had no issues up to this point.  I have the latest stable versions of both ARC and Atmosphere, the switch boots into fusee and cfw just fine.  I launch smash, arc does not pop up saying that I've installed it nor generates a config, just loads vanilla smash, both arc and mods for smash do not work, homebrew and apps work as intended.  I have 0 idea what is going on.  Same issue happened when I tried it with older versions of both ARC and Atmosphere, just so I made sure it wasn't just because of the updated ARC and Atmosphere, I have 0 idea how to resolve this issue and it's bugging me, a lot.

### Configuration

I don't have one since ARC will not generate one.

### Minimal modpack to observe the issue

https://www.mediafire.com/file/idhph2jgbrzinnk/ultimate.7z/file

**Comment by DCKomet** [comment]
I'm having the same issue with arcopolis not loading and I've been doing this for about 4 months.

**Comment by DCKomet** [comment]
I retried on a old and new version and ARC just doesn't load period or start with the configuration file menu even after a clean wipe and on FAT32, boots into vanilla ultimate. all of my other CFW works aside from ARC.

**Comment by Raytwo** [comment]
Have you read the changelog for the release as well as the issue it redirects to? Sounds to me like you don’t have Skyline. Try following the instructions here: #157
