### ISSUE TITLE
[Incorrect behavior][ARCropolis version]: DLC Characters past Steve aren't appearing when using ARC

### ISSUE THREAD

**Issue by Flowersfor** [Raytwo/ARCropolis#171]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1

### Atmosphere Version

1.2.2

### Smash Version

13.0.0

### ARCropolis Version

2.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

When not using ARC Sephiroth, Aegis, Kazuya and Sora all appear, however when I use ARC they don't appear on the CSS. Unlock message for them doesn't appear either upon reinstalling the game and running ARC, while other DLC unlocks appear.

### Context

I've tried deleting game files, save data, reinstalling all DLC, reinstalling NCA's, the works. For full transparency I'm using Tinfoil for the downloads, but like I said the DLC characters appear when I'm not using ARC so I don't think the downloads are the issue.

### Configuration

[infos]
version = "2.1.1"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "0.0.0.0"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"

**Comment by jozz024** [comment]
make sure you dont have a ui_chara_db.prc file in any of your mods.

**Comment by Flowersfor** [comment]
I'll check, although this was an issue before I installed any mods.
