### ISSUE TITLE
[Bug][infinite loading][crash?] [ARCropolis version]: Brief description of the issue

### ISSUE THREAD

**Issue by LeonCamero** [Raytwo/ARCropolis#173]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

2.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

This also occurs offline as well. You will just get stuck in an endless loop loading in. Choosing a modded character during battle arena or offline and loading into the stage causes online arenas to "shutdown", however, modded players are stuck on loading before battle.

Tested with friends.

### Configuration

Changed TOML file to add here:

[infos]
version = "2.1.1"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "upd.arcropolis.com"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"

### Crash report

None found.

### Minimal modpack to reproduce the crash

[mods.zip](https://github.com/Raytwo/ARCropolis/files/7646628/mods.zip)

Are you joking? 10mb limit?

**Comment by AwesomeKirito** [comment]
I think you got a non WiFi safe mod, does it happen offline?

**Comment by LeonCamero** [comment]
> I think you got a non WiFi safe mod, does it happen offline?


Wifi safe mods only. Doesn't do the same offline.

**Comment by Raytwo** [comment]
Hey there, thanks for opening an issue, but you did not copy paste your crash report, your configuration or provide a modpack to reproduce the issue ourselves. Please edit your issue to provide these so we can look into it.

**Comment by LeonCamero** [comment]
> Hey there, thanks for opening an issue, but you did not copy paste your crash report, your configuration or provide a (minimal) modpack to reproduce the issue ourselves. Please edit your issue to provide these so we can look into it.
> 
> You also did not even tell what character causes the issue, are we supposed to guess everything ourselves?

It doesn't crash so there is no crash report to give. It only gets stuck on the loading screen before you can play. It turns out that anyone with mods will have the same issue. I believe all you have to do is choose a modded character to reproduce it.

If you aren't having this issue, then it's probably on my end. But I'm pretty sure it's the updated version causing it.

**Comment by LeonCamero** [comment]
@Raytwo 

Edited my report. I wasn't able to get the crash report at first until recently. I did not use a mod Pack however, but Individual characters and had no issues.

**Comment by LeonCamero** [comment]
Closing issue. I was able to enter the game while having some mods on. It's probably an mod error that's causing the infinite loading.

**Comment by Raytwo** [comment]
Yeah it is an already known issue, thanks for reporting anyways!
