### ISSUE TITLE
[Incorrect behavior] [ARCropolis version 3.0.0-beta]: Attempting to load the game with an NSO inside a mod folder prevents it from booting.

### ISSUE THREAD

**Issue by DShip91** [Raytwo/ARCropolis#175]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.1.0

### ARCropolis Version

3.0.0-beta 0.5

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Context

I installed the Mario Series Bowser mod to my ultimate/mods folder with the included .nro file added to the mod's folder (the release notes don't explain what I'm supposed to do with the NRO so I renamed it plugin.nro as stated in the notes) but that only causes ARCropolis to panic and the game to refuse to boot.

### Configuration

version = '3.0.0-beta.0.5'
debug = false
auto_update = true
beta_updates = true
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

### Crash report

Thread '<unnamed>' panicked at 'Invalid UTF-8 sequence: invalid UTF-8 sequence of 1 bytes from index 0', /home/runner/.cargo/git/checkouts/skyline-rs-652bad0610bd03a8/7f1403f/src/lib.rs:63:19

### Minimal modpack to reproduce the crash

Any mod that includes a Skyline plugin in addition to file replacements.

**Comment by blu-dev** [comment]
Yep so this is a NRO hook issue that needs to be resolved. I'm aware of it and will attempt a fix on NRO hook.

**Comment by DShip91** [comment]
> Yep so this is a NRO hook issue that needs to be resolved. I'm aware of it and will attempt a fix on NRO hook.

Keep me posted. :)

**Comment by Raytwo** [comment]
As far as I know, this was fixed as of ARCropolis 3.0.0 so I’ll be closing this. If qi’m mistaken, feel free to reopen an issue!
