### ISSUE TITLE
[Crash] [ARCropolis version]: 3.0.0-beta 0.5 Crahses after switch logo

### ISSUE THREAD

**Issue by Demonslayerx8** [Raytwo/ARCropolis#176]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.4

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta 0.5

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Crashes all the time after switch logo finishes.

I'll send atmosphere crash log, plus arcropolis logs.

### Configuration

[config.zip](https://github.com/Raytwo/ARCropolis/files/7687441/config.zip)

### Crash report

[01639072251_01006a800016e000.zip](https://github.com/Raytwo/ARCropolis/files/7687455/01639072251_01006a800016e000.zip)

**Comment by blu-dev** [comment]
Remove arcropolis, does the issue persist?

**Comment by blu-dev** [comment]
Also this is not an arcropolis issue. If seen this brought to my attention a few times, but ultimately just update nro_hook and see if that resolves the issue

**Comment by blu-dev** [comment]
I have replied to the issue with no response for 4-5 days. If the issue is not resolved by the above steps you can either create a new one or leave a comment here, but I am closing the issue as this is not an arcropolis issue.
