### ISSUE TITLE
[Crash] [ARCropolis version 3.0.0 Beta 5]: Parcel plugin crashes on startup

### ISSUE THREAD

**Issue by TripleLJ** [Raytwo/ARCropolis#177]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0 beta 5

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Attempting to utilize the runtime PRC plugin (https://github.com/blu-dev/parcel) causes crashes . While the Switch boot animation is looping a pop-up will appear saying, "The software was closed because an error occured" before the game can load. 

Disabling the plugin from ARCadia immediately fixes the issue. 

Currently using it on the following file: 
param/in_game/result_parameter.prc

I have not tested any other files. 

The issue does not occur on v2.1.1.

### Configuration

version = '3.0.0-beta.0.5'
debug = false
auto_update = true
beta_updates = true
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x2A8 (2168-0001)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000137
    Process Flags:               00000077
    User Exception Address:      00000038aa3b3000
Exception Info:
    Type:                        Instruction Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   00000000000080a1
    Thread Name:                 Thread_0x0000002A94568568
    Stack Region:                00000056d5a45000-00000056d5a49000
    Registers:
        X[00]:                   000000040d0002d4
        X[01]:                   00000004e402cb84
        X[02]:                   0000002a94578518
        X[03]:                   00000056d5a48d10
        X[04]:                   0000000000000073
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   0000000000000000
        X[08]:                   00000004e4030eb4
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   00000000000ab9dd
        X[12]:                   00000056d5a48910
        X[13]:                   2f736e6967756c70
        X[14]:                   656372617062696c
        X[15]:                   00000056d5a48a88
        X[16]:                   0000000000000000
        X[17]:                   0000002a948bf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   000000002f656e69
        X[19]:                   0000006d80720000
        X[20]:                   0000006d81de0000
        X[21]:                   0000006d810d0bfc
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000056d5a48fb0
        LR:                      0000002a94560f3c (Skyline + 0x1f3c)
        SP:                      00000056d5a48cc0
        PC:                      0000000000000000
    Stack Trace:
        ReturnAddress[00]:       0000002a948bd984 (nnSdk + 0x338984)
        ReturnAddress[01]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0056d5a48cc0 00 0a 0d 81 6d 00 00 00 f8 0b 0d 81 6d 00 00 00
                                 0056d5a48cd0 b0 f3 55 94 2a 00 00 00 00 0d a0 8c 2a 00 00 00
                                 0056d5a48ce0 44 00 00 00 00 00 00 00 58 43 58 94 2a 00 00 00
                                 0056d5a48cf0 c7 64 49 91 de c0 52 24 de 7c 47 92 e0 c8 a7 b3
                                 0056d5a48d00 3a cd 1f 1c 07 11 a6 30 df 9e 1f 5e c1 a5 29 4e
                                 0056d5a48d10 b4 0e 03 e4 04 00 00 00 48 8d a4 d5 56 00 00 00
                                 0056d5a48d20 48 8d a4 d5 56 00 00 00 00 60 03 00 00 00 00 00
                                 0056d5a48d30 40 02 3f 81 6d 00 00 00 00 07 77 81 6d 00 00 00
                                 0056d5a48d40 00 40 58 94 2a 00 00 00 00 00 00 00 2a 00 00 00
                                 0056d5a48d50 c0 00 3f 81 6d 00 00 00 00 01 3f 81 6d 00 00 00
                                 0056d5a48d60 40 00 3f 81 6d 00 00 00 06 00 00 00 00 00 00 00
                                 0056d5a48d70 20 00 3e 81 6d 00 00 00 14 00 00 00 00 00 00 00
                                 0056d5a48d80 1e 00 00 00 00 00 00 00 80 8e a4 d5 56 00 00 00
                                 0056d5a48d90 58 43 58 94 2a 00 00 00 00 00 00 00 00 00 00 00
                                 0056d5a48da0 64 17 56 94 2a 00 00 00 10 17 56 94 2a 00 00 00
                                 0056d5a48db0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000038aa3b3a00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0038aa3b3a00 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a20 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a30 d3 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a40 90 d7 66 07 00 00 00 00 d3 0c 00 00 00 00 00 00
                                 0038aa3b3a50 6e 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3a90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3aa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3ab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3ac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3ad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3ae0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0038aa3b3af0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           8
    Module 00:
        Address:                 0000002a8c9dc000-0000002a8ca00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000002a8ca00000-0000002a8ca02000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000002a8ca04000-0000002a903cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000

**Comment by blu-dev** [comment]
Ah, so currently parcel is not supported on the latest beta. I intend to support it but it uses an API that is currently only present in the 2.X.X versions of ARCropolis
