### ISSUE TITLE
[Incorrect behavior][3.0.0-beta0.5]: Incorrect Buffer Returned by the ARCropolis API

### ISSUE THREAD

**Issue by jozz024** [Raytwo/ARCropolis#178]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta0.5

### Version channel

Beta

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

The buffer returned by the api should have been in the format of a .prc file to be read using prc::read_stream, but instead this was the result:
[buffer.zip](https://github.com/Raytwo/ARCropolis/files/7699108/buffer.zip)

 

### Context

Was trying to have the prc-rs crate print the contents of the prc. here's my code

> #![feature(concat_idents)]
> #![feature(proc_macro_hygiene)]
> 
> use prc;
> use arcropolis_api::*;
> 
> #[arc_callback]
> fn amiibo_db_callback(hash: u64, mut data: &mut [u8]) -> Option<usize> {
> //    load_original_file(hash, &mut data);
>     let mut reader = std::io::Cursor::new(&mut data);
>     println!("{:?}", prc::read_stream(&mut reader));
>     return Some(reader.position() as usize);
> }
> 
> const MAX_FILE_SIZE: usize = 0xFFFF;
> 
> #[skyline::main(name = "ui_amiibo_db_patch")]
> fn main() {
>     amiibo_db_callback::install("ui/param/database/ui_amiibo_db.prc", MAX_FILE_SIZE);
> }

(load_original_file commented out because it would hang)

### Configuration

[config.zip](https://github.com/Raytwo/ARCropolis/files/7699117/config.zip)

**Comment by blu-dev** [comment]
Ah so I can tell you that you do have to call load original file, which would be why it's dying trying to read the data you get passed in. I'll look at it

**Comment by jozz024** [comment]
i assumed so, but load original file was crashing the game, so yeah i was a bit confused

**Comment by blu-dev** [comment]
This should be resolved now in beta-0.6. Please test and let me know if the issue persists!
