### ISSUE TITLE
TRACKING ISSUE FOR 3.0.0 BETA-2

### ISSUE THREAD

**Issue by blu-dev** [Raytwo/ARCropolis#183]
### Context

If you are experiencing any of the following at random or consistently:
* Infinite loading (with animated loading icon in the bottom and the ability to continuously iterate through tips)
* Crashed loader threads (infinite load where the icon animates but you can't iterate through tips)
* UI freeze (nothing animates, but no crash report)
* Crash

And you have confirmed that the issue is with arcropolis/mod loading, please leave the following information:
* SD card format
* Approximately when the last time you formatted your SD card was
* Which mods you were using (like literally what you selected when you were going to crash), and links (either to zip or to GB post if applicable)
* config file
* log file
Please zip the files so that I can grab them and collect them, please name them after your github username so I don't have to keep renaming them

**Comment by DevorySSBU** [comment]
- FAT32
- About two months ago. Sora Release.
- C03 Byleth against C02 Byleth on a stage: '[More competitive Garreg Mach Monastery](https://gamebanana.com/mods/339330)'
- Log and Config files are both in the whole ZIP Folder ([HERE](https://discord.com/channels/447823426061860879/447940880922574848/920515652702330941))

**Comment by Err0ne0us** [comment]
- FAT32
- Around June/July 2021
- Giving Male Wii Fit a Ponytail
- Mod, log and configs included in download below

[(Err0ne0us).zip](https://github.com/Raytwo/ARCropolis/files/7717504/Err0ne0us.zip)

**Comment by SorcererPonse** [comment]
- FAT32
- Last month, don't remember the exact day
- Just some custom music and a stage mod, with no custom skins selected. All involved are in the zip file.
- Everything needed is included in the zip file.
[SorcererPonse.zip](https://github.com/Raytwo/ARCropolis/files/7739954/SorcererPonse.zip)

**Comment by Angstdiscord** [comment]
Random infinite loading, generally before a match starts, at the VS screen.

Seems to occur because of the file logger being enabled. Disabling it stops the problem.

SD card format fat32
Approximately when the last time you formatted your SD card was: Over a year ago
Completely arbitrary.

**Comment by GarnetSunset** [comment]
- FAT32
- Since I switched to the beta, when it first came out afaik
- This mod, but it only breaks when I use a character that's NOT Sephiroth along with them. Sephiroth vs Sephiroth it works, but if I do Sephiroth vs anyone else the video breaks and gets stuck on a white screen. https://gamebanana.com/mods/38814
- Here's my logs!
[2021-12-27_17-48-47.zip](https://github.com/Raytwo/ARCropolis/files/7781250/2021-12-27_17-48-47.zip)

**Comment by Raytwo** [comment]
With 3.0.0 finally released, I'll be closing this. Thanks for the reports everybody!
