### ISSUE TITLE
[Incorrect behavior][ARCropolis 3.0.0 Beta 2.1]: Added Fighter animations are not loaded correctly

### ISSUE THREAD

**Issue by WuBoytH** [Raytwo/ARCropolis#184]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta2.1

### Version channel

Beta

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

I added an animation called `attack_lw3_2` to Terry, which should have given him a punch instead of a kick. However, when I switched to that motion, it plays the last animation Terry was in, but still runs `attack_lw3_2`'s acmd scripts.

### Context

I just pressed down tilt.

### Screenshot

The bug, showing when I press Down Tilt, it simply plays his wait animation, but with the new motion kind's acmd scripts. If you were crouching, it'd play the crouch animation instead, but with that hitbox:
https://user-images.githubusercontent.com/26860994/146206289-d4a20afe-930a-4c10-8a1f-638fffdf1998.mp4

The added file loaded in arcropolis-server.
<img width="417" alt="the new file loaded, as shown by arcropolis-server" src="https://user-images.githubusercontent.com/26860994/146206008-dfa8d51b-efa6-4b37-a34a-49d500200961.png">

Screenshot of my config.json:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/26860994/146207014-c4081231-e0a8-483b-9891-0a4efcf78e83.png">

### Configuration

version = '3.0.0-beta.2.1'
debug = true
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'rom:/arcropolis/workspaces/The WuBoy Ultimate Modpack/umm/'
extra_paths = []

[logger]
logger_level = 'Info'
log_to_file = false

### Minimal modpack to observe the issue

https://drive.google.com/file/d/17bkIiDcWEONaUC-Pbp_Qn7Cvux7-cpnN/view?usp=sharing

**Comment by blu-dev** [comment]
Please attach a file log so that I can see ARCropolis's loader thread information

**Comment by WuBoytH** [comment]
[2021-12-15_17-17-15.log](https://github.com/Raytwo/ARCropolis/files/7721468/2021-12-15_17-17-15.log)
Here you go, this log has info up until loading Terry into training mode.

**Comment by WuBoytH** [comment]
This got fixed in like 3.0.0 beta 2.5 or 2.6
