### ISSUE TITLE
[Feature suggestion] Update Setup wiki to include manual install of Skyline

### ISSUE THREAD

**Issue by KaniDev** [Raytwo/ARCropolis#190]
### What would the feature do?

The [wiki](https://github.com/Raytwo/ARCropolis/wiki/Setup) currently shows how to install ARCropolis, but having to install Skyline manually isn't mentioned anywhere.
I was remodding my game after a while, and I couldn't figure out why it wasn't working by reading the wiki, until I found out on the release page. Updating it would help users troubleshoot their errors by having clear and extensive steps to follow.

Best regards and thanks for the work done !

**Comment by Raytwo** [comment]
That is a fair point, I completely forgot about that. Thanks for reminding us!

**Comment by Raytwo** [comment]
Done, thank you for your report!
