### ISSUE TITLE
[Crash] [v3.0.0-beta.2.4]: Consistent Crashes when loading Special Icy Night Battlefield

### ISSUE THREAD

**Issue by Angstdiscord** [Raytwo/ARCropolis#191]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

[v3.0.0-beta.2.4

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

After selecting the character, small BF consistently crashes at the loading screen before the battle. Works great on the stable release. Regular BF seems to load but occasionally infinite loads. Doesn't seem to matter what character is selected.

### Configuration

version = '3.0.0-beta.2.4'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'warn'
log_to_file = false

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  000000000000008e
    Process Flags:               00000077
    User Exception Address:      0000002a62ee0000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000610
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000000000904f1
        X[02]:                   000000000009f9c1
        X[03]:                   0000000000000008
        X[04]:                   0000002077345260 (cross2_Release.nss + 0x3541260)
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   000000673dbebf50
        X[08]:                   00000066c04781f8
        X[09]:                   0000000000018010
        X[10]:                   0000000000000018
        X[11]:                   0000000000000000
        X[12]:                   0000000000018008
        X[13]:                   0000000000ffffff
        X[14]:                   0000002f7fd0414f
        X[15]:                   ffffffffffffffff
        X[16]:                   000000207c5b8ee8
        X[17]:                   000000207bcbf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   000000207c425c38
        X[19]:                   00000000000904f1
        X[20]:                   0000000000000200
        X[21]:                   00000066c0478000
        X[22]:                   0000002079134000
        X[23]:                   00000066c0490290
        X[24]:                   0000000000000003
        X[25]:                   00000066c0491498
        X[26]:                   0000000000000200
        X[27]:                   0000002079134000
        X[28]:                   00000066c04913b8
        FP:                      00000066c56806b0
        LR:                      0000002077363810 (cross2_Release.nss + 0x355f810)
        SP:                      00000066c5680390
        PC:                      00000020773639e0 (cross2_Release.nss + 0x355f9e0)
    Stack Trace:
        ReturnAddress[00]:       0000002077366cb8 (cross2_Release.nss + 0x3562cb8)
        ReturnAddress[01]:       0000002076f5eecc (cross2_Release.nss + 0x315aecc)
        ReturnAddress[02]:       0000002076428d18 (cross2_Release.nss + 0x2624d18)
        ReturnAddress[03]:       00000020763e61ec (cross2_Release.nss + 0x25e21ec)
        ReturnAddress[04]:       00000020763dc4dc (cross2_Release.nss + 0x25d84dc)
        ReturnAddress[05]:       00000020764d9a00 (cross2_Release.nss + 0x26d5a00)
        ReturnAddress[06]:       0000002076409be8 (cross2_Release.nss + 0x2605be8)
        ReturnAddress[07]:       00000020752de4d0 (cross2_Release.nss + 0x14da4d0)
        ReturnAddress[08]:       0000002075161d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[09]:       000000207734d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[10]:       0000002077340538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[11]:       00000020775cf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[12]:       000000207bcbcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 00000035ca890c00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0035ca890c00 00 00 01 00 09 00 00 00 80 61 28 00 e8 f3 67 c5
                                 0035ca890c10 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890c20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890c30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 0035ca890c40 01 00 7b 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 0035ca890c50 28 00 7b 01 e8 f3 67 c5 66 00 28 00 00 00 00 00
                                 0035ca890c60 00 00 00 00 18 00 00 00 10 01 68 c5 66 00 18 00
                                 0035ca890c70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890c80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890c90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890ca0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890cb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890cc0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890cd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890ce0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0035ca890cf0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 0000002073ddc000-0000002073e00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000002073e00000-0000002073e02000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000002073e04000-00000020777cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000207b24a000-000000207b5b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 000000207b95f000-000000207b978000
        Name:                    Skyline
        Module Id:               466072583325300530AA2813B517F4123CAE0C28000000000000000000000000
    Module 05:
        Address:                 000000207b985000-000000207bec6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:
        Address:                 000000081484a000-0000000814cae000
        Name:                    HDR
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
Thread Report:
Number of Threads:               31
Threads[00]:
    Thread ID:                   0000000000000602
    Thread Name:                 MainThread
    Stack Region:                00000044e26bf000-00000044e27bf000
    Registers:
        X[00]:                   00000044e27bbb38
        X[01]:                   00000044e27bbb3c
        X[02]:                   0000000000000001
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000044e27bbb50
        LR:                      000000207bcbe498 (nnSdk + 0x339498) (_ZN2nn2os6detail30InterProcessEventImplByHorizon4WaitEjb + 0x88)
        SP:                      00000044e27bbb20
        PC:                      000000207bd0e900 (nnSdk + 0x389900)
    Stack Trace:
        ReturnAddress[00]:       000000207b9abf1c (nnSdk + 0x26f1c)
        ReturnAddress[01]:       000000207bd94460 (nnSdk + 0x40f460)
        ReturnAddress[02]:       000000207bd93328 (nnSdk + 0x40e328)
        ReturnAddress[03]:       000000207bdaf034 (nnSdk + 0x42a034)
        ReturnAddress[04]:       0000002077672c24 (cross2_Release.nss + 0x386ec24)
        ReturnAddress[05]:       000000207754aafc (cross2_Release.nss + 0x3746afc)
        ReturnAddress[06]:       00000020740c9cf0 (cross2_Release.nss + 0x2c5cf0)
        ReturnAddress[07]:       000000207bc22a2c (nnSdk + 0x29da2c) (_ZN2nn4init5StartEmmPFvvES2_ + 0x4c)
        ReturnAddress[08]:       0000002073e000c0 (nnrtld + 0xc0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0044e27bbb20 38 bb 7b e2 44 00 00 00 38 7f 24 d5 66 00 00 00
                                 0044e27bbb30 50 bb 7b e2 44 00 00 00 74 5a cb 7b b9 81 2b 00
                                 0044e27bbb40 e0 bb 7b e2 44 00 00 00 38 7f 24 d5 66 00 00 00
                                 0044e27bbb50 c0 bb 7b e2 44 00 00 00 1c bf 9a 7b 20 00 00 00
                                 0044e27bbb60 00 00 00 00 00 00 00 00 7c e8 72 77 ff ff ff ff
                                 0044e27bbb70 00 70 13 79 20 00 00 00 00 40 27 78 20 00 00 00
                                 0044e27bbb80 90 bc 7b e2 44 00 00 00 01 00 00 00 00 00 00 00
                                 0044e27bbb90 05 40 04 f0 00 00 00 00 10 be 7b e2 44 00 00 00
                                 0044e27bbba0 00 00 00 00 00 00 00 00 78 bd 7b e2 44 00 00 00
                                 0044e27bbbb0 80 52 0d c1 66 00 00 00 d8 bd 7b e2 44 00 00 00
                                 0044e27bbbc0 10 bd 7b e2 44 00 00 00 60 44 d9 7b 20 00 00 00
                                 0044e27bbbd0 f0 bb 7b e2 44 00 00 00 88 b1 72 77 ff ff ff ff
                                 0044e27bbbe0 00 00 00 00 00 00 00 00 d0 01 28 c0 66 00 00 00
                                 0044e27bbbf0 10 bc 7b e2 44 00 00 00 40 b1 72 77 20 00 00 00
                                 0044e27bbc00 c8 01 28 c0 66 00 00 00 08 00 28 c0 66 00 00 00
                                 0044e27bbc10 50 bc 7b e2 44 00 00 00 7c e8 72 77 20 00 00 00
    TLS Address:                 0000002a62ee0200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002a62ee0200 00 00 01 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee0210 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee0220 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee0230 53 46 43 49 01 00 00 00 03 00 00 00 00 00 00 00
                                 002a62ee0240 00 00 00 00 07 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee0250 03 00 7b 01 1b 48 18 c0 00 00 00 00 00 00 00 00
                                 002a62ee0260 00 00 00 00 18 00 00 00 e0 bb 7b e2 44 00 18 00
                                 002a62ee0270 00 00 00 00 00 00 00 00 03 0d 08 00 00 04 0a 00
                                 002a62ee0280 08 04 0a 00 04 02 14 00 00 00 00 00 00 00 00 00
                                 002a62ee0290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002a62ee02f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[01]:
    Thread ID:                   0000000000000603
    Thread Name:                 NxSystemThread
    Stack Region:                000000452c5d2000-000000452c5d3000
    Registers:
        X[00]:                   000000452c5d2b5c
        X[01]:                   000000452c5d2d74
        X[02]:                   0000000000000001
        X[03]:                   ffffffffffffffff
        X[04]:                   ffffffffffffffff
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000452c5d2b60
        LR:                      000000207bcbd464 (nnSdk + 0x338464) (_ZN2nn2os6detail22MultiWaitImplByHorizon20WaitSynchronizationNEiPjil + 0x24)
        SP:                      000000452c5d2b40
        PC:                      000000207bd0e900 (nnSdk + 0x389900)

### Minimal modpack to reproduce the crash

https://drive.google.com/file/d/1BzPdltUmNCokGVlpk2frLTFSoJrPjuCl/view?usp=sharing

**Comment by blu-dev** [comment]
Thank you for reporting. I can reproduce, I will be taking a look.

**Comment by Angstdiscord** [comment]
Closing this, since we resolved this privately.
