### ISSUE TITLE
[Crash] [v3.0.0-beta.2.4]: Occasional Random Crashes on Boot, even without changing mods

### ISSUE THREAD

**Issue by Angstdiscord** [Raytwo/ARCropolis#192]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

[v3.0.0-beta.2.4

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

No

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [X] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Right before opening cutscene, the game occasionally crashes

### Configuration

version = '3.0.0-beta.2.4'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'info'
log_to_file = true

### Crash report

[01640206215_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7765194/01640206215_01006a800016e000.log)

### Minimal modpack to reproduce the crash

too inconsistent for a specific mod.

**Comment by Raytwo** [comment]
Welp, 2 months late but I genuinely think you just had a nasty mod, also this was on beta 2.4 so if the issue remains, please reopen an issue.
