### ISSUE TITLE
[Infinite loading][ARCropolis version 3.0.0-beta.2.6]: Game may infinite load or crash if multiple custom skins are involved

### ISSUE THREAD

**Issue by SorcererPonse** [Raytwo/ARCropolis#193]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.5

### Smash Version

13.1.0

### ARCropolis Version

3.0.0-beta2.6

### Version channel

Beta

### SD card formatting

FAT32

### Can the infinite loading be consistently reproduced?

Yes

### In what situation does it happen?

- [X] During the Smash ball loading on boot
- [X] During the loading for a battle
- [X] At random
- [ ] After a long time playing
- [ ] Offline
- [ ] Online

### Context

When loading into a Smash battle, or sometimes when trying to load after the title screen, or sometimes when picking characters, the game will either infinite load or crash if a custom skin is chosen for a character. I have changed no settings in ARCropolis beyond shutting off my file logger to see if it alleviates the issue and the problem still persists. It doesn't seem to matter which skins I select, as long as they're not vanilla, the game will sometimes infinitely load, and even when adding extra computer players, the game may actually crash on character select. It is very random and seems to decide when it wants to do it.

### Configuration

version = '3.0.0-beta.2.6'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'sd:/ultimate/Default/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Off'
log_to_file = false

### Minimal modpack to reproduce the infinite loading

Does not matter which mod is selected, custom skins will sometimes refuse to load

**Comment by Demonslayerx8** [comment]
I can confirm that this does happen even to me, and was able to get a crash report, but I also included my log file too.
[log files.zip](https://github.com/Raytwo/ARCropolis/files/7777672/log.files.zip)
.

**Comment by Nin10Doug** [comment]
Can confirm as well as mentioned in my issue not long ago.
https://github.com/Raytwo/ARCropolis/issues/189
