### ISSUE TITLE
[Feature suggestion] Ability to turn off conflict manager.

### ISSUE THREAD

**Issue by EvanScribe** [Raytwo/ARCropolis#194]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### What would the feature do?

I like messing around with a ton of mods, and I prefer risking the chance of crashing if it gives me some more interesting mod combinations. Having some way to disable the conflict manager, with a warning not to report any crashes this gives, would be very useful!

### How should it be implemented?

Ability to toggle the manager, even if it's hidden away.

**Comment by Raytwo** [comment]
> I'd second this as conflict manager can be counter-intuitive in some cases. For example, if I put the same mod over all of my wi-fi unsafe mods so I don't go online, the conflict manager no longer allows it.

To be fair that sounds more like you not doing things properly (disabling the wifi unsafe mods) than it being counter-intuitive. Mod overwrite has always been considered an issue in ARCropolis as it can easily lead to a crash if the right conditions are met.

I’m going to have to decline this suggestion as the goal is to make the user experience smoother and less likely to run into exotic crashes that are difficult to debug.
