### ISSUE TITLE
[Crash] [ARCropolis version 3.0.0]: Every time I try to use Sonic in a match it crashes.

### ISSUE THREAD

**Issue by MikeyProHD** [Raytwo/ARCropolis#197]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-Beta 2.6

### Version channel

Beta

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

So I'm trying to use Acropolis 3.0.0 Beta, but it keeps crashing in certain situations. At first, when I booted up smash ultimate there was a pop-up telling me that there was a conflict JSON file that told me what mods were causing the conflict. It was just an unrestricted camera mod that I had so I deleted that. I lanched smash ultimate again and there was no pop-up for any conflicts, so I thought I was solid. But when I tried to use training mode with a Sonic skin mod that I had, it still crashed, which is weird considering how no character skins were mentioned in the conflict JSON file.

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000091
    Process Flags:               00000077
    User Exception Address:      0000003b1f5cf000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000478
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000000000904c3
        X[02]:                   000000000009f9b3
        X[03]:                   0000000000000008
        X[04]:                   000000411d745260 (cross2_Release.nss + 0x3541260)
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   0000001844850e60
        X[08]:                   00000018404782a0
        X[09]:                   0000000000018010
        X[10]:                   0000000000000018
        X[11]:                   0000000000000000
        X[12]:                   0000000000018008
        X[13]:                   0000000000ffffff
        X[14]:                   0000002507282a03
        X[15]:                   ffffffffffffffff
        X[16]:                   00000041229b8ee8
        X[17]:                   00000041220bf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   0000004122825c38
        X[19]:                   00000000000904c3
        X[20]:                   0000000000000329
        X[21]:                   0000001840478000
        X[22]:                   000000411f534000
        X[23]:                   0000001840490338
        X[24]:                   0000000000000004
        X[25]:                   0000001840491498
        X[26]:                   0000000000000329
        X[27]:                   000000411f534000
        X[28]:                   00000018404913b8
        FP:                      0000001844850ed0
        LR:                      000000411d763810 (cross2_Release.nss + 0x355f810)
        SP:                      0000001844850bb0
        PC:                      000000411d7639e0 (cross2_Release.nss + 0x355f9e0)
    Stack Trace:
        ReturnAddress[00]:       000000411a80ffbc (cross2_Release.nss + 0x60bfbc)
        ReturnAddress[01]:       000000411a5b25b0 (cross2_Release.nss + 0x3ae5b0)
        ReturnAddress[02]:       000000411a85cb2c (cross2_Release.nss + 0x658b2c)
        ReturnAddress[03]:       000000411b6e2350 (cross2_Release.nss + 0x14de350)
        ReturnAddress[04]:       000000411b561d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[05]:       000000411d74d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[06]:       000000411d740538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[07]:       000000411d9cf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[08]:       00000041220bcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 0000003a490ccc00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 003a490ccc00 00 00 01 00 09 00 00 00 40 80 28 00 b8 fa 84 44
                                 003a490ccc10 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccc20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccc30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 003a490ccc40 01 00 7b 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 003a490ccc50 28 00 7b 01 b8 fa 84 44 18 00 28 00 00 00 00 00
                                 003a490ccc60 00 00 00 00 18 00 00 00 90 0e 85 44 18 00 18 00
                                 003a490ccc70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccc80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccc90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccca0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490cccb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490cccc0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490cccd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490ccce0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003a490cccf0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           6
    Module 00:
        Address:                 000000411a1dc000-000000411a200000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 000000411a200000-000000411a202000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 000000411a204000-000000411dbcb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000412164a000-00000041219b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 0000004121d5f000-0000004121d78000
        Name:                    Skyline
        Module Id:               466072583325300530AA2813B517F4123CAE0C28000000000000000000000000
    Module 05:

### Minimal modpack to reproduce the crash

Soap Shoes Sonic: https://gamebanana.com/mods/175200
Type G Sonic: https://gamebanana.com/mods/342942
You may not need to download these to recreate the crash, as I have certain Sonic slots that don't have any skin mods on them (I don't think I had any voice mods for Sonic on the vanilla slots, and I know for a fact that I don't have any effect mods for Sonic), but I would still test Sonic with the linked mods above just to be safe.

**Comment by MikeyProHD** [comment]
I closed this issue by accident.

**Comment by Raytwo** [comment]
Hello, sorry for the very late reply, odd question I know but: Would you happen to live in Europe? Or at least, outside of North America.

I've observed an issue where people living outside of the US but using us_en as their region (in ARCropolis' config) instead of eu_en could cause crashes in certain circumstances (related to how patching is performed since file addition).

Consider checking this and letting me know?

**Comment by CarterBugg** [comment]
probably for the better lol
