### ISSUE TITLE
[Crash][Aborting][Bug?] [ARCropolis version]: 3.0.0 beta 2.6

### ISSUE THREAD

**Issue by LeonCamero** [Raytwo/ARCropolis#198]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0 beta 2.6

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

After loading acropolis beta for the first time, I was given conflict errors and have activated logging to see what is causing the errors to occur on the second run. I've tested merging the mod files that were conflicting; at first and it seem to have fixed the conflicts. However, after deleting some effect files and merging separated mod files that were causing conflict (which has fixed the conflict issues), the system suddenly just says "this software is aborting" and follows with check to see if your smash ultimate game file is corrupted (it's not, which is always the results). 
The following error shows before leaving:

Error code: 2--0069

0
Error: 0x258402

### Configuration

version = '3.0.0-beta.2.6'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = true

### Crash report

[01642479611_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7886162/01642479611_01006a800016e000.log)

### Minimal modpack to reproduce the crash

Unnecessary since this occurred after fixing the conflict files.

**Comment by LeonCamero** [comment]
Side note: Arcropolis version 2.1.1 allows me to enter the game with no issues.

**Comment by jozz024** [comment]
send the file log

**Comment by LeonCamero** [comment]
> send the file log

That's the issue. I am unable to even access that. It gives me a file that says shared.lut and unshared.lut and no longer provides any files but the crash report given. I am currently testing to see why I am constantly getting the aborting issue, and not when I revert to version 2.1.1

**Comment by LeonCamero** [comment]
[01642487420_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7886732/01642487420_01006a800016e000.log)

same results after 4 tries. I will see if this re-occurs after removing the sound file since this was the last thing I can remember that was an conflicting file.

**Comment by LeonCamero** [comment]
I got in! Apparently all you had to do was do a Fix Bit in the hekate software and it will find the offsets that are causing this issue.

**Comment by pleasehelpmeeeee** [comment]
> I got in! Apparently all you had to do was do a Fix Bit in the hekate software and it will find the offsets that are causing this issue. i hope that eventually that conflict thing is removed. it has been a headache.
      
do i use fusee to launch super smash or hakete?

**Comment by pleasehelpmeeeee** [comment]
beacause im having the same issue as you if you can make a video of how to fix this error it will be really help :) im new lol
