### ISSUE TITLE
[Crash] [ARCropolis version]: Unable to view replays when you save it under a different stage mod, when in previous versions that was possible

### ISSUE THREAD

**Issue by glazedonut** [Raytwo/ARCropolis#199]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0 v2.6

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Game turns black when you try to view a replay that was saved under a different stage mod. For example, I used to have a moonville smashville mod, and after I changed the smashville stage skin to something else, any and all replays saved on smashville can no longer be seen. this was an issue with arcropolis since 2.1.1. Viewing the same replays under different stage mods were possible before, and it would be great if I can do it again

### Crash report

No crash, honestly dont know what category to put this issue under, as it is also not infinite loading. 

### Minimal modpack to reproduce the crash

Save a replay under a vanilla stage mod, and try to view the same replay after you install a mod for that stage

**Comment by Raytwo** [comment]
Sorry but replays are something that I'd rather not touch (for security reasons, as they can be uploaded) in any way of form. I have no idea what could even have happened but I don't intend to fix this.
