### ISSUE TITLE
Crashing on game startup

### ISSUE THREAD

**Issue by fhi5fhiu8tg** [Raytwo/ARCropolis#20]
The game crashes when there are any files in either the arc folder or ultimate/mods. Removing the files makes the game run as normal.
[01602660802_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/5376487/01602660802_01006a800016e000.log)

**Comment by Raytwo** [comment]
Yes, I am aware of the issue and am working on fixing it. Please download version 0.9.0 when it releases later today (hopefully)
