### ISSUE TITLE
[Incorrect behavior][3.0.0-beta.2.6]: .msbt files that have country codes do not fall under conflicts during conflict detection

### ISSUE THREAD

**Issue by ryannguyen96** [Raytwo/ARCropolis#203]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.0

### Atmosphere Version

1.2.5

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta.2.6

### Version channel

Beta

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

ARC is supposed to check for file conflicts so the user is aware what files would conflict with each other in loading. However, if the file is the type to have the country code flag (eg. "+us_en") appended in its name, it won't detect a conflict with another file with the same name that doesn't have the country code flag.

### Context

I was updating my UI One slot name template, which utilizes the msg_name.msbt file to function. I regularly have been loading this mod with HDR for over a month with no issues. However, this time, after I updated it, I realized none of my names were properly loading. I disabled and isolated multiple mod folders through Arcadia to debug and found out that it only broke when running alongside HDR. Upon further inspection, my UI One Slot mod uses msg_name.msbt, while HDR uses msg_name+us_en.msbt (or +eu_en).  

In the entire duration I was using my UI One Slot name mod, this was never an issue until my last update. Ergo, it means that ARCropolis has been loading the msg_name.mbst from my UI One Slot mod first, and not loading msg_name+us_en.msbt from HDR, hence why I was unaware of this conflict. Once it started prioritizing the msg_name+us_en.msbt file from HDR and my UI names broke, I realized HDR was not detecting conflicts for files with those country flags. Once I deleted the msg_name+us_en.msbt from HDR, my One Slot mod functioned properly again. 

### Screenshot

Unnecessary for this report.

### Configuration

[Shiga UI Names + Organized CSS.zip](https://github.com/Raytwo/ARCropolis/files/7966334/Shiga.UI.Names.%2B.Organized.CSS.zip)

Above is my One Slot UI names mod. I don't believe I need to attach HDR for you since you're a dev for it.

**Comment by Raytwo** [comment]
That’s most likely because conflicts are checked by file paths in the mod directory and not by « in-game conflict ». While it can probably be made to work that way, it could be that file addition can make it harder to work around. Will keep you updated when something has been decided

**Comment by blu-dev** [comment]
So the reasoning for this is because, as Ray stated, the conflict checker is done on the actual filesystem files, so it sees `msg_name.msbt` different from `msg_name+us_en.msbt`. The most I can do is issue a warning when that file is detected and inserted into the hash table because at that point the conflict checker has already run it's course. I will also probably set it to use the regional one as priority so that the msg_name.msbt can be a fallback.

**Comment by ryannguyen96** [comment]
Yep, I figured that's just how the logic was. I think this is just a less common edge case. 

I think your solution is best, blu. Prioritize region, use non-region one as fallback, and issue a warning for _potential_ file conflicts for the user to be aware of.
