### ISSUE TITLE
[Crash] [3.0.0 Beta 3]: prc patching using prctxt crashes the game.

### ISSUE THREAD

**Issue by WuBoytH** [Raytwo/ARCropolis#204]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta.3

### Version channel

Beta

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [X] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

When attempting to use the new prc patching feature in ARCropolis, the game freezes, presumably when it attempts to load and patch the file.

### Configuration

version = '3.0.0-beta.3'
debug = false
auto_update = false
beta_updates = false
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'rom:/arcropolis/workspaces/The WuBoy Ultimate Modpack/umm/'
extra_paths = []

[logger]
logger_level = 'Info'
log_to_file = true

### Crash report

[01643743832_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7981529/01643743832_01006a800016e000.log)

### Minimal modpack to reproduce the crash

https://drive.google.com/file/d/1ani0IlD-2cokseGD_udie7f7-HaoO5Yx/view?usp=sharing

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 3.1.0!
