### ISSUE TITLE
[Feature suggestion] Camera and Movie one-slot 

### ISSUE THREAD

**Issue by puli2004** [Raytwo/ARCropolis#206]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### What would the feature do?

The feature is to one-slot camera animations and movie animation for fighters
mods/camera/fighter/[fighter code name]/c0#/(camera animation files)
mods/prebuilt;/movie/[fighter code name]/c0#/(movie animation files)
I'm also not sure if these are all what is need to one slot fighters completely. I'm going to keep researching but from the looks of it the fighter file seems to be one-slot in the characters. Only had problems with these two. 

### How should it be implemented?

It should work the same way the one slot fighters work. It just gets added and one sloted to the slot instead of it being shared.

**Comment by Raytwo** [comment]
Hey there, ARCropolis’ objective is only to replace and add files to the game, as well as allow for some collaboration with other plugins as an intermediate with the game.

Editing the code to turn hardcoded paths into non-hardcoded ones is out of scope for the time being.

There is indeed code for one-slot camera and movies, but it is (afaik) unused.

i’ve been shown the following on the SUM server that could be a good lead if you want to tackle this yourself:
`smash::app::lua_bind::FighterManager::prepare_movie(fighter_manager,Hash40::new("prebuilt:/movie/fighter/jack/c00/final_00.h264"));`
