### ISSUE TITLE
[FV4] [3.0.0-beta.3.1]: After installing the everything crits mod, the game crashes when loading before the fight.

### ISSUE THREAD

**Issue by MarioGlitchy9** [Raytwo/ARCropolis#208]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta.3.1

### Version channel

Beta

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

After loading smash, everything was fine up until the loading screen. I have the Minecraft skin grabber mod and the training pack mod along with the everything crits mod... they could be factors

### Configuration

version = '3.0.0-beta.3.1'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

### Crash report

AtmosphÃ¨re Crash Report (v1.7):
Result:                          0xCA8 (2168-0006)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000082
    Process Flags:               00000077
    User Exception Address:      000000107fb05000
Exception Info:
    Type:                        User Break
    Address:                     00000055d890e998 (nnSdk + 0x389998)
    Break Reason:                0x0
    Break Address:               0000000000000000
    Break Size:                  0x0
Crashed Thread Info:
    Thread ID:                   0000000000000288
    Thread Name:                 ResInflateThread
    Stack Region:                00000004caabf000-00000004caaff000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000000000000000
        X[02]:                   0000000000000000
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000004caafe830
        LR:                      00000055d88b8180 (nnSdk + 0x333180) (nnosBreak + 0x10)
        SP:                      00000004caafe820
        PC:                      00000055d890e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       00000055d8a9ec10 (nnSdk + 0x519c10) (__nnmusl_GetTlsValue + 0x0)
        ReturnAddress[01]:       00000000080012e0 ([00000000] + 0x12e0)
        ReturnAddress[02]:       00000000a99f5090 (smashline_hook + 0x26090) (abort_hook + 0x40)
        ReturnAddress[03]:       0000000000000008
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0004caafe820 c0 e9 af ca 04 00 00 00 c0 e9 af ca 04 00 00 00
                                 0004caafe830 40 e8 af ca 04 00 00 00 10 ec a9 d8 55 00 00 00
                                 0004caafe840 50 e8 af ca 04 00 00 00 e0 12 00 08 00 00 00 00
                                 0004caafe850 70 65 3b a1 17 00 00 00 90 50 9f a9 00 00 00 00
                                 0004caafe860 68 3b a0 a9 00 00 00 00 01 00 00 00 00 00 00 00
                                 0004caafe870 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0004caafe880 40 e6 9f a9 00 00 00 00 00 00 00 00 00 00 00 00
                                 0004caafe890 24 e3 20 a1 17 00 00 00 01 00 00 00 00 00 00 00
                                 0004caafe8a0 0c e3 20 a1 17 00 00 00 c0 e9 af ca 04 00 00 00
                                 0004caafe8b0 c8 e9 af ca 04 00 00 00 18 0e 3b a1 17 00 00 00
                                 0004caafe8c0 70 ea af ca 04 00 00 00 08 26 39 a1 17 00 00 00
                                 0004caafe8d0 88 65 3b a1 17 00 00 00 72 a8 31 a1 17 00 00 00
                                 0004caafe8e0 74 af 31 a1 17 00 00 00 63 b8 2d a1 17 00 00 00
                                 0004caafe8f0 74 a8 31 a1 17 00 00 00 28 66 3b a1 17 00 00 00
                                 0004caafe900 01 00 00 00 00 00 00 00 ec 59 72 00 34 00 00 00
                                 0004caafe910 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00
    TLS Address:                 0000001751999400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 001751999400 06 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 001751999410 02 00 00 00 1e 00 00 00 00 00 00 00 00 00 00 00
                                 001751999420 53 46 43 4f 00 00 00 00 80 04 00 00 00 00 00 00
                                 001751999430 00 00 00 00 00 00 00 00 0a 00 00 00 00 00 00 00
                                 001751999440 00 00 00 00 00 00 00 00 68 20 00 00 00 00 00 00
                                 001751999450 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001751999460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001751999470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001751999480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001751999490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0017519994f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

### Minimal modpack to reproduce the crash

https://cdn.discordapp.com/attachments/672589167317745678/939966258617671760/modpack.zip

**Comment by Raytwo** [comment]
Hello, sorry for the very long delay, your crash report indicates that the issue comes from another plugin (most likely the crit plugin judging by the NROs in your modpack). Consider reporting the issue to whoever made it!
