### ISSUE TITLE
[Feature suggestion] Add a way to disable all but one conflicting file.

### ISSUE THREAD

**Issue by DShip91** [Raytwo/ARCropolis#209]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### What would the feature do?

In the event of a conflict, there should be a way to prioritize one copy of a file above the others

### How should it be implemented?

Ideally, this would be done by making a switch of sorts that disables every copy of a specific file except for the one that the user has chosen. However, I know nothing about coding and therefore do not know how well such a feature would work if at all.

**Comment by blu-dev** [comment]
Conflicts automatically default to whichever mod was first discovered that had that file. If you have a lot of conflicts it can lead to some mods just not working, but the reality of this is that *you* need to manage your conflicts better. The intended user experience is to not have the conflict message pop-up when you start the game, if it does please just take the time to fix it.
