### ISSUE TITLE
Crashing on launch, with latest version and no mods

### ISSUE THREAD

**Issue by glencoe2004** [Raytwo/ARCropolis#21]
Even when there are no mods in romfs and a clean install is used, Smash Bros. crashes almost immediately upon opening the game.  

[01602708801_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/5380834/01602708801_01006a800016e000.log)

**Comment by Raytwo** [comment]
Judging by the crash log, this is a Skyline issue, not something from ARCropolis. Please double check your install.
