### ISSUE TITLE
[Panic][ARCropolis version Beta 3.1]: Arcadia Mod Manager in E-Shop "Thread has Panicked"

### ISSUE THREAD

**Issue by BeastMiner32** [Raytwo/ARCropolis#210]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6|S

### Smash Version

13.0.1

### ARCropolis Version

Beta 3.0.0-3.1

### Version channel

Beta

### SD card formatting

FAT32

### Can the panic be consistently reproduced?

Yes

### Context

I launched the new verision of the beta today to attempt to use the built in Arcadia Mod Manager on the E-Shop Button. When pressed the following error message is reported and a restart of the game is required to do anything else. I also updated arcadia to work with the 3.0.0 file system.

### Screenshot

![2022020917210400-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/99372438/153315697-4e8c8ac5-35f1-4e3b-8057-020c94e0297c.jpg)

### Configuration

Initially Tested:

version = '3.0.0-beta.3.1'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

Also tested with this setup:

version = '3.0.0-beta.3.1'
debug = false
auto_update = true
beta_updates = true
no_web_menus = true <-- Changed
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

**Comment by Raytwo** [comment]
Strange, this code shouldn't throw an error considering there is a check right before to make sure it exists. 
I'll be changing the way it works just in case, thanks for reporting.
