### ISSUE TITLE
[Incorrect behavior][ARCropolis version]: Brief description of the issue

### ISSUE THREAD

**Issue by AvnonIdo** [Raytwo/ARCropolis#212]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

2.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

I have installed 2 mods through the quasar mod manager, the "ease of training" mod and jam1garner's smash "minecraft skins mod".
Both mods appear in the ingame mod manager and are marked as enabled but when I try to use them they don't work.
I have installed the "ease of training" independently before and it worked (of course I deleted it before installing it through the mod manager) additionally I have "The training modpack" mod installed and it is working fine.

### Configuration

[infos]
version = "2.1.1"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "upd.arcropolis.com"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"

**Comment by Raytwo** [comment]
Tested it myself, worked fine. Closing this
