### ISSUE TITLE
[Panic] [3.0.0]: Minecraft Skins Plugin Crashing

### ISSUE THREAD

**Issue by RocketRaccoon27** [Raytwo/ARCropolis#214]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta.3.2

### Version channel

Beta

### SD card formatting

FAT32

### Can the panic be consistently reproduced?

Yes

### Context

I go into training mode with the plugin, a custom skin selected, and minecraft_2_layer loaded as well. I do something and then leave. Right before the CSS appears, the crash/panic happens. I close out the panic box and the skin selector is shown where I am able to load a skin. Of course, this is all to no avail as the game crashes shortly after.

### Screenshot

https://i.imgur.com/QnsJTpf.jpg

### Configuration

Config File:

version = '3.0.0-beta.3.2'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

I don't think my config will help very much so I will link my crash reports.

[Crash Report #1](https://pastebin.com/yFX1ipgq)
[Crash Report #2](https://pastebin.com/QD4AhUYv)
[Crash Report #3](https://pastebin.com/kYX0vA6V)
[Crash Report #4](https://pastebin.com/d5yn5g5d)

**Comment by dfox20** [comment]
I get the exact same issue and error message/error code and writing with these plugins on latest everything, Switch 13.2.0, Arc 3.2, latest skyline and up to date plugins and have been tested separately. They last worked on Arc 3.0 Beta 2.6
Cloud victory plugin here: https://gamebanana.com/sounds/51503
25 M plugin: https://gamebanana.com/mods/309758
Mega Charizard X Fire plugin: https://gamebanana.com/mods/347988
Press start to end results plugin: https://gamebanana.com/mods/315835
There is other plugins I wanted to add like the One Slot Victory Results and the unique result screen plugin but i'm sure the same issue will happen with them. The only Plugin I managed to get working is the Axes Toggle one for the camera.

**Comment by Raytwo** [comment]
Tested Smash Minecraft Skins plugin on beta-3.3, worked just fine, closing this.
