### ISSUE TITLE
[Incorrect behavior][ARCropolis version]: arcropolis.toml file never created

### ISSUE THREAD

**Issue by maxwell1755** [Raytwo/ARCropolis#215]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

2.1.0

### Version channel

Stable

### SD card formatting

exFat

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

The arcropolis.toml file that is supposed to be generated on the first boot was never created. So there is no config folder which causes lots of problems with ARCadia. 

### Context

Trying to install ARCropolis

### Screenshot

![image](https://user-images.githubusercontent.com/67136352/155871826-4044e9d3-c2b6-4dad-81c7-704ed7132bfa.png)
![Screenshot 2022-02-27 005459](https://user-images.githubusercontent.com/67136352/155871847-e5a01dd8-3076-462f-92b4-ff80ebc955e5.png)

### Configuration

This is the problem. I do not have a configuration file

**Comment by Raytwo** [comment]
Ah, that's unfortunate. We'll get rid of this file with the following update which should come out in a few days, hopefully the problem will be solved thanks to that.
