### ISSUE TITLE
I installed the latest release (Minecraft Edition) and I have no idea what happened

### ISSUE THREAD

**Issue by kckarnige** [Raytwo/ARCropolis#22]
![2020101511400000-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/32397453/96153307-8bbd5580-0edb-11eb-8443-50e34018fa04.jpg)

**Comment by Raytwo** [comment]
Yeah sorry about that, the issue is fixed and will be put in the latest release soon.
