### ISSUE TITLE
[Crash] [ARCropolis version 3.0.0]: I still can't use Sonic without the game crashing

### ISSUE THREAD

**Issue by MikeyProHD** [Raytwo/ARCropolis#220]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Every time I try to use Sonic in a match, it still crashes. I don't have any conflicts yet it still causes crashes.

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000096
    Process Flags:               00000077
    User Exception Address:      0000002f493d0000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   00000000000003f5
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   000000000009037f
        X[02]:                   000000000009f8e9
        X[03]:                   0000000000000008
        X[04]:                   0000004af2d45260 (cross2_Release.nss + 0x3541260)
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   00000005043b02e0
        X[08]:                   0000000500494348
        X[09]:                   0000000000018010
        X[10]:                   0000000000000018
        X[11]:                   0000000000000000
        X[12]:                   0000000000018008
        X[13]:                   0000000000ffffff
        X[14]:                   0000002507282a03
        X[15]:                   ffffffffffffffff
        X[16]:                   0000004af7fb8ee8
        X[17]:                   0000004af76bf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   0000004af7e25c38
        X[19]:                   000000000009037f
        X[20]:                   0000000000000329
        X[21]:                   0000000500494000
        X[22]:                   0000004af4b34000
        X[23]:                   00000005004ac3e0
        X[24]:                   0000000000000005
        X[25]:                   00000005004ad498
        X[26]:                   0000000000000329
        X[27]:                   0000004af4b34000
        X[28]:                   00000005004ad3b8
        FP:                      00000005043b0350
        LR:                      0000004af2d63810 (cross2_Release.nss + 0x355f810)
        SP:                      00000005043b0030
        PC:                      0000004af2d639e0 (cross2_Release.nss + 0x355f9e0)
    Stack Trace:
        ReturnAddress[00]:       0000004aefe0ffbc (cross2_Release.nss + 0x60bfbc)
        ReturnAddress[01]:       0000004aefbb25b0 (cross2_Release.nss + 0x3ae5b0)
        ReturnAddress[02]:       0000004aefe5cb2c (cross2_Release.nss + 0x658b2c)
        ReturnAddress[03]:       0000004af0ce2350 (cross2_Release.nss + 0x14de350)
        ReturnAddress[04]:       0000004af0b61d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[05]:       0000004af2d4d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[06]:       0000004af2d40538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[07]:       0000004af2fcf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[08]:       0000004af76bcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 000000301214fa00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00301214fa00 00 00 01 00 09 00 00 00 00 50 28 00 38 ef 3a 04
                                 00301214fa10 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fa20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fa30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 00301214fa40 01 00 75 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 00301214fa50 28 00 75 01 38 ef 3a 04 05 00 28 00 00 00 00 00
                                 00301214fa60 00 00 00 00 18 00 00 00 10 03 3b 04 05 00 18 00
                                 00301214fa70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fa80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fa90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214faa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214fae0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00301214faf0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 0000004aef7dc000-0000004aef800000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000004aef800000-0000004aef802000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000004aef804000-0000004af31cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 0000004af6c4a000-0000004af6fb7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 0000004af735f000-0000004af7378000
        Name:                    Skyline
        Module Id:               466072583325300530AA2813B517F4123CAE0C28000000000000000000000000
    Module 05:

**Comment by Raytwo** [comment]
Ok but where's the modpack to reproduce the crash? Or at least links to the mods you're using, including plugins? Except if you're telling me Sonic crashes out of the box with no mods, which I doubt.

**Comment by Raytwo** [comment]
Also you already have an [open issue](https://github.com/Raytwo/ARCropolis/issues/197) about this. I’ll be closing this one now.
