### ISSUE TITLE
[Panic][3.0.0]: random thread has pacnicked and a random file location

### ISSUE THREAD

**Issue by kokun15** [Raytwo/ARCropolis#221]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the panic be consistently reproduced?

Yes

### Context

when i try to load in classic mode i get this error with every character in the vs screen

### Screenshot

![Error_20220303_174107_00](https://user-images.githubusercontent.com/100884053/156672219-50fbd268-4bd9-4168-bdb5-402303de9e1d.jpg)

**Comment by Raytwo** [comment]
Sounds like you had a plugin that communicates with ARCropolis. The bug has been fixed in ARCropolis 3.1.0, please update when offered to!
