### ISSUE TITLE
[Qualify of Life] re-releasing 3.0.0 beta 3.2

### ISSUE THREAD

**Issue by awesomeme22** [Raytwo/ARCropolis#223]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### Explain what could get improvements.

The current full release of 3.0.0 has had panic issues across the board from many users. While I am sure this is being worked on, in the meantime, I would recommend re-releasing the beta version 3.2, as this is the consensus last version of 3.0 that did not have these issues. 

### How could we make this better?

A new temporary release to be public for 3.0.0 beta version 3.2.

**Comment by Raytwo** [comment]
No.
