### ISSUE TITLE
[Panic] [3.0.0]: Error code 2--0069

### ISSUE THREAD

**Issue by metasaint** [Raytwo/ARCropolis#226]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

The panic happens everytime I wake up the console from sleep mode.
![photo_2022-03-10_16-02-49](https://user-images.githubusercontent.com/101344791/157689865-077e7c6b-6aee-4755-85a6-61902a500e9d.jpg)

### Crash report

[01646924985_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8224543/01646924985_01006a800016e000.log)

**Comment by Raytwo** [comment]
Disable debug field in your configuration.

**Comment by metasaint** [comment]
thanks. disabling debug fixed the problem
