### ISSUE TITLE
[Incorrect behavior][ARCropolis version 3.0.0]: Music mods not loading with new discovery system

### ISSUE THREAD

**Issue by cmargroff** [Raytwo/ARCropolis#228]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

Sma5h Music exported mod will automatically disable each time ARCcopolis starts, it does not log anything to log file regardless of log level setting. Setting ARCropolis to "Use legacy mod discovery system" allows the mod to load with no issues. The mod files have not changed between version 3.0.0-beta2.7.1 and 3.0.0 stable.

### Configuration

There is no generated toml file even after modifying the options in the ui.

**Comment by Raytwo** [comment]
Hello, have you read the fine prints in the changelog for 3.0.0? Sounds to me like you missed the part saying you need to use the mod manager to re-enable your mods using the new system.

**Comment by cmargroff** [comment]
Yes I read that, yes I went in and re-enabled all mods after upgrading. The issue is that _each_ time I enable the mod, press save, and then let ARCropolis restart the game, it just loads again with my music mod disabled.

**Comment by Raytwo** [comment]
Is that the only mod you have that’s enabled? Or do you have more and only that one is not loading?

**Comment by cmargroff** [comment]
It is not the only mod that I have installed nor is it the only mod that I have enabled. It is not a conflicted mod either as I have no other mods for the music library and it doesn't get flagged as conflicted though it doesnt really seem that it ever gets to load at all. Is it possible that it is getting disabled because of the total size of the mod?

**Comment by AterialDawn** [comment]
I can confirm this is also happening to me. I upgraded from an older version (unsure) to this latest 3.0.0 version. My mods were disabled on boot, went into the Arcadia-rs(?) menu, enabled the ones i wanted enabled, pressed + to save, pressed yes on the prompt to restart the game. When the game restarted, my mods were still not enabled. Attempted this 3 times over 2 different profiles with no change, mods wouldn't enable. The only thing that got them enabled was to enable the legacy discovery system.

Same FW version as op, acropolis, smash, and atmosphere. SDcard formatted to ExFat

**Comment by Raytwo** [comment]
I've been able to confirm this behavior but not to isolate the cause.
However some changes are planned to prevent this from happening. Until then, I'd recommend using the legacy discovery system as OP mentioned.

**Comment by Raytwo** [comment]
Could you please try [this version](https://cdn.discordapp.com/attachments/447940880922574848/952705729406586910/libarcropolis.nro) (and disable legacy discovery while doing so) and provide some feedback on your issue please?

**Comment by AterialDawn** [comment]
Seems to work! I disabled autodiscovery, manually enabled all my mods again, and this time they actually stayed enabled. I did not get prompted to restart the game after hitting + to save though.

**Comment by Raytwo** [comment]
Glad to hear it! Feel free to use this version for the time being until 3.1.0 is ready, shouldn't be too long.

**Comment by cmargroff** [comment]
I can test shortly, what was the fix?

**Comment by Raytwo** [comment]
> I can test shortly, what was the fix?

I've tried to mitigate the issue when it comes to reading/writing your enabled mods (an actual fix will be available in 3.1.0), managed to make the mod manager not crash and improved the menu's framerate a ton which should make it usable now.

**Comment by Raytwo** [comment]
> I can test shortly, what was the fix?

Sooo... did you test?

**Comment by cmargroff** [comment]
Sorry. Yes I tested last night. Works fine but the mods list does weird jumping around, either list items are inserting at weird times and the scroll bar is the wrong size and position. This doesn't affect mods loading just UI issue.

**Comment by Raytwo** [comment]
Yeah I'm aware, someone is working on reworking it even more and it should be included in the official release. So can I close this issue?

**Comment by cmargroff** [comment]
Yep yep
