### ISSUE TITLE
I Dont Have Steve On My Modded Smash

### ISSUE THREAD

**Issue by AwesomeKirito** [Raytwo/ARCropolis#23]
I downloaded the latest arc and steve doesnt pop up as a fighter even though i bought him as dlc, I would love some assistance, i want to play steve smash mods

**Comment by CoatlessEskimo** [comment]
Did you redump your own data.arc with Steve included? If not then you will need to delete data.arc and redump it. Also, data.arc is related to UltimateModManager, and is not related to ARCropolis in almost any way on its own. If you're explicitly using only mods compatible with ARCropolis, and not using UMM, then delete data.arc.

**Comment by Demonslayerx8** [comment]
it's cause your using an outdated ui_chara_db.prc file

please remove it, and steve will show up on the CSS. CoatlessEskimo, please don't give out false info, if he was using a data.arc (8.0.0 or 8.1.0, the game wouldn't even start up on 9.0.0)

**Comment by CoatlessEskimo** [comment]
My apologies to both of you. I didn't know any better, and that's my bad.

**Comment by AwesomeKirito** [comment]
Alright so i see steve but when i select them the game freezes
