### ISSUE TITLE
[Qualify of Life] Prior to file discovery, offer to enable newly found mods

### ISSUE THREAD

**Issue by techyCoder81** [Raytwo/ARCropolis#230]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### Explain what could get improvements.

Automatically defaulting newly added mods to "on" would simplify some user experience in some situations, as non advanced users often don't read and get confused initially when their mods are not on by default. This was the legacy behavior in the first place, so returning to that initial behavior may help with the user experience.

### How could we make this better?

It would be convenient if, prior to file discovery, a quick check of the `ultimate/mods` directly was made to see if there are any new mods that are not currently in the configuration (because the user just added them). If new mods are found, adding them to the configuration, set to "on" by default, would reduce user confusion in some situations, and would improve user experience. 

A further improvement to that would be to use a simple popup to ask if the user _wants_ to enable them.

A further improvement to _that_ would be to have an additional "ask me again?" popup afterwards, to persist the user's choice of default on or default off, as well as if they want to be asked again. This is a bit of a stretch potentially.

**Comment by Raytwo** [comment]
Added for ARCropolis 3.1.0, thanks for the suggestion!
