### ISSUE TITLE
[Incorrect behavior][3.0.0]: Mods do not load on first boot after using another profile

### ISSUE THREAD

**Issue by RocketRaccoon27** [Raytwo/ARCropolis#231]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

Mods should load but do not.

### Context

I switched to another profile playing another game, closed out and then opened Smash back up with my profile. 

### Screenshot

Do not have a screenshot but here is the log verbatim. 

[arcropolis::hashes] Failed to read 'sd:/ultimate/arcropolis/hashes.txt' for hashes. Reason: Custom { kind: Other, error: "Result code: 514" }. There won't be any hash lookups in this run's logs.
[arcropolis::fs] Cannot get the incoming load because the filesystem is not initialized!
[arcropolis::fs] Cannot get the incoming load because the filesystem is not initialized!

### Configuration

Not sure how to extract it.

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 3.1.0
