### ISSUE TITLE
[Crash] [3.0.0]: ARCropolis crashes every time i open the e shop

### ISSUE THREAD

**Issue by Wraiax** [Raytwo/ARCropolis#233]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

I load smash and it all goes according to plan, but when I try to click on the e-shop tab (to open the mod manager), the game crashes, and it says _error code 2--0069_ and, then it does this
![WhatsApp Image 2022-03-16 at 9 15 36 AM](https://user-images.githubusercontent.com/101699839/158546168-6672f0e7-8f37-456f-9ebb-27accfe2815a.jpeg)
![WhatsApp Image 2022-03-16 at 9 15 36 AM (1)](https://user-images.githubusercontent.com/101699839/158546185-3578e8de-d8dc-4b69-9f9b-95dc25538775.jpeg)
after I finish checking for corrupted files it just happens again, but this time, with my mods loaded 

### Configuration

It's not where it's supposed to be, I can't find it

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x258402 (2002-4802)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000095
    Process Flags:               00000077
    User Exception Address:      0000001f3b79a000
Exception Info:
    Type:                        User Break
    Address:                     000000167250e998 (nnSdk + 0x389998)
    Break Reason:                0x0
    Break Address:               0000006585005a38
    Break Size:                  0x4
Crashed Thread Info:
    Thread ID:                   00000000000002f2
    Thread Name:                 MainThread
    Stack Region:                0000006584f0a000-000000658500a000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000006585005a38
        X[02]:                   0000000000000004
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000065850057d0
        LR:                      0000001672308ad8 (nnSdk + 0x183ad8) (_ZN2nn4diag6detail5AbortEPKNS_6ResultE + 0x18)
        SP:                      00000065850057d0
        PC:                      000000167250e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       00000016723074a0 (nnSdk + 0x1824a0) (_ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_z + 0x0)
        ReturnAddress[01]:       000000167215f7e8 (Skyline + 0x7e8)
        ReturnAddress[02]:       000000167237c0d0 (nnSdk + 0x1f70d0) (_ZN2nn2fs8OpenFileEPNS0_10FileHandleEONSt3__110unique_ptrINS0_3fsa5IFileENS3_14default_deleteIS6_EEEEi + 0x0)
        ReturnAddress[03]:       0000003be288a9f4 (arcropolis + 0xfa9f4)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0065850057d0 a0 58 00 85 65 00 00 00 a0 74 30 72 16 00 00 00
                                 0065850057e0 03 00 00 00 65 00 00 00 50 58 00 85 65 00 00 00
                                 0065850057f0 2e 3d b7 72 16 00 00 00 2e 3d b7 72 16 00 00 00
                                 006585005800 2e 3d b7 72 16 00 00 00 00 00 00 00 01 00 00 00
                                 006585005810 02 84 25 00 69 00 00 00 00 00 00 00 00 00 00 00
                                 006585005820 03 00 00 00 65 00 00 00 50 58 00 85 65 00 00 00
                                 006585005830 2e 3d b7 72 16 00 00 00 2e 3d b7 72 16 00 00 00
                                 006585005840 2e 3d b7 72 16 00 00 00 00 00 00 00 01 00 00 00
                                 006585005850 2e 3d b7 72 16 00 00 00 e0 58 00 85 65 00 00 00
                                 006585005860 24 00 00 00 00 00 00 00 80 60 00 85 65 00 00 00
                                 006585005870 24 00 00 00 00 00 00 00 25 00 00 00 00 00 00 00
                                 006585005880 50 04 79 1a 69 00 00 00 40 59 00 85 65 00 00 00
                                 006585005890 00 84 f1 d0 68 00 00 00 00 5a 00 85 65 00 00 00
                                 0065850058a0 20 5a 00 85 65 00 00 00 e8 f7 15 72 16 00 00 00
                                 0065850058b0 f0 fb 1a 21 69 00 00 00 00 00 00 00 00 00 00 00
                                 0065850058c0 b8 5a 00 85 65 00 00 00 01 00 00 00 00 00 00 00
    TLS Address:                 0000001f3b79a200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 001f3b79a200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a230 00 00 00 00 00 00 00 00 0a 00 00 00 00 00 00 00
                                 001f3b79a240 00 00 00 00 00 00 00 00 cc 00 00 00 00 00 00 00
                                 001f3b79a250 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 001f3b79a260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a270 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 00
                                 001f3b79a280 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a290 00 00 00 00 01 00 00 00 d0 5d 00 85 65 00 00 00
                                 001f3b79a2a0 b8 3f 1c 72 16 00 00 00 6c 04 00 00 00 00 00 00
                                 001f3b79a2b0 00 00 00 00 00 00 00 00 10 5d 00 85 65 00 00 00
                                 001f3b79a2c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a2d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a2e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001f3b79a2f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by Raytwo** [comment]
Hey there.
I’m aware of the issue and it has been solved already, new release should be out in the next 24h if everything goes according to plan so make sure to update when it does!
