### ISSUE TITLE
[Incorrect behavior][ARCropolis version]: Mod is installed but ARCropolis refuse to let me use it

### ISSUE THREAD

**Issue by LeTartimorphe** [Raytwo/ARCropolis#234]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Beta

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

I installed mods, and once I go to the folder to activate / disactivate mods, I check all my mods I want, now, the mod should either work or tell me there is a conflict. Instead of this, the mod just don't activate itself, when I go to the folder again after restarting game, the mod automatically removed the mod I asked to activate. And I could restart this for hours, the mod will never get working. (mods aren't corrupted, I tried them on friend's switch)

### Context

I am into mod folder (inside smash bros, at shop's icon), activating mod, restarting game to apply changes, and then the game desactivate from itself

### Configuration

[infos]
version = "2.1.1"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "upd.arcropolis.com"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"

### Minimal modpack to observe the issue

https://gamebanana.com/dl/738259

**Comment by Raytwo** [comment]
Bug is known and fixed, update should release in about a day
