### ISSUE TITLE
[Crash] [ARCropolis 3.0.0]: Custom Music Crashes with 8 Player Smash

### ISSUE THREAD

**Issue by danielkim90** [Raytwo/ARCropolis#235]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [X] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

After I select a custom song, the game usually crashes when trying to select characters for 8 Player Smash.
I tested 8 Player Smash with character skin mods multiple times and it never crashed until I activated the mod for custom music.

### Crash report

[01647709758_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8309749/01647709758_01006a800016e000.log)

**Comment by Raytwo** [comment]
Could you please try with the newest update (3.1.0) and let me know if it still happens? I've heard that some people need to rename or delete/add their mod back at times

**Comment by danielkim90** [comment]
Hi, Thanks for your response! I updated to 3.1.0 and still get the issue with the game crashing at the CSS with 8 Player Smash.

**Comment by Raytwo** [comment]
Do you happen to have lots of mods? We’ve been suspecting that we use too much memory but nothing is confirmed yet

**Comment by danielkim90** [comment]
Hello again. Yes, I have have a lot of character skin mods. On the prior version, it never crashed when I did 8 Player Smash with mods and no custom music. After the update, I tested again by doing 8 Player Smash with mods and no custom music first. It crashed the first time when I didn't even use custom music.

**Comment by Raytwo** [comment]
Yeah seems related to what we suspected then. ARCropolis needs a big change when it comes to memory so we can handle more mods without crashing, and this will take quite a while unfortunately m.

**Comment by danielkim90** [comment]
Okay. No rush and no worries. I really do appreciate your attention to this. For the time being, I can just disable some mods when I want to play 8 Player Smash with friends.

**Comment by danielkim90** [comment]
> Yeah seems related to what we suspected then. ARCropolis needs a big change when it comes to memory so we can handle more mods without crashing, and this will take quite a while unfortunately.

Hello again! 
I updated to 3.1.2.
Do you know if this update addresses the memory issue? I updated to 3.1.2. I only played one 8 player smash game with custom music and experienced no crashing. Just would like to know if I got lucky or if stuff in the background were done to help improve the issue. Thank you!

**Comment by Raytwo** [comment]
Ah nope, you just got lucky! Hopefully it remains that way. Closing this then, have fun!
