### ISSUE TITLE
[Crash] [ARCropolis version 3.1.0]: "Software has closed" popup past switch loading screen

### ISSUE THREAD

**Issue by bandeyawx** [Raytwo/ARCropolis#239]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.1.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

When Arcropolis 3.1.0 plugin is loaded, post Switch-load screen, almost immediately booted out with a "software has closed because an error occured" popup.
Similar issue existed for me on 3.0.0 Stable's plugin, but simply stuck on the Switch-load screen with an infinite load.
Reverting back to earlier versions of Arcropolis (a 3.0 beta in my case) allows mods to continue working perfectly. Issue only appears when a stable 3.0.0 is installed.
ultimate/mods is empty. Outcome does not change regardless of what is in ultimate/mods - no mod folders, one mod folder, or several.
Arcropolis was reinstalled several times (both by a self-drag and drop and by following the in-game nag that asks if you want to install a new stable version it found.)
Skyline was reinstalled several times.
All other plugins are disabled.
Cache folder exists, but is largely empty (13.0.1 folder contains nothing). Deleting folder does not resolve the issue (reappears and issue repeats itself.)
romfs/arc is empty.
Any logs Arcropolis creates in ultimate/arcropolis/logs are empty.
Restarts, reboots, anything similar does not resolve the issue - only booting vanilla (holding L) or reverting to an older beta of Arcropolis has resolved the issue.

### Configuration

version = '3.0.0-beta.3.2'
debug = false
auto_update = true
beta_updates = true
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'sd:/ultimate/mods'
extra_paths = []

[logger]
logger_level = 'Warn'
log_to_file = false

*Yes, I am aware the config file is still reading as the beta - I'm assuming this is because the game is crashing before the config file ever gets a chance to be updated by new arcropolis

### Crash report

*(first ~200 lines)
Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000092
    Process Flags:               00000077
    User Exception Address:      0000000ac6f00000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000018
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   00000000000003c4
    Thread Name:                 Thread_0x0000006063C9E670
    Stack Region:                0000005e182ee000-0000005e184ee000
    Registers:
        X[00]:                   0000000000177a02
        X[01]:                   0000000000000000
        X[02]:                   0000004d421d0000
        X[03]:                   0000000000000000
        X[04]:                   0000006995e60440
        X[05]:                   0000000000000000
        X[06]:                   0000004d421d0000
        X[07]:                   000000000000026f
        X[08]:                   0000004d407a12d0
        X[09]:                   0000000000000000
        X[10]:                   0000000000000018
        X[11]:                   0080000000000000
        X[12]:                   0000000000000000
        X[13]:                   000000000000000a
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000006063977fb0 (nnSdk + 0x1f2fb0) (_ZN2nn2fs6detail12FileAccessor5WriteElPKvmRKNS0_11WriteOptionE + 0x0)
        X[17]:                   00000060643b46d0
        X[18]:                   0000000000000000
        X[19]:                   0000004d407b4bc0
        X[20]:                   0000006995e60440
        X[21]:                   0000004d407b4bc0
        X[22]:                   0000006995e60440
        X[23]:                   0000004d421d0000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000001
        X[26]:                   0000005e184eddd1
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      0000005e184edcc0
        LR:                      000000606397aafc (nnSdk + 0x1f5afc) (_ZN2nn2fs9WriteFileENS0_10FileHandleElPKvmRKNS0_11WriteOptionE + 0xdc)
        SP:                      0000005e184edca0
        PC:                      0000006063978058 (nnSdk + 0x1f3058) (_ZN2nn2fs6detail12FileAccessor5WriteElPKvmRKNS0_11WriteOptionE + 0xa8)
    Stack Trace:
        ReturnAddress[00]:       000000606397aafc (nnSdk + 0x1f5afc) (_ZN2nn2fs9WriteFileENS0_10FileHandleElPKvmRKNS0_11WriteOptionE + 0xdc)
        ReturnAddress[01]:       0000006995e233b4 (arcropolis + 0x1613b4)
        ReturnAddress[02]:       0000006063ab94b8 (nnSdk + 0x3344b8)
        ReturnAddress[03]:       0000006063abd984 (nnSdk + 0x338984)
        ReturnAddress[04]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 005e184edca0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 005e184edcb0 00 00 00 00 00 00 00 00 6f 02 00 00 00 00 00 00
                                 005e184edcc0 10 dd 4e 18 5e 00 00 00 fc aa 97 63 60 00 00 00
                                 005e184edcd0 00 dd 4e 18 5e 00 00 00 08 a8 28 40 4d 00 00 00
                                 005e184edce0 00 00 00 00 00 00 00 00 f2 f2 95 69 00 00 00 00
                                 005e184edcf0 10 cf f4 95 69 00 00 00 08 cf f4 95 69 00 00 00
                                 005e184edd00 6f 02 00 00 00 00 00 00 c8 dd 4e 18 5e 00 00 00
                                 005e184edd10 80 df 4e 18 5e 00 00 00 b4 33 e2 95 69 00 00 00
                                 005e184edd20 88 0b d0 95 69 00 00 00 c8 a9 28 40 4d 00 00 00
                                 005e184edd30 08 a8 28 40 4d 00 00 00 20 3f 75 40 4d 00 00 00
                                 005e184edd40 80 df 4e 18 5e 00 00 00 dc 0b d0 95 69 00 00 00
                                 005e184edd50 63 72 6f 70 6f 6c 69 73 2f 63 6f 6e 66 69 67 2f
                                 005e184edd60 73 64 3a 2f 75 6c 74 69 6d 61 74 65 2f 61 72 63
                                 005e184edd70 20 3f 75 40 4d 00 00 00 8e 00 00 00 00 00 00 00
                                 005e184edd80 53 00 00 00 00 00 00 00 20 3f 75 40 4d 00 00 00
                                 005e184edd90 bc 9e cf 95 69 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 000000160ef4a400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00160ef4a400 06 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a410 02 00 00 00 8e 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a420 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a430 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a450 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00160ef4a4f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 000000605bbdc000-000000605bc00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 000000605bc00000-000000605bc02000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 000000605bc04000-000000605f5cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000606304a000-00000060633b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 000000606375f000-0000006063778000
        Name:                    Skyline
        Module Id:               B44280982D6BBFA90259E041B53C1889D3F10328000000000000000000000000
    Module 05:
        Address:                 0000006063785000-0000006063cc6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:
        Address:                 0000006995cc2000-0000006995e59000
        Name:                    arcropolis
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
Thread Report:
Number of Threads:               09
Threads[00]:
    Thread ID:                   00000000000003bb
    Thread Name:                 MainThread
    Stack Region:                0000005e323ba000-0000005e324ba000
    Registers:
        X[00]:                   0000004d402f003c
        X[01]:                   0000004d402f0040
        X[02]:                   00000000000081ff
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      0000005e324b7e50
        LR:                      0000006063abe998 (nnSdk + 0x339998) (_ZN2nn2os6detail38InternalConditionVariableImplByHorizon4WaitEPNS1_23InternalCriticalSectionE + 0x48)
        SP:                      0000005e324b7e30
        PC:                      0000006063b0e92c (nnSdk + 0x38992c)
    Stack Trace:
        ReturnAddress[00]:       0000006063ab3898 (nnSdk + 0x32e898) (_ZN2nn2os9WaitEventEPNS0_9EventTypeE + 0x48)
        ReturnAddress[01]:       000000606375f5f4 (Skyline + 0x5f4)
        ReturnAddress[02]:       000000605f344c7c (cross2_Release.nss + 0x3740c7c)
        ReturnAddress[03]:       000000605bec9968 (cross2_Release.nss + 0x2c5968) (nnMain + 0x348)
        ReturnAddress[04]:       0000006063a22a2c (nnSdk + 0x29da2c) (_ZN2nn4init5StartEmmPFvvES2_ + 0x4c)
        ReturnAddress[05]:       000000605bc000c0 (nnrtld + 0xc0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 005e324b7e30 40 00 2f 40 4d 00 00 00 00 00 00 00 00 00 00 00
                                 005e324b7e40 20 00 2f 40 4d 00 00 00 3c 00 2f 40 4d 00 00 00
                                 005e324b7e50 80 7e 4b 32 5e 00 00 00 98 38 ab 63 60 00 00 00
                                 005e324b7e60 d8 06 00 00 00 00 00 00 49 7f 4b 32 5e 00 00 00
                                 005e324b7e70 80 0a 7a 40 4d 00 00 00 00 0a 0d 41 4d 00 00 00
                                 005e324b7e80 c0 83 4b 32 5e 00 00 00 f4 f5 75 63 60 00 00 00
                                 005e324b7e90 30 7f 4b 32 5e 00 00 00 10 81 2c 41 4d 00 00 00
                                 005e324b7ea0 50 25 35 5f 60 00 00 00 00 00 00 00 00 00 00 00
                                 005e324b7eb0 01 00 00 00 00 00 00 00 d8 06 00 00 00 00 00 00
                                 005e324b7ec0 00 15 1d 41 4d 00 00 00 49 7f 4b 32 5e 00 00 00
                                 005e324b7ed0 00 0a 0d 41 4d 00 00 00 50 25 35 5f 00 00 00 00
                                 005e324b7ee0 20 7f 4b 32 5e 00 00 00 88 40 55 5f 60 00 00 00
                                 005e324b7ef0 00 00 27 40 4d 00 00 00 08 00 28 40 4d 00 00 00
                                 005e324b7f00 e0 43 00 40 01 00 00 00 c0 0d 00 40 4d 00 00 00
                                 005e324b7f10 78 83 4b 32 5e 00 00 00 01 00 00 00 4d 00 00 00
                                 005e324b7f20 28 96 4b 32 5e 00 00 00 98 3f 55 5f 60 00 00 00
    TLS Address:                 0000000ac6f00200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000ac6f00200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00230 d8 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00240 7c a9 34 1a 04 00 00 00 d8 04 00 00 00 00 00 00
                                 000ac6f00250 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00270 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f00290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000ac6f002f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by Raytwo** [comment]
What about deleting /ultimate/arcropolis/config with 3.1.0? Heard that helps.

**Comment by Raytwo** [comment]
Also I just noticed that something is preventing the game from writing a file, which is very weird.

**Comment by blu-dev** [comment]
Solved by deleting the config folder and rebooting.
