### ISSUE TITLE
motion_list.bin files issue

### ISSUE THREAD

**Issue by JamesAndrewsXV** [Raytwo/ARCropolis#24]
motion_list.bin files seem to not load on time sometimes. Tested using two different switches, one with other mods (skin, model import, music, and .msbt edits) and one with only those edits. 

Most of the time, after starting a match for the first time, frame data edits do not load or partially load (lower landing lag). Upon restarting a match with the same character, the likelihood of these edits appearing increases, but is not guaranteed.

Can submit set of files used when testing upon request.

**Comment by Raytwo** [comment]
Hello,
I am already aware of the issue, problem being that I have no way of making this more reliable for the moment.
I might look until it soon as ARCropolis is undergoing a rewrite, so please check out version 0.10.0 when it comes out.
(Also, sorry for the delay)

**Comment by Raytwo** [comment]
Problem is apparently already fixed. Closing this for now.
