### ISSUE TITLE
[Crash] [3.1.0]: #239 Variant, unable to fix due to recreating config folder

### ISSUE THREAD

**Issue by ElaineLMN** [Raytwo/ARCropolis#244]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.1.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Almost identical to issue #239, except for the fact I have mods in my "mods" folder. On boot, it'll detect new mods, ask to enable them. If I say yes, crash, and then back to issue as described in #239. If I say no, game will load. I can try to enable mods in the manager, and when I restart: crash, and back to #239. I deleted my config folder, but because of the mod enabling, ARC will create another one, and the issue is back. 
EDIT: I tried to downgrade back to an old beta (2.6), which usually fixes problems, and the problem persisted. I saw plugins mentioned in the crash report so I tried removing them, and the problem persisted. My game just no longer gets past the switch screen unless I disable all mods.
EDIT 2: Tried switching to legacy file discovery still no dice.
EDIT 3: Enabling one mod at a time seems to fix the issue, but obviously this is not ideal.
EDIT 4: Enabling TWO things causes the issue again.

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x2A8 (2168-0001)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000084
    Process Flags:               00000077
    User Exception Address:      0000005369e05000
Exception Info:
    Type:                        Instruction Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000230
    Thread Name:                 Thread_0x0000000EF689E670
    Stack Region:                00000011e69e5000-00000011e6a25000
    Registers:
        X[00]:                   00000006a120f1c4 (one_slot_victory + 0x41c4)
        X[01]:                   00000006a120f2d8 (one_slot_victory + 0x42d8)
        X[02]:                   0000000000000000
        X[03]:                   00000033002f0050
        X[04]:                   0000000000000003
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   0000000000000000
        X[08]:                   00000000001881d7
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   000000000024048b
        X[12]:                   0000000000000000
        X[13]:                   7830203a74657366
        X[14]:                   0a30333462333733
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000ef66bf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   0000000000000000
        X[19]:                   0000000ef1f3f431 (cross2_Release.nss + 0x373b431)
        X[20]:                   fffffffffc8c4bd0
        X[21]:                   00000006a12390a8
        X[22]:                   0000000000000003
        X[23]:                   00000011e6a24c58
        X[24]:                   00000011e6a24c23
        X[25]:                   0000000000000001
        X[26]:                   00000011e6a24c30
        X[27]:                   00000011e6a24c70
        X[28]:                   00000006a120db10 (one_slot_victory + 0x2b10) (main + 0x0)
        FP:                      00000011e6a248f0
        LR:                      00000006a120ddc8 (one_slot_victory + 0x2dc8) (main + 0x2b8)
        SP:                      00000011e6a246a0
        PC:                      0000000000000000
    Stack Trace:
        ReturnAddress[00]:       0000000000000004
        ReturnAddress[01]:       0000003300000001
        ReturnAddress[02]:       0000006788ac4158
        ReturnAddress[03]:       00000005d3ce61b0
        ReturnAddress[04]:       00000020fcad8c78
        ReturnAddress[05]:       0000000eee803280
        ReturnAddress[06]:       00000006a1241200
        ReturnAddress[07]:       0000006788ac4158
        ReturnAddress[08]:       00000005d3ce61b0
        ReturnAddress[09]:       00000020fcad8c78
        ReturnAddress[10]:       0000000eee803280
        ReturnAddress[11]:       00000006a1241200
        ReturnAddress[12]:       0000006788ac4158
        ReturnAddress[13]:       00000005d3ce61b0
        ReturnAddress[14]:       00000020fcad8c78
        ReturnAddress[15]:       0000000eee803280
        ReturnAddress[16]:       00000006a1241200
        ReturnAddress[17]:       0000006788ac4158
        ReturnAddress[18]:       00000005d3ce61b0
        ReturnAddress[19]:       00000020fcad8c78
        ReturnAddress[20]:       0000000eee803280
        ReturnAddress[21]:       00000006a1241200
        ReturnAddress[22]:       0000006788ac4158
        ReturnAddress[23]:       00000005d3ce61b0
        ReturnAddress[24]:       00000020fcad8c78
        ReturnAddress[25]:       0000000eee803280
        ReturnAddress[26]:       00000006a1241200
        ReturnAddress[27]:       0000006788ac4158
        ReturnAddress[28]:       00000005d3ce61b0
        ReturnAddress[29]:       00000020fcad8c78
        ReturnAddress[30]:       0000000eee803280
        ReturnAddress[31]:       00000006a1241200
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0011e6a246a0 01 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 0011e6a246b0 c0 14 64 11 33 00 00 00 00 cd cc f1 0e 00 00 00
                                 0011e6a246c0 78 e2 23 a1 06 00 00 00 40 00 21 a1 06 00 00 00
                                 0011e6a246d0 40 4b 64 11 33 00 00 00 cc 70 36 f6 0e 00 00 00
                                 0011e6a246e0 80 e2 23 a1 06 00 00 00 02 00 00 00 00 00 00 00
                                 0011e6a246f0 10 46 23 a1 06 00 00 00 01 00 00 00 00 00 00 00
                                 0011e6a24700 c0 46 a2 e6 11 00 00 00 01 00 00 00 00 00 00 00
                                 0011e6a24710 80 9b 8b fc 20 00 00 00 60 c8 6c f6 0e 00 00 00
                                 0011e6a24720 38 01 00 00 00 00 00 00 12 00 00 00 00 00 00 00
                                 0011e6a24730 c8 5a 9f fc 20 00 00 00 a3 21 df 01 33 00 00 00
                                 0011e6a24740 00 00 00 00 00 00 00 00 73 00 00 00 01 00 00 00
                                 0011e6a24750 73 64 3a 2f 75 6c 74 69 6d 61 74 65 2f 6d 6f 64
                                 0011e6a24760 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0011e6a24770 00 00 00 00 00 00 00 00 c0 25 27 00 33 00 00 00
                                 0011e6a24780 d0 47 a2 e6 11 00 00 00 58 4d a2 e6 11 00 00 00
                                 0011e6a24790 08 00 00 00 00 00 00 00 27 00 00 00 00 00 00 00

### Minimal modpack to reproduce the crash

Literally any mods at all.

**Comment by Raytwo** [comment]
Resolved by removing a broken plugin.
