### ISSUE TITLE
[Crash] [ARCropolis version]: Brief description of the issue

### ISSUE THREAD

**Issue by CarterBugg** [Raytwo/ARCropolis#249]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.0.0

### Atmosphere Version

1.3.0

### Smash Version

13.0.1

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [X] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Every time I go to boot up into Arcropolis, I get a "software closed because an error occurred". The one time it did work, it gave me a "software is aborting" error when I opened the eshop menu in game. I have tried downgrading my version of arcropolis many times, to no avail. If anyone has a solution/fix, it would be greatly appreciated. Thanks!

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000083
    Process Flags:               00000077
    User Exception Address:      0000006a112f1000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000018
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000251
    Thread Name:                 Thread_0x0000001041C9E670
    Stack Region:                000000404bcd4000-000000404bed4000
    Registers:
        X[00]:                   0000000000177a02
        X[01]:                   0000000000000000
        X[02]:                   00000021421d0000
        X[03]:                   0000000000000000
        X[04]:                   0000003b338393ac
        X[05]:                   0000000000000000
        X[06]:                   00000021421d0000
        X[07]:                   0000000000000176
        X[08]:                   00000021407a12d0
        X[09]:                   0000000000000000
        X[10]:                   0000000000000001
        X[11]:                   00000000fffffffd
        X[12]:                   0000000000000000
        X[13]:                   000000000000000a
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   00000010423b46d0
        X[17]:                   0000001041977fb0 (nnSdk + 0x1f2fb0) (_ZN2nn2fs6detail12FileAccessor5WriteElPKvmRKNS0_11WriteOptionE + 0x0)
        X[18]:                   0000000000000000
        X[19]:                   00000021407b4bc0
        X[20]:                   0000003b338393ac
        X[21]:                   00000021407b4bc0
        X[22]:                   0000003b338393ac
        X[23]:                   00000021421d0000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000001
        X[26]:                   000000404bed3dd1
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000404bed3cc0
        LR:                      000000104197aafc (nnSdk + 0x1f5afc) (_ZN2nn2fs9WriteFileENS0_10FileHandleElPKvmRKNS0_11WriteOptionE + 0xdc)
        SP:                      000000404bed3ca0
        PC:                      0000001041978058 (nnSdk + 0x1f3058) (_ZN2nn2fs6detail12FileAccessor5WriteElPKvmRKNS0_11WriteOptionE + 0xa8)
    Stack Trace:
        ReturnAddress[00]:       000000104197aafc (nnSdk + 0x1f5afc) (_ZN2nn2fs9WriteFileENS0_10FileHandleElPKvmRKNS0_11WriteOptionE + 0xdc)
        ReturnAddress[01]:       0000003b337fdf54 (arcropolis + 0x161f54)
        ReturnAddress[02]:       0000001041ab94b8 (nnSdk + 0x3344b8)
        ReturnAddress[03]:       0000001041abd984 (nnSdk + 0x338984)
        ReturnAddress[04]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00404bed3ca0 00 00 00 00 01 00 00 00 00 64 75 40 00 00 00 00
                                 00404bed3cb0 00 00 00 00 00 00 00 00 76 01 00 00 00 00 00 00
                                 00404bed3cc0 10 3d ed 4b 40 00 00 00 fc aa 97 41 10 00 00 00
                                 00404bed3cd0 20 3d ed 4b 40 00 00 00 74 0f 53 3d 10 00 00 00
                                 00404bed3ce0 00 00 00 00 00 00 00 00 a3 90 33 3b 00 00 00 00
                                 00404bed3cf0 e0 7f 92 33 3b 00 00 00 d8 7f 92 33 3b 00 00 00
                                 00404bed3d00 76 01 00 00 00 00 00 00 c8 3d ed 4b 40 00 00 00
                                 00404bed3d10 80 3f ed 4b 40 00 00 00 54 df 7f 33 3b 00 00 00
                                 00404bed3d20 50 3d ed 4b 40 00 00 00 08 a8 28 40 21 00 00 00
                                 00404bed3d30 08 99 6d 33 3b 00 00 00 c8 a9 28 40 21 00 00 00
                                 00404bed3d40 08 a8 28 40 21 00 00 00 00 64 75 40 21 00 00 00
                                 00404bed3d50 80 3f ed 4b 40 00 00 00 5c 99 6d 33 3b 00 00 00
                                 00404bed3d60 63 72 6f 70 6f 6c 69 73 2f 63 6f 6e 66 69 67 2f
                                 00404bed3d70 73 64 3a 2f 75 6c 74 69 6d 61 74 65 2f 61 72 63
                                 00404bed3d80 00 64 75 40 21 00 00 00 8c 00 00 00 00 00 00 00
                                 00404bed3d90 38 56 6d 33 3b 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000062600b5400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0062600b5400 06 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5410 02 00 00 00 94 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5420 53 46 43 4f 00 00 00 00 00 00 00 00 a1 6d 71 f3
                                 0062600b5430 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5450 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b5490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0062600b54f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 0000001039bdc000-0000001039c00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000001039c00000-0000001039c02000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000001039c04000-000000103d5cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000104104a000-00000010413b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 000000104175f000-0000001041778000
        Name:                    Skyline
        Module Id:               B44280982D6BBFA90259E041B53C1889D3F10328000000000000000000000000
    Module 05:
        Address:                 0000001041785000-0000001041cc6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:

**Comment by Raytwo** [comment]
Hey OP,

Seems like ARCropolis is having trouble writing to your SD. Consider running a checkup on your PC?
