### ISSUE TITLE
[Crash] [ARCropolis version]: Error code 2-0069 please help 

### ISSUE THREAD

**Issue by BlueMario22** [Raytwo/ARCropolis#250]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

1 3.2.0

### Atmosphere Version

1.2.6

### Smash Version

1 3.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Every time I go into Eshop on smash ultimate to activate mods the hardware gives me a error message saying aborting operation, i've never had this problem before so I updated Acropolis again & sadly it is the same thin
![IMG_3311](https://user-images.githubusercontent.com/102125778/160211383-0016a945-4dc2-40cd-a2e3-ff853e051dd4.jpeg)
![IMG_3310](https://user-images.githubusercontent.com/102125778/160211390-393d0d46-f73c-4fad-885e-48adf1d4d282.jpeg)
g

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x258402 (2002-4802)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000084
    Process Flags:               00000077
    User Exception Address:      000000149b508000
Exception Info:
    Type:                        User Break
    Address:                     000000727110e998 (nnSdk + 0x389998)
    Break Reason:                0x0
    Break Address:               00000022a2324a38
    Break Size:                  0x4
Crashed Thread Info:
    Thread ID:                   0000000000000233
    Thread Name:                 MainThread
    Stack Region:                00000022a2229000-00000022a2329000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000022a2324a38
        X[02]:                   0000000000000004
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000022a23247d0
        LR:                      0000007270f08ad8 (nnSdk + 0x183ad8) (_ZN2nn4diag6detail5AbortEPKNS_6ResultE + 0x18)
        SP:                      00000022a23247d0
        PC:                      000000727110e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       0000007270f074a0 (nnSdk + 0x1824a0) (_ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_z + 0x0)
        ReturnAddress[01]:       0000007270d5f7e8 (Skyline + 0x7e8)
        ReturnAddress[02]:       0000007270f7c0d0 (nnSdk + 0x1f70d0) (_ZN2nn2fs8OpenFileEPNS0_10FileHandleEONSt3__110unique_ptrINS0_3fsa5IFileENS3_14default_deleteIS6_EEEEi + 0x0)
        ReturnAddress[03]:       00000008f793d9f4 (arcropolis + 0xfa9f4)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0022a23247d0 a0 48 32 a2 22 00 00 00 a0 74 f0 70 72 00 00 00
                                 0022a23247e0 03 00 00 00 22 00 00 00 50 48 32 a2 22 00 00 00
                                 0022a23247f0 2e 3d 77 71 72 00 00 00 2e 3d 77 71 72 00 00 00
                                 0022a2324800 2e 3d 77 71 72 00 00 00 00 00 00 00 01 00 00 00
                                 0022a2324810 02 84 25 00 50 00 00 00 00 00 00 00 00 00 00 00
                                 0022a2324820 03 00 00 00 22 00 00 00 50 48 32 a2 22 00 00 00
                                 0022a2324830 2e 3d 77 71 72 00 00 00 2e 3d 77 71 72 00 00 00
                                 0022a2324840 2e 3d 77 71 72 00 00 00 00 00 00 00 01 00 00 00
                                 0022a2324850 2e 3d 77 71 72 00 00 00 e0 48 32 a2 22 00 00 00
                                 0022a2324860 2d 00 00 00 00 00 00 00 80 50 32 a2 22 00 00 00
                                 0022a2324870 2d 00 00 00 00 00 00 00 2e 00 00 00 00 00 00 00
                                 0022a2324880 10 20 93 93 50 00 00 00 40 49 32 a2 22 00 00 00
                                 0022a2324890 00 70 a8 82 50 00 00 00 00 4a 32 a2 22 00 00 00
                                 0022a23248a0 20 4a 32 a2 22 00 00 00 e8 f7 d5 70 72 00 00 00
                                 0022a23248b0 70 21 77 b5 50 00 00 00 00 00 00 00 00 00 00 00
                                 0022a23248c0 b8 4a 32 a2 22 00 00 00 01 00 00 00 00 00 00 00
    TLS Address:                 000000149b508200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00149b508200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508230 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508240 00 00 00 00 00 00 00 00 67 02 00 00 00 00 00 00
                                 00149b508250 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 00149b508260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508270 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 00
                                 00149b508280 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508290 00 00 00 00 01 00 00 00 d0 4d 32 a2 22 00 00 00
                                 00149b5082a0 b8 3f dc 70 72 00 00 00 1a 7e 00 00 00 00 00 00
                                 00149b5082b0 00 00 00 00 00 00 00 00 10 4d 32 a2 22 00 00 00
                                 00149b5082c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b5082d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b5082e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b5082f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 00000072691dc000-0000007269200000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000007269200000-0000007269202000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000007269204000-000000726cbcb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000727064a000-00000072709b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 0000007270d5f000-0000007270d78000
        Name:                    Skyline
        Module Id:               B44280982D6BBFA90259E041B53C1889D3F10328000000000000000000000000
    Module 05:
        Address:                 0000007270d85000-00000072712c6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:
        Address:                 00000008f7843000-00000008f795e000
        Name:                    arcropolis
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
Thread Report:
Number of Threads:               29
Threads[00]:
    Thread ID:                   0000000000000233
    Thread Name:                 MainThread
    Stack Region:                00000022a2229000-00000022a2329000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000022a2324a38
        X[02]:                   0000000000000004
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000022a23247d0
        LR:                      0000007270f08ad8 (nnSdk + 0x183ad8) (_ZN2nn4diag6detail5AbortEPKNS_6ResultE + 0x18)
        SP:                      00000022a23247d0
        PC:                      000000727110e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       0000007270f074a0 (nnSdk + 0x1824a0) (_ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_z + 0x0)
        ReturnAddress[01]:       0000007270d5f7e8 (Skyline + 0x7e8)
        ReturnAddress[02]:       0000007270f7c0d0 (nnSdk + 0x1f70d0) (_ZN2nn2fs8OpenFileEPNS0_10FileHandleEONSt3__110unique_ptrINS0_3fsa5IFileENS3_14default_deleteIS6_EEEEi + 0x0)
        ReturnAddress[03]:       00000008f793d9f4 (arcropolis + 0xfa9f4)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0022a23247d0 a0 48 32 a2 22 00 00 00 a0 74 f0 70 72 00 00 00
                                 0022a23247e0 03 00 00 00 22 00 00 00 50 48 32 a2 22 00 00 00
                                 0022a23247f0 2e 3d 77 71 72 00 00 00 2e 3d 77 71 72 00 00 00
                                 0022a2324800 2e 3d 77 71 72 00 00 00 00 00 00 00 01 00 00 00
                                 0022a2324810 02 84 25 00 50 00 00 00 00 00 00 00 00 00 00 00
                                 0022a2324820 03 00 00 00 22 00 00 00 50 48 32 a2 22 00 00 00
                                 0022a2324830 2e 3d 77 71 72 00 00 00 2e 3d 77 71 72 00 00 00
                                 0022a2324840 2e 3d 77 71 72 00 00 00 00 00 00 00 01 00 00 00
                                 0022a2324850 2e 3d 77 71 72 00 00 00 e0 48 32 a2 22 00 00 00
                                 0022a2324860 2d 00 00 00 00 00 00 00 80 50 32 a2 22 00 00 00
                                 0022a2324870 2d 00 00 00 00 00 00 00 2e 00 00 00 00 00 00 00
                                 0022a2324880 10 20 93 93 50 00 00 00 40 49 32 a2 22 00 00 00
                                 0022a2324890 00 70 a8 82 50 00 00 00 00 4a 32 a2 22 00 00 00
                                 0022a23248a0 20 4a 32 a2 22 00 00 00 e8 f7 d5 70 72 00 00 00
                                 0022a23248b0 70 21 77 b5 50 00 00 00 00 00 00 00 00 00 00 00
                                 0022a23248c0 b8 4a 32 a2 22 00 00 00 01 00 00 00 00 00 00 00
    TLS Address:                 000000149b508200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00149b508200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00149b508220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by BlueMario22** [comment]
I’ve updated to the most recent Acropolis, with same issue

**Comment by Raytwo** [comment]
Are you using ARCropolis 3.1.1 and not 3.1.1? It addresses a small issue. But do you happen to have a ``sd:/ultimate/mods/`` directory on your SD?
Also consider deleting ``sd:/ultimate/arcropolis/config`` and trying again.

**Comment by BlueMario22** [comment]
Thank so much for the reply, & yes I do have a sd:/ultimate/mods/ directory, so I went ahead & deleted the config folder in sd:/Ultimate/acropolis, & it still sadly gave me the same message

**Comment by BlueMario22** [comment]
After staying on the details screen after the abort message, a error code 2002-4802 popped up im not sure if that helps

**Comment by BlueMario22** [comment]
The current version im on is 1 3.2.0/ ams 1.2 6

**Comment by BlueMario22** [comment]
It did happen originally after pressing a on the first option the mod loader on eshop, however after the most recent update it won’t allow me to even get past the initial loading before it aborts with the error message, because it’s trying to automatically load my mods

**Comment by BlueMario22** [comment]
Do you think going back to a older version then upgrading might solve the problem ? I really miss Smash Bros. at this point .

**Comment by Raytwo** [comment]
Well I have no clue what's happening with you so it's difficult to help you tbh. Maybe go back to ARCropolis 2.1.1 and hopefully something will get fixed at some point?
