### ISSUE TITLE
[Infinite loading][3.1.1]: Smash infinite loads before a match if modpack exceeds a certain size.

### ISSUE THREAD

**Issue by Angstdiscord** [Raytwo/ARCropolis#252]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.0.0

### Atmosphere Version

1.3.0

### Smash Version

13.0.1

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the infinite loading be consistently reproduced?

Yes

### In what situation does it happen?

- [ ] During the Smash ball loading on boot
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing
- [ ] Offline
- [ ] Online

### Context

Seemingly when a modpack exceeds 16-17GB smash will start infinite loading before a match. Swapping out different files doesn't seem to matter, it does seem to be tied to the overall size or file amount. I can cut off certain mods and enable others, but arc currently seems to have a limit to how much it will load. This is exacerbated by having more than 2 player smash. Say 3 player, 4 player etc seem to increase the odds of infinite loading.  Devory has had similar experiences.

### Minimal modpack to reproduce the infinite loading

I can upload my modpack privately to a google drive if needed. Since its seemingly a size issue

**Comment by VegaScratchSilver** [comment]
I've gotten this issue as well. Seems to manifest whenever I try to load new mods at an Ultimate Folder size(on disk) of 17 GB.

**Comment by Raytwo** [comment]
Fixed as of today! 🎉
