### ISSUE TITLE
[Crash] [ARCropolis 3.1.1]: Crash at Character select when 4+ modded skins are selected

### ISSUE THREAD

**Issue by Lagmobile** [Raytwo/ARCropolis#254]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.1.0

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [X] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

I am well aware this issue was reported before, and that it was recently closed, but there was no clarification or resolution as to why. I am reposting this because it is still an issue that's been long standing for me.

At character select up to 4 modded characters (model replacement or texture edit) can be selected without issue, but the moment a 5th player attempts to select a character the game freezes and crashes almost instantly.

The amount of modded characters that can be selected before crashing can vary with 4 being the most consistent (and the 5th player causing the crash) but can range between 3 and 5. I have tried multiple different combinations of characters and there seems to be no rhyme or reason as to why the range can vary but characters that are technically multiple characters (ie Pokemon Trainer, Pyra and Mythra) seem to make the limit lower.

### Crash report

[01648536348_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8368801/01648536348_01006a800016e000.log)

**Comment by Raytwo** [comment]
There there, sorry for closing your issue without reply, we're trying to clean up the section a bit because a lot of issues are user error related.

Your crash report indicated that there is a smashline related issue, so consider asking the authors about it or on the Discord server for more informations. I'll be closing this again since this isn't ARCropolis related, but if it turns out it is, feel free to use the Discussion page.

**Comment by Raytwo** [comment]
No problem, glad this is solved.
