### ISSUE TITLE
[Crash] [ARCropolis 3.1.1]: Software Aborting

### ISSUE THREAD

**Issue by 220240001** [Raytwo/ARCropolis#255]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.0

### Atmosphere Version

1.3.0

### Smash Version

13.0.1

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [X] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

When I start the game, a window appears saying that the Software is aborting(Error Code: 2--0069). Then about a minute later, It says the software was closed because an error occurred. Not that this is not my primary switch, I'm using Hecate 5.7.2, and it only happens on Smash, no other games.

### Configuration

N/A

### Crash report

[01648608677_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8376637/01648608677_01006a800016e000.log)

**Comment by Raytwo** [comment]
You're having an issue with the game trying to open a file, so it either comes from a music mod or you having a (broken?) data.arc in your romfs directory.
