### ISSUE TITLE
[Infinite loading][3.1.2]: infinite loading before fight start

### ISSUE THREAD

**Issue by Parkerboy92** [Raytwo/ARCropolis#256]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.0.0

### Atmosphere Version

13.0

### Smash Version

13. 0.1

### ARCropolis Version

3.1.2

### Version channel

Stable

### SD card formatting

FAT32

### Can the infinite loading be consistently reproduced?

Yes

### In what situation does it happen?

- [ ] During the Smash ball loading on boot
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing
- [ ] Offline
- [ ] Online

### Context

Just like the other guy, I'm getting infinite loading before a match. I have a 17GB modpack

**Comment by gucciboy512** [comment]
I am having the same issue, and have been since the early beta of 3.0.0
it seems to be caused by too many mods loading. my current mod pack works fine, but if I activate even one more skin, then I am met with infinite load screen at the loading screen. I hope the devs can fix this

**Comment by Raytwo** [comment]
As @gucciboy512 mentioned, it is most likely an issue with memory usage that we've been observing with users of very big modpacks.

We're currently investigating ways of using less memory, but please understand than 17GB of mods is massive to begin with and we can only do so much.

Please consider disabling a few mods until then.
