### ISSUE TITLE
Unicode characters in the path cause a crash

### ISSUE THREAD

**Issue by T6kyo** [Raytwo/ARCropolis#26]
i did everything that need to be done for arcropolis to give me the clear that its working then this pops up
![7C0DB7C3-F0A7-4234-BEE1-1B9DB01D4E3C](https://user-images.githubusercontent.com/73440716/97115493-64ca0500-16cd-11eb-9c2b-aef94cede91b.jpeg)
![8A39C53A-0B90-47D7-8A4A-3CA5C341F3E4](https://user-images.githubusercontent.com/73440716/97115496-65fb3200-16cd-11eb-877f-cab03b054066.jpeg)
get back to me through my discord T6kyo.#8600 if you have a response

**Comment by zzpixel** [comment]
make sure your plugin folder doesn't have an .nro file

**Comment by zzpixel** [comment]
make sure you have skyline installed

**Comment by Genwald** [comment]
I saw two people with this issue today, both cases were resolved by removing [this mod](https://gamebanana.com/skins/174448). I bet the issue here relates to the special characters in the `c07(Åj` folder name.

**Comment by Raytwo** [comment]
Hello,
I've been made aware of this issue by Genwald and will implement a fix in version 0.10.0 if possible.
Until then, please rename your directory if it contains weird characters.
