### ISSUE TITLE
[Incorrect behavior][3.1.1]: Switching to the 1st page after editing the 2nd one makes it forget your 2nd page toggle changes

### ISSUE THREAD

**Issue by kalomaze** [Raytwo/ARCropolis#260]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Expected behavior

Making a change to my 2nd mod page's enabled mods, then switching to another page to toggle mods there, and then switching back will wipe the changes you made on the previous page.
It should have remembered the changes I made when going back to the page. I am also not sure if this means that switching back to page 1 and saving the layout there would cause the 2nd page to reset or not, but it definitely resets the second you Switch back.

### Context

Attempting to disable HDR's nightly folders on the 2nd page (my stable HDR folders are on the 1st page) and then noticing the toggle changes I made were reset when I switched back to the page to double check I was turning off the right folders.

### Configuration

Not an ARCropolis error, I believe this is a gui programming oversight. I tried to find my config but all I found was a bunch of separate files and I'm not sure if any would be relevant. Just in case I uploaded it
[13569797346554227112.zip](https://github.com/Raytwo/ARCropolis/files/8405890/13569797346554227112.zip)

### Minimal modpack to observe the issue

At least 11 mods are required for the 2nd page to exist. Empty folders can be created to test this.

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 3.2.0
