### ISSUE TITLE
[Crash] [3.1.1]: Crashes at the versus screen 

### ISSUE THREAD

**Issue by cbisbocci** [Raytwo/ARCropolis#262]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.0.0

### Atmosphere Version

1.3.0

### Smash Version

13.0.0

### ARCropolis Version

3.1.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Whenever I select a character and a CPU to fight the game crashes on the loading screen. 

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x2A8 (2168-0001)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  00000000000000b2
    Process Flags:               00000077
    User Exception Address:      0000002377c11000
Exception Info:
    Type:                        Instruction Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   000000000000058a
    Thread Name:                 MainThread
    Stack Region:                0000004f59f32000-0000004f5a032000
    Registers:
        X[00]:                   00000012aff7b980
        X[01]:                   0000000000000000
        X[02]:                   0000004f5a02e410
        X[03]:                   00000075efeae7a0
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000001
        X[10]:                   0000000000000000
        X[11]:                   000000000000330a
        X[12]:                   500011050d040000
        X[13]:                   665f6c6f72746e6f
        X[14]:                   7645726574686769
        X[15]:                   0000000000000000
        X[16]:                   00000075efeaf628
        X[17]:                   00000004a9650534 ([00000000] + 0x534)
        X[18]:                   000000129987dc38
        X[19]:                   00000012aff7b980
        X[20]:                   0000004f5a02e550
        X[21]:                   00000004a965ca00
        X[22]:                   0000000000000008
        X[23]:                   00000012821f0118
        X[24]:                   000000128b1f8990
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   00000012f8e43718
        X[28]:                   0000000050000000
        FP:                      0000004f5a02e590
        LR:                      00000004a96505b4 ([00000000] + 0x5b4)
        SP:                      0000004f5a02e440
        PC:                      0000000000000000
    Stack Trace:
        ReturnAddress[00]:       00000054f5930c58 (cross2_Release.nss + 0x372cc58)
        ReturnAddress[01]:       00000054f268f95c (cross2_Release.nss + 0x48b95c)
        ReturnAddress[02]:       00000054f25ac270 (cross2_Release.nss + 0x3a8270)
        ReturnAddress[03]:       00000054f2819b38 (cross2_Release.nss + 0x615b38)
        ReturnAddress[04]:       00000054f25b0b08 (cross2_Release.nss + 0x3acb08)
        ReturnAddress[05]:       00000054f357f588 (cross2_Release.nss + 0x137b588)
        ReturnAddress[06]:       00000054f3560bfc (cross2_Release.nss + 0x135cbfc)
        ReturnAddress[07]:       00000054f356374c (cross2_Release.nss + 0x135f74c)
        ReturnAddress[08]:       00000054f3a54484 (cross2_Release.nss + 0x1850484)
        ReturnAddress[09]:       00000054f3a54378 (cross2_Release.nss + 0x1850378)
        ReturnAddress[10]:       00000054f5927d14 (cross2_Release.nss + 0x3723d14)
        ReturnAddress[11]:       00000054f44e2570 (cross2_Release.nss + 0x22de570)
        ReturnAddress[12]:       00000054f5927d14 (cross2_Release.nss + 0x3723d14)
        ReturnAddress[13]:       00000054f44e2570 (cross2_Release.nss + 0x22de570)
        ReturnAddress[14]:       00000054f5927d14 (cross2_Release.nss + 0x3723d14)
        ReturnAddress[15]:       00000054f594f5a8 (cross2_Release.nss + 0x374b5a8)
        ReturnAddress[16]:       00000054f24c9cf0 (cross2_Release.nss + 0x2c5cf0)
        ReturnAddress[17]:       00000054fa022a2c (nnSdk + 0x29da2c) (_ZN2nn4init5StartEmmPFvvES2_ + 0x4c)
        ReturnAddress[18]:       00000054f22000c0 (nnrtld + 0xc0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 004f5a02e440 a0 02 eb ef 75 00 00 00 c0 03 eb ef 75 00 00 00
                                 004f5a02e450 a8 02 eb ef 75 00 00 00 50 e5 02 5a 4f 00 00 00
                                 004f5a02e460 80 b9 f7 af 12 00 00 00 dc dc e9 ef 75 00 00 00
                                 004f5a02e470 35 9d ca 14 14 00 00 00 60 fb dd b0 0a 00 00 00
                                 004f5a02e480 04 00 00 00 00 00 00 00 60 fb dd b0 0a 00 00 00
                                 004f5a02e490 41 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 004f5a02e4a0 04 00 00 00 13 00 00 00 60 fb dd b0 0a 00 00 00
                                 004f5a02e4b0 10 e5 02 5a 00 00 00 00 c8 01 28 80 12 00 00 00
                                 004f5a02e4c0 a0 02 eb ef 75 00 00 00 58 0b 3a b1 0a 00 00 00
                                 004f5a02e4d0 80 ef 9a 05 13 00 00 00 04 00 00 00 00 00 00 00
                                 004f5a02e4e0 60 fb dd b0 0a 00 00 00 41 00 00 00 00 00 00 00
                                 004f5a02e4f0 00 00 00 50 00 00 00 00 18 37 e4 f8 12 00 00 00
                                 004f5a02e500 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 004f5a02e510 90 89 1f 8b 12 00 00 00 00 d0 b3 f7 54 00 00 00
                                 004f5a02e520 60 76 7e f2 12 00 00 00 80 b9 f7 af 12 00 00 00
                                 004f5a02e530 c8 e6 02 5a 4f 00 00 00 80 b9 f7 af 12 00 00 00
    TLS Address:                 0000002377c11200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002377c11200 00 00 00 00 0d 00 00 00 00 00 00 00 00 00 00 00
                                 002377c11210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c11220 53 46 43 4f 00 00 00 00 00 00 00 00 6f eb 49 79
                                 002377c11230 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c11240 53 46 43 49 01 00 00 00 0b 00 00 00 00 00 00 00
                                 002377c11250 03 00 54 01 1b 48 18 c0 4f 00 10 00 00 00 00 00
                                 002377c11260 00 00 00 00 18 00 00 00 f0 eb 02 5a 4f 00 18 00
                                 002377c11270 00 00 00 00 00 00 00 00 03 0d 08 00 00 04 0a 00
                                 002377c11280 08 04 0a 00 04 02 14 00 00 00 00 00 00 00 00 00
                                 002377c11290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002377c112f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by Raytwo** [comment]
Crash comes from some code dealing with lua code (.lc files and moveset editing plugins). Sounds familiar?

**Comment by cbisbocci** [comment]
Okay cleaning out my plugins and troubleshooting now. What do you mean by
"Ic files"?

**Comment by Raytwo** [comment]
.lc files are files containing lua that mostly control the menus. You’d have absolutely no reason to mod that but saying just in case

**Comment by cbisbocci** [comment]
Thanks for that. I cleaned everything and it worked. I think it was my
smashline plugin that was crashing my game.

**Comment by Raytwo** [comment]
No problem! Closing this then.
