### ISSUE TITLE
[Crash] [ARCropolis 3.0.0]: Game crashing when choosing certain characters

### ISSUE THREAD

**Issue by Kiura0** [Raytwo/ARCropolis#268]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.1.0

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.0.0 (and later)

### Version channel

Stable

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

After merging from 2.1.1 to 3.0.0, i tested every mods to see if some of them doesn't work anymore and so remove them. I tested mods for each characters un the order on the select screen, everything was alright, everymod worked fine, as well for stage mods, until I tried Daisy and Bowser's mods. The game freeze for a while and then close after some like 5-10 seconds. I just though the mods was the issue, but after more crashes on the next Bowser's mods, I tried to play as just regular Bowser without any mods loaded, any mods in the match at all, and the game still freeze at the loading battle screen and close after a while. The problem is, it crash with the usual message "Software close because it encounter a problem" (or something like that, don't know the exact quote since my Switch is on French), but it just the regular message of the Switch that you can have without hacking it, for exemple glitching your game too much. So I have no report message at all, no details on what actually happen, I just can't play with Bowser or Daisy at all (I tried characters further on the character order, since Daisy and Bowser are side by side, but Ridley and Cloud just work fine, tho I didn't try every single characters). It happened on the 3.0.0 pre-released; 3.0.0 official release, 3.1.0 and today 3.1.2, and still have the same issues. I go back to 2.1.1 each time to still be able to play with mods, and everything just work perfectly fine.

(Note: I only put the 107 first line in crash report as it suggest that 100 is suffisante, the chrash report is actually +2000 lines)

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000083
    Process Flags:               00000077
    User Exception Address:      0000000561f9c000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000284
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000000000090401
        X[02]:                   000000000009f9ea
        X[03]:                   0000000000000008
        X[04]:                   0000004aee145260 (cross2_Release.nss + 0x3541260)
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   000000284828fbe0
        X[08]:                   0000002840478498
        X[09]:                   0000000000018010
        X[10]:                   0000000000000018
        X[11]:                   0000000000000000
        X[12]:                   0000000000018008
        X[13]:                   0000000000ffffff
        X[14]:                   00000025f02ae133
        X[15]:                   ffffffffffffffff
        X[16]:                   0000004af33b8ee8
        X[17]:                   0000004af2abf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   0000004af3225c38
        X[19]:                   0000000000090401
        X[20]:                   000000000000030f
        X[21]:                   0000002840478000
        X[22]:                   0000004aeff34000
        X[23]:                   0000002840490530
        X[24]:                   0000000000000007
        X[25]:                   0000002840491498
        X[26]:                   000000000000030f
        X[27]:                   0000004aeff34000
        X[28]:                   00000028404913b8
        FP:                      000000284828fc50
        LR:                      0000004aee163810 (cross2_Release.nss + 0x355f810)
        SP:                      000000284828f930
        PC:                      0000004aee1639e0 (cross2_Release.nss + 0x355f9e0)
    Stack Trace:
        ReturnAddress[00]:       0000004aeb20ffbc (cross2_Release.nss + 0x60bfbc)
        ReturnAddress[01]:       0000004aeafb25b0 (cross2_Release.nss + 0x3ae5b0)
        ReturnAddress[02]:       0000004aeb25cb2c (cross2_Release.nss + 0x658b2c)
        ReturnAddress[03]:       0000004aec0e2350 (cross2_Release.nss + 0x14de350)
        ReturnAddress[04]:       0000004aebf61d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[05]:       0000004aee14d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[06]:       0000004aee140538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[07]:       0000004aee3cf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[08]:       0000004af2abcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 0000000f66f28a00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000f66f28a00 00 00 01 00 09 00 00 00 80 80 28 00 38 e8 28 48
                                 000f66f28a10 53 46 43 4f 00 00 00 00 00 00 00 00 99 5d e2 a4
                                 000f66f28a20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28a30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 000f66f28a40 01 00 81 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 000f66f28a50 28 00 81 01 38 e8 28 48 28 00 28 00 00 00 00 00
                                 000f66f28a60 00 00 00 00 18 00 00 00 10 fc 28 48 28 00 18 00
                                 000f66f28a70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28a80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28a90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28aa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28ab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28ac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28ad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28ae0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000f66f28af0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 0000004aeabdc000-0000004aeac00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000004aeac00000-0000004aeac02000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000004aeac04000-0000004aee5cb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 0000004af204a000-0000004af23b7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 0000004af275f000-0000004af2778000
        Name:                    Skyline
        Module Id:               B44280982D6BBFA90259E041B53C1889D3F10328000000000000000000000000
    Module 05:
        Address:                 0000004af2785000-0000004af2cc6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:
        Address:                 00000005e7190000-00000005e72ba000
        Name:                    arcropolis
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000

**Comment by Raytwo** [comment]
Hey there, closing this as this is clearly user mistake, but the issue comes from one of your .eff files.

**Comment by Kiura0** [comment]
Hello there, god dammit that was back at my first modding day when I though that you can simply rename .eff files to apply them to only certain slot, and I just forget it since it doesn't work but doesn't bothering the game since now... So sorry for the inconvenience, and thank so so much for saying me what was wrong, for your really quick answer, and of course for all your work for the modding comunity!

**Comment by Raytwo** [comment]
Haha, it's all good, appreciate it! Have fun.
