### ISSUE TITLE
[Crash] [ARCropolis version 3.1.2]: Crashes on boot.

### ISSUE THREAD

**Issue by DShip91** [Raytwo/ARCropolis#270]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.1.0

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.1.2

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Attempting to boot Ultimate on ARCropolis 3.1.2 crashes the game on boot no matter what I do.

### Configuration

Region: English (US)
Logging level: Warning
Beta updates: On
Legacy mod discovery: On
Debug: Off
Log to file: Off
Check for update on boot: On

### Crash report

[01649625128_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8459940/01649625128_01006a800016e000.log)

### Minimal modpack to reproduce the crash

Unknown

**Comment by Raytwo** [comment]
Can't be crashing more than 3.1.1 considering the only change is adding a check on the button so the issue is local. Maybe redownload it fresh and install manually, and learn to show some respect.

**Comment by DShip91** [comment]
I'm sorry about the original title. It wasn't my intent to offend. I just can't understand why 3.1.1 can bot yet 3.1.2 can't. And if that really is the only change then that only leaves me more confused.

Sorry.

**Comment by Raytwo** [comment]
Your crash report mentions a crash when closing a web browser page, which you did not specify in any way in your issue.
If you don't provide every detail, there is no way for us to track down the issue. If this actually happened, what was the message?

**Comment by DShip91** [comment]
I took your advice and re-installed the update fresh but it's still not working. I even deleted the config.toml file so that it would bypass the changelog (which I thought was the problem) and go straight to the game but it still crashes on boot. The only message it gives me is "The software has closed because an error occurred" which is why I uploaded the crash log along with the issue.

**Comment by Raytwo** [comment]
I just reinstalled ARCropolis fresh from 3.1.1 then updated to 3.1.2 while using the exact same configuration you specified as well as a massive amount of mods, and everything went through.

Considering the only issue it brings up is from the web browser being closed, I'd recommend to perhaps delete sd:/atmosphere/contents/01006A800016E000/manual_html/ to clean up some old web files.

If this still doesn't work well, here is my exact [Atmosphere + Hekate combo](https://www.sdsetup.com/console?switch#atmosphere;atmos_musthave;hekate_musthave;kosmos_toolkit;atmos_sysftpd;hbmenu;hekate;tegrarcmgui;) that work for me in case you want to try this.

**Comment by DShip91** [comment]
Unfortunately, none of those suggestions work for me. The only thing I can do for now is downgrade back to 3.1.1 and hope that the next update works for me.

Thanks for trying, though. Also wanted to apologize again for my unintentional rudeness when first posting the issue. I didn't mean to come across like that but I do understand now how it could be seen that way. Sorry about that.
