### ISSUE TITLE
[Crash] [Arcropolis and Training Mod]

### ISSUE THREAD

**Issue by JokeEmperor** [Raytwo/ARCropolis#278]
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

14.1.0

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.1.2

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Context

Game crashes after switch logo disappears. Trying to use skin mods and training mode beta mod. 

### Crash report

[01649676320_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8463631/01649676320_01006a800016e000.log)

### Minimal modpack to reproduce the crash

https://github.com/jugeeya/UltimateTrainingModpack/releases/tag/beta

**Comment by Raytwo** [comment]
ARCropolis is having an issue when trying to write a file to your SD, so make sure your SD doesn't have corrupted sectors.
If it persists, consider disabling some mods until you can isolate which one is problematic.

**Comment by JokeEmperor** [comment]
It works with skins when using HDR, but when i disable it using Ultimate Plugin Toggler, it stops working. Arcropolis all together
