### ISSUE TITLE
Language specific MSBTs loaded based on console language, not game language

### ISSUE THREAD

**Issue by soneek** [Raytwo/ARCropolis#30]
I normally have my console's language as English, but I changed the in-game language to Japanese. ARCropolis still loaded msg_bgm+us_en.msbt for me. 

When changing my console language to Japanese, ARCropolis loaded msg_bgm+ja_jp.msbt for me, for both English and Japanese as the in-game language. 

Is there a way to have the MSBT language reflect the in-game setting, rather than the console setting?

**Comment by Raytwo** [comment]
Resolved as of ARCropolis v1.0.1
