### ISSUE TITLE
[Qualify of Life] Enable/Disable Skyline Plugins from within the Mod Manager

### ISSUE THREAD

**Issue by ColdPizza2002** [Raytwo/ARCropolis#304]
I don't like having to disable or enable plugins manually through remotely editing the contents of my SD card each time. It would be neat, if possible, if you could toggle plugins just like any other mod from within the mod manager menu.

**Comment by jozz024** [comment]
this is not the job of arcropolis, use https://github.com/jozz024/arcadia/releases/tag/v1.0

**Comment by Raytwo** [comment]
1. There is chainloading if your plugin is not ``nro_hooks``, ``smashline`` or ``acmd_hook`` that lets you toggle your plugins as if they were a mod (rename them as plugin.nro and put them in a mod)
2. If the plugin is one of those I just listed, refer to what @jozz024 said
3. [Thanks for reading the disclaimer but issues are for developers](https://github.com/Raytwo/ARCropolis/issues/288)
