### ISSUE TITLE
Game crashes at the beginning of the match 

### ISSUE THREAD

**Issue by glazedonut** [Raytwo/ARCropolis#31]
Game crashes at the beginning of the match, after the versus screen, right before the countdown. This has happened 5 times in the last 3 days. It’s not something that always happens though. But it happens frequently enough I believe it might be an Arcropolis issue.

**Comment by Raytwo** [comment]
Please pay attention to every detail that could give you a clue on why this happens, such as:
- Which characters were being loaded
- What skin were they using
- What stage where you using (if it was modded)
- What mode for said stage (Normal, Battlefield, FD)
- Did you load custom music?
- Did you have modded voices?
...

And try to isolate which mod exactly could cause a crash.

**Comment by JteMonteEnDerby** [comment]
I have the same problem everything was working but now i just can't play a match

**Comment by 1337haXXor** [comment]
I'm in the same boat. Just updated Acropolis and Smash, installed 5 or 6 more costumes and now can't start anything. Tested a half dozen times with modded costumes, levels, and using vanilla characters on vanilla maps, all crash. Additionally, World of Light is crashing.

**Comment by JteMonteEnDerby** [comment]
Yeah the maj is broken

**Comment by SevenThomsen** [comment]
Anyone have a fix for this yet? Still experiencing the issue and I can't find much information on it.

**Comment by Raytwo** [comment]
> 
> 
> I'm in the same boat. Just updated Acropolis and Smash, installed 5 or 6 more costumes and now can't start anything. Tested a half dozen times with modded costumes, levels, and using vanilla characters on vanilla maps, all crash. Additionally, World of Light is crashing.
> 
> EDIT: Okay, so I went through and disabled all the NEW few mods I'd installed in this batch and it still happened. Then I went through and disabled ALL mods in their entirety. Now when running through Arcadia, it crashes with a Skyline crash log error. 2--0069, error 514". Something about an error replacing something, I can post the screenshot if needed. When running the game from the main Switch menu, it crashes before the match starts.

This sounds more like you have a mod with a weird character in the filepath? Another issue happened to have the same error and it was tracked back to that.

Anyway, no, still no progress on that simply because what you guys are reporting is just... weird? The latest update did nothing but the bare minimum to run on Smash 9.0.2, which shouldn't break. I keep the issue in mind though, just absolutely no clue why this is happening for the time being.

**Comment by Raytwo** [comment]
Oh and by the way, if you could be clearer on *when* a crash occurs (boot, CSS, before/during/after a loading, on result screen, on CSS after a match), that'd help, thanks.

**Comment by 1337haXXor** [comment]
I'll check the file names in a bit. I mentioned it crashes before the match starts, but more specifically on the actual match loading screen. The loading icon will spin a couple times, then it throws the error. One time, it just kept loading eternally.

**Comment by JteMonteEnDerby** [comment]
me it work again and i don't know why the only thing i do is install the support for skin minecraft for 9.0.2

**Comment by JteMonteEnDerby** [comment]
and after that it worked again u:

**Comment by glazedonut** [comment]
> Please pay attention to every detail that could give you a clue on why this happens, such as:
> 
> * Which characters were being loaded
> * What skin were they using
> * What stage where you using (if it was modded)
> * What mode for said stage (Normal, Battlefield, FD)
> * Did you load custom music?
> * Did you have modded voices?
>   ...
> 
> And try to isolate which mod exactly could cause a crash.

Very sorry for the late reply, aside from school stuff, I’ve been trying to find as many cases as possible where the game crashes at the beginning and that doesn’t happen often (like once or twice a day). Couple of times the game would crash after the vs screen before the countdown when there are no skins used. There were times we used the games default alts and the game still crashed.
Though, today. I was able to do reproduce the crash successfully

**Comment by glazedonut** [comment]
> Please pay attention to every detail that could give you a clue on why this happens, such as:
> 
> * Which characters were being loaded
> * What skin were they using
> * What stage where you using (if it was modded)
> * What mode for said stage (Normal, Battlefield, FD)
> * Did you load custom music?
> * Did you have modded voices?
>   ...
> 
> And try to isolate which mod exactly could cause a crash.

Very sorry for the late reply, aside from school stuff, I’ve been trying to find as many cases as possible where the game crashes at the beginning and that doesn’t happen often (like once or twice a day). Couple of times the game would crash after the vs screen before the countdown when there are no skins used. There were times we used the games default alts and the game still crashed.
Though, today. I was able to do reproduce the crash successfully with the black and gold falcon skin matched up with the ash Greninja skin. Although doesn’t crash every time with these 2 characters against each other, it did crash twice in a row both times there characters were pitched against each other. Aside from that, the shiny Greninja skin also caused the game to crash right after the versus screen. I turned off the mod on Arcadia and it did lessen the crashes. 
But other than that. Possible factors include the game possibly crashing on nus3audio files of the announcer at the beginning of the match, combined with certain skins crashing the game at startup.

**Comment by glazedonut** [comment]
> > Please pay attention to every detail that could give you a clue on why this happens, such as:
> > 
> > * Which characters were being loaded
> > * What skin were they using
> > * What stage where you using (if it was modded)
> > * What mode for said stage (Normal, Battlefield, FD)
> > * Did you load custom music?
> > * Did you have modded voices?
> >   ...
> > 
> > And try to isolate which mod exactly could cause a crash.
> 
> Very sorry for the late reply, aside from school stuff, I’ve been trying to find as many cases as possible where the game crashes at the beginning and that doesn’t happen often (like once or twice a day). Couple of times the game would crash after the vs screen before the countdown when there are no skins used. There were times we used the games default alts and the game still crashed.
> Though, today. I was able to do reproduce the crash successfully with the black and gold falcon skin matched up with the ash Greninja skin. Although doesn’t crash every time with these 2 characters against each other, it did crash twice in a row both times there characters were pitched against each other. Aside from that, the shiny Greninja skin also caused the game to crash right after the versus screen. I turned off the mod on Arcadia and it did lessen the crashes.
> But other than that. Possible factors include the game possibly crashing on nus3audio files of the announcer at the beginning of the match, combined with certain skins crashing the game at startup.

Btw startup I meant the game will crash right after it goes into the versus loading screen. The way it crashes is that when the game renders the stage, the tip will be still visible but the entire stage is visible. When this happens. The game dims, freezes and crashes right before the countdown announcer says “3!”

**Comment by glazedonut** [comment]
> > I'm in the same boat. Just updated Acropolis and Smash, installed 5 or 6 more costumes and now can't start anything. Tested a half dozen times with modded costumes, levels, and using vanilla characters on vanilla maps, all crash. Additionally, World of Light is crashing.
> > EDIT: Okay, so I went through and disabled all the NEW few mods I'd installed in this batch and it still happened. Then I went through and disabled ALL mods in their entirety. Now when running through Arcadia, it crashes with a Skyline crash log error. 2--0069, error 514". Something about an error replacing something, I can post the screenshot if needed. When running the game from the main Switch menu, it crashes before the match starts.
> 
> This sounds more like you have a mod with a weird character in the filepath? Another issue happened to have the same error and it was tracked back to that.
> 
> Anyway, no, still no progress on that simply because what you guys are reporting is just... weird? The latest update did nothing but the bare minimum to run on Smash 9.0.2, which shouldn't break. I keep the issue in mind though, just absolutely no clue why this is happening for the time being.

Btw 9.0.2 has nothing to do with this.
For some reason the 9.0.2 update is actually slightly more stable. The crashes were so bad in 9.0.1 it crashed almost every 30 mins.
This time, it crashes every few hours.

**Comment by 1337haXXor** [comment]
@JteMonteEnDerby Which mod are you talking about? I couldn't find one like that on gamebanana. But I don't even have any Minecraft skins installed...

And what I don't understand is I can't play the game at all, even without any mods. With all of them disabled, the game still crashes at the vs. screen. Is the game still loading code/mods, but just not utilizing them? I guess what I'm asking is what is the easiest way to run the full vanilla game? Do I have to rename the mods folder or something?

**Comment by Raytwo** [comment]
@1337haXXor They were talking about [smash-minecraft-skins](https://github.com/jam1garner/smash-minecraft-skins), which was not compatible with 9.0.2 right away.

If you have absolutely no mods running (be it in /ultimate/mods/ or in romfs/arc/), I really don't get why you'd have any issue related to ARCropolis itself. Mods do run even if there are no files but ARCropolis is made in a way that nothing would happen if there are no file to load. Especially not this far at runtime.

If you happen to be running other code mods, I'd suggest removing them one at a time to confirm if it doesn't come from there instead, as some other mods might also need support for 9.0.2.

If you want to run the game vanilla, you can either keep R pressed while booting Smash or remove files in the /romfs/skyline/plugins directory.

**Comment by 1337haXXor** [comment]
Okay, I stumbled across a comment, I think on gamebanana, that solved it. I deleted my data.arc file. It was fine, because I wasn't currently using any UMM mods, and the few that I have that aren't compatible with Arcropolis I'm in no hurry to use. All in all, saved 15GB off SD card anyway.

Thanks for all your work, by the way!
