### ISSUE TITLE
[Incorrect behavior] All of the "guidance" taunts (Palutena/MGS/StarFox) are silent or in japanese

### ISSUE THREAD

**Issue by Raytwo** [Raytwo/ARCropolis#312]
### System Firmware Version

14.0.0 or smth

### Atmosphere Version

13.0.0 or smth

### Smash Version

13.0.0.1

### ARCropolis Version

3.3.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### Expected behavior

The taunts should obviously work in the correct language but don't.
Some like Starfox's are in japanese, some are silent.

Can be observed by running a Codec on Lucario.

**Comment by Raytwo** [comment]
Might just want to prevent unsharing these and see how it goes? Probably a case of hardcoded slot that gets unshared automatically.

**Comment by TripleLJ** [comment]
Preventing unsharing doesn't seem to work per CSK. I personally wouldn't mind a brute force fix since no one is modding the smash taunts anytime soon.

**Comment by TripleLJ** [comment]
Thank you!!! Works fine from what I tested.
