### ISSUE TITLE
[Crash] Arcrop crash during startup on ryujinx due to ninput operations

### ISSUE THREAD

**Issue by techyCoder81** [Raytwo/ARCropolis#314]
### System Firmware Version

N/A

### Atmosphere Version

N/A

### Smash Version

latest

### ARCropolis Version

latest

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [X] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [x] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

According to reports, latest arcrop now crashes on ryujinx while trying to use ninput to check for +/- inputs to open the mod manager on smash boot. While this is not directly arcropolis' responsibility, exactly, if the button check/ninput init could be guarded by a ryujinx check, that should resolve this issue.

Best point of contact for this issue is @O1yyy on discord.

### Crash report

I don't have one as I have not personally reproduced this, but shadow looked at it with Olyyy and he determined that its ninput that is crashing during smash startup.

**Comment by mrTerryBogard** [comment]
Good day!

ARCropolis stable or pre-release latest version and Ryujinx latest version.
Ryujinx freezes when trying to exit the game. At the same time, it is possible to close the SPM emulator only when closing the console.
