### ISSUE TITLE
[Incorrect behavior] Agreeing to enable newly found mods does not properly work

### ISSUE THREAD

**Issue by Raytwo** [Raytwo/ARCropolis#320]
### System Firmware Version

lol

### Atmosphere Version

lmao

### Smash Version

13.0.1

### ARCropolis Version

3.3.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

When prompted about new mods being found and asking if they should be enabled, saying yes does not work properly, as it does not take workspaces into account.

**Comment by pleasehelpmeeeee** [comment]
does anyone know why my game keeps on saying check for courrupted files every time i try to start the game after im done with all the moding i need to keep on redownloading the game when that happens
