### ISSUE TITLE
software abort/check for corrupted files when i launch super smash ultimate

### ISSUE THREAD

**Issue by pleasehelpmeeeee** [Raytwo/ARCropolis#321]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.3.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [X] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

First i download the latest version Arcropolis and the extract the files then move them to my sd card and then i download skyline than extract it to my smash bros content id after that i open my ultimate folder next to acropolis i make a mods folder than i open that than look for mods than after that i put the smash mods in the mods folder after that i boot up my modded switch with fussee latest version after that i launch smash bros it software abort after that it says check for corrupted files <>MOVE ON TO CRASH REPORT<>

### Crash report

every time i try to start the game after im done with all the moding i need to keep on redownloading the game when that happens

**Comment by pleasehelpmeeeee** [comment]
sorry this is the best i can explain it right now

**Comment by Raytwo** [comment]
[Please use Discussions instead of opening issues](https://github.com/Raytwo/ARCropolis/issues/288)
