### ISSUE TITLE
[Crash] error code 2--0069 "The software is aborting."

### ISSUE THREAD

**Issue by Monjgurt** [Raytwo/ARCropolis#324]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.3.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

upon starting the game, the changelog (i think) appears, once its closed shortly after the error pops up, and forces you to check the game for errors, it then finds errors and wants you to redownload the game, doing so wont change anything, same error pops up
i also tried uninstalling every single mod acrive, so only ARCropolis and skyline are installed

### Crash report

-

**Comment by DuIslingr** [comment]
@Raytwo Why was this closed? I have this exact issue on HOS 14.1.2, Atmosphere 1.3.2. Arcropolis 3.7.2 Smash 13.0.1 and the Skyline beta from March 5 2022 This occurs with or without mods in the ultimate/mods directory. Holding L allows the game to boot just fine. 
[01664635593_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/9690599/01664635593_01006a800016e000.log)
![IMG_0718](https://user-images.githubusercontent.com/19367043/193416230-43e4f0c8-7830-4c7e-8b55-5047feb2c33c.jpg)
