### ISSUE TITLE
reflection_cubemap.nutexb files not loaded in-game with ARCropolis

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Raytwo/ARCropolis#33]
Using either a vanilla or custom `reflection_cubemap.nutexb` file in place of an existing one will not take effect in-game and will instead load the vanilla file. Checking the logs, ARCropolis acknowledges the file and patches its size at runtime and appears to load it in, but it does not actually load in-game.

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 10.0.0-beta
