### ISSUE TITLE
[Crash] Arc 3.0 and after Character crashes

### ISSUE THREAD

**Issue by JarlTheKing** [Raytwo/ARCropolis#334]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.3.0

### Version channel

Stable

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

Ever since updating to Arc 3.0 (and after) whenever I choose certain characters with skins (or other mods on them) the game crashes on the loading screen to a match. So instead I have to update back to Arc 2.1.1 in order for everything to work properly again. I'm still new in working around mods, and I would like to add all the cool mods that only really work with the new Arc updates.

### Crash report

[01651764735_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8633072/01651764735_01006a800016e000.log)

![01651764735_01006a800016e000](https://user-images.githubusercontent.com/102709826/166971119-1f988b64-9189-452e-9945-22538e316024.jpg)

**Comment by Raytwo** [comment]
> @Raytwo Any help?

[Use discussions?](https://github.com/Raytwo/ARCropolis/issues/288)
