### ISSUE TITLE
Game crashes on load (different error)

### ISSUE THREAD

**Issue by sorasin** [Raytwo/ARCropolis#34]
Hi,

Ultimate is crashing on loading unless I disable all Skyline plugins. I have tried updating to no avail. Here is the error:

`Thread '<unnamed>' panicked at 'Invalid last url for dialog', C:\Users\Raytwo\.cargo\git\checkouts\skyline-web-b2552367e4749066\bd44c9b\src\dialog.rs:58:18`

thank you

**Comment by Raytwo** [comment]
Looks like this is related to the web browser used to display windows.
Issues related to that belong to the [skyline-web](https://github.com/skyline-rs/skyline-web) repository.
