### ISSUE TITLE
Game crashes at start

### ISSUE THREAD

**Issue by EvilProHack** [Raytwo/ARCropolis#35]
I tried to switch from UltimateModManager to ARCropolis when Steve's patch came out. I started with the character selection screen errors that I have seen here. I have tried using the program in sx os and Atmosphere 14 and Atmosphere 15 without any results.
Currently the game (after tryed to solve the bug myself)does not even load the main screen (I have reinstalled it 7 times and  ARCropolis  4 times) and it does not generate the ARCropolis configuration
The closest thing to an error report that has come out would be with sx os ERROR CODE 2-0069 and ERROR "0X7D802" with Atmosphere I didn't get anything but the classic the game has closed.

**Comment by EvilProHack** [comment]
Update solved the error code but continuing crashing at the start with no reason

**Comment by Raytwo** [comment]
I'm aware of a bug related to the configuration file but have no one to test a fix.
Mind trying [this build](https://cdn.discordapp.com/attachments/447940880922574848/776827108621025280/release.zip) and letting me know if the game boots properly?

**Comment by EvilProHack** [comment]
Still not working 
if I boot up Arcadia says that I do not have the configuration file.
So ARCropolis doesn't even create the file
I'm starting to think it's atmosphere's fault but I have the latest version   so it shouldn't give me any problems right?

**Comment by Raytwo** [comment]
Well after checking your error code (nn::fs::ResultNcaExternalKeyUnavailable), that sounds more like an issue with your own setup than ARCropolis at this point. Sorry but I can't really help more than that, maybe ask in the Ultimate Modding Server for some assistance in setting up your environment again?
