### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by Blazingflare** [Raytwo/ARCropolis#352]
### System Firmware Version

14.1.0

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.4.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

When the vl.prc param files for Pokemon trainer are replaced at all, the game will consistently crash right before the match starts in any spirit battles against a solo Pokemon. 
It might only be one of the specific files, but if you replace
fighter/pfushigisou/param/vl.prc
fighter/plizardon/param/vl.prc
fighter/ptrainer/param/vl.prc
fighter/ptrainer_low/param/vl.prc
fighter/pzenigame/param/vl.prc
with even just the vanilla files, the game will always crash on the match loading screen

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0xCA8 (2168-0006)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000094
    Process Flags:               00000077
    User Exception Address:      00000031eae0b000
Exception Info:
    Type:                        User Break
    Address:                     000000496550e998 (nnSdk + 0x389998)
    Break Reason:                0x0
    Break Address:               0000000000000000
    Break Size:                  0x0
Crashed Thread Info:
    Thread ID:                   00000000000006f2
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000000000000000
        X[02]:                   0000000000000000
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000037cb896ca0
        LR:                      00000049654b8180 (nnSdk + 0x333180) (nnosBreak + 0x10)
        SP:                      00000037cb896c90
        PC:                      000000496550e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       000000496569ec10 (nnSdk + 0x519c10) (__nnmusl_GetTlsValue + 0x0)
        ReturnAddress[01]:       0000000008001218 ([00000000] + 0x1218)
        ReturnAddress[02]:       0000003406f35090 (smashline_hook + 0x26090) (abort_hook + 0x40)
        ReturnAddress[03]:       000000496564c380 (nnSdk + 0x4c7380)
        ReturnAddress[04]:       000000496564efb0 (nnSdk + 0x4c9fb0) (__cxa_get_exception_ptr + 0x0)
        ReturnAddress[05]:       000000496564ef1c (nnSdk + 0x4c9f1c)
        ReturnAddress[06]:       0000004965636ab4 (nnSdk + 0x4b1ab4) (_ZNKSt3__120__vector_base_commonILb1EE20__throw_out_of_rangeEv + 0x4c)
        ReturnAddress[07]:       000000495e5c74a8 (cross2_Release.nss + 0xfc34a8)
        ReturnAddress[08]:       00000049609be168 (cross2_Release.nss + 0x33ba168)
        ReturnAddress[09]:       00000049609be3d8 (cross2_Release.nss + 0x33ba3d8)
        ReturnAddress[10]:       00000049609b9f38 (cross2_Release.nss + 0x33b5f38)
        ReturnAddress[11]:       000000495d9ab5fc (cross2_Release.nss + 0x3a75fc)
        ReturnAddress[12]:       00000049609a1e40 (cross2_Release.nss + 0x339de40)
        ReturnAddress[13]:       000000495d9aa5cc (cross2_Release.nss + 0x3a65cc)
        ReturnAddress[14]:       000000495d9aa3b0 (cross2_Release.nss + 0x3a63b0)
        ReturnAddress[15]:       000000495dc5cd9c (cross2_Release.nss + 0x658d9c)
        ReturnAddress[16]:       000000495eae2350 (cross2_Release.nss + 0x14de350)
        ReturnAddress[17]:       000000495e961d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[18]:       0000004960b4d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[19]:       0000004960b40538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[20]:       0000004960dcf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[21]:       00000049654bcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 0000002dcf856e00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002dcf856e00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856e10 53 46 43 4f 00 00 00 00 00 00 00 00 d2 da 81 3e
                                 002dcf856e20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856e30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 002dcf856e40 01 00 7d 01 06 41 28 c0 01 00 00 00 90 9d ff ff
                                 002dcf856e50 28 00 00 00 28 6e 89 cb 37 00 28 00 00 00 00 00
                                 002dcf856e60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856e70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856e80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856e90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856ea0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856eb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856ec0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856ed0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856ee0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcf856ef0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           9
    Module 00:
        Address:                 000000495d5dc000-000000495d600000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01
[01653803674_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8792761/01653803674_01006a800016e000.log)
:

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
