### ISSUE TITLE
[Incorrect behavior] Brief description of the issue

### ISSUE THREAD

**Issue by BigBoss320** [Raytwo/ARCropolis#357]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.4.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### Expected behavior

Something is weird with the Mod manager (Arcadia-rs). when we put the info.toml file in the mod with "UI" category, it appears blue in the list but when filtering with "UI" it desappear.
See followed pics :
![image](https://user-images.githubusercontent.com/44122706/172577463-d73889cb-f232-4f93-8fd4-c69fd8dafd0c.png)
![2022060810575300-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/44122706/172578743-7581854c-8cee-405b-92ac-36dece54fa9d.jpg)
![2022060810575900-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/44122706/172579311-fc5b95be-f48a-4f89-b453-1d9a2611e0bd.jpg)
![2022060810580200-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/44122706/172579325-3b1943b9-2a20-42d4-9ec4-a6b4087a59ca.jpg)

But when writting "Ui" in the category, the mod appears black in the list and can be filtered
See followed pics :

![image](https://user-images.githubusercontent.com/44122706/172579597-27244fb9-50d5-4e98-86ca-7618f0268869.png)
![2022060811072500-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/44122706/172579640-87489264-5f21-4931-8311-b0f6a2129112.jpg)
![2022060811073200-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/44122706/172579677-16c1f265-8509-457c-b8e4-2d19e664764a.jpg)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.

**Comment by BigBoss320** [comment]
so how do i report an issue without being able to do it

**Comment by Raytwo** [comment]
> so how do i report an issue without being able to do it

By opening a Discussion like a civilised person.

**Comment by BigBoss320** [comment]
Haha. Already did it. But issue or discussion it's nearly the same

**Comment by Raytwo** [comment]
Not really, issues are for developers to track what needs fixing by using features such as a kanban board or closing issues by linking them to pull requests. Discussions are to report issues that we haven't confirmed exist yet and gather more feedback on it, which is needed because people used to open issues every day for things that they had caused themselves. :(

**Comment by BigBoss320** [comment]
Oh okay I understand
