### ISSUE TITLE
The game takes ages to boot with mods on

### ISSUE THREAD

**Issue by MissingNerd** [Raytwo/ARCropolis#36]
The game takes a whopping 1:40 Minutes to boot since today. Holding L on startup reduces the boot time to the normal duration. Removing all mods doesn't tho. This is both on my switch as well as my friend's. We are both still on 10.2.0 since Atmosphere isn't updated yet. Going to the home menu and back in during the boot process leaves me with a black screen.

My model is a Day 1 Switch. My friend's is from sometime in 2018.

**Comment by Raytwo** [comment]
Is it fixed now? Might've been an issue with the update server not responding.

**Comment by MissingNerd** [comment]
Seems like it. Guess I can close this now
