### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by arcenedon** [Raytwo/ARCropolis#366]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.5.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [X] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

With 4 or more players or CPUs with no .nro plugins in the skyline folder and only cosmetics, the game will crash repeately at random intervals.

### Crash report

[01655000594_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/8885126/01655000594_01006a800016e000.log)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
