### ISSUE TITLE
[Incorrect behavior] Joker One Slot Victory Lines are silent

### ISSUE THREAD

**Issue by MewtwoFanz** [Raytwo/ARCropolis#376]
### System Firmware Version

14.1.2

### Atmosphere Version

1.3.1

### Smash Version

13.0.1

### ARCropolis Version

3.5.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

One slot Joker Victory Lines should play as normal, but they don't.

### Minimal modpack to reproduce the panic

https://gamebanana.com/sounds/49165

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
