### ISSUE TITLE
11.0.1 booting error

### ISSUE THREAD

**Issue by TwistedTempest** [Raytwo/ARCropolis#38]
Booting up SSBU on 9.0.2 11.0.1 FW prompts a screen asking to set up ARCropolis, but crashes atmosphere instantly when selected.

**Comment by Raytwo** [comment]
Is this still relevant or has your error been resolved with the latest update?

**Comment by TwistedTempest** [comment]
> Is this still relevant or has your error been resolved with the latest update?

The issue was with Atmosphere, which I have resolved.
