### ISSUE TITLE
[Crash] won't start after switch logo or arcropolis notifications

### ISSUE THREAD

**Issue by jcolston95** [Raytwo/ARCropolis#381]
### System Firmware Version

14.1.1

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.5.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

It started when I was trying to install training modpack and since then, it started crashing. I uninstalled both arcropolis and training modpack and reinstalled arcropolis only and it still won't start, unless I remove ALL mods. If I could find a way to figure out which mod is causing this to happen, it would be extremely helpful and save a lot of time.

### Crash report

[01656823902_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/9034125/01656823902_01006a800016e000.log)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.

**Comment by jcolston95** [comment]
my b
