### ISSUE TITLE
[Crash] [v3.5.0] Software aborts on startup

### ISSUE THREAD

**Issue by sterlingvm** [Raytwo/ARCropolis#386]
![image](https://user-images.githubusercontent.com/87245870/179427547-e8102758-d5b9-4180-9df2-e9efddd87d64.png)

**Setup**
System firmware version: 12.0.1
Atmosphère version: 0.19.1
Smash version: 11.0.1
ARCropolis version: 1.1.1
microSD card format: exFAT

**Reproducibility**
It is reproduced every time the game is opened.

**What happened and what's the context?**
At the game startup, it gives an abort error, and then the game crashes. It then prompts to check for corrupted data, says it finds none, then asks me to redownload, I click done or redownload it. I boot It up again... same error, same place.

Once I was able to get to the arcropolis update page that opens once smash boots up but right after that "software is aborting" error.

Any troubleshooting solutions? Is this an FAQ?

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
