### ISSUE TITLE
Config crash persists. 

### ISSUE THREAD

**Issue by xKito** [Raytwo/ARCropolis#39]
With new ARCropolis, every time I try to launch the game I am met with the "Updating config file" fake error and then my game crashes with the error 0x4A2 and 01000000100F.

**Comment by Raytwo** [comment]
Sorry to hear but if you're getting the message it pretty much means the config itself wasn't the one causing the crash anyway.
Please send a crash report generated right after getting this error so I can investigate.

**Comment by CoatlessEskimo** [comment]
Also occurs when HDR attempts to copy its files for all slots.
[Crash dumps here.](https://drive.google.com/folderview?id=1CMbQkBlq8WqtYflvhdQ-3Gi9YamUO4mF)

**Comment by xKito** [comment]
I would up resetting my Atmosphère folder and that fixed it for me. My assumption is I had a bad module.

**Comment by Randomflop** [comment]
it's a problem with custom themes I had the same issue I was able to fix it by removing all my themes and deleting the contents folder  01000000100F, 0100000000001000, and 010000000000100D. There may be more for you so also try searching that error code and reading forums to find the right folders to delete

**Comment by Artdigy** [comment]
I also have this issue. I have completely removed the files for Smash and redownloaded and any attempt to update or create a config crashes atmosphere with the exact same error. This has nothing to do with themes (I have none installed) and it has nothing to do with any of those content folders for anyone else, as I don't have any of those and removed all that I did have. Though, Smash Ultimate just released yet another update, and it's likely that it broke Arcropolis and we need to wait. 
I really commend how hard they work. Not even three days after and the poor thing is broken again thanks to Nintendo

**Comment by Raytwo** [comment]
>  Also occurs when HDR attempts to copy its files for all slots.
> 
> [Crash dumps here.](https://drive.google.com/folderview?id=1CMbQkBlq8WqtYflvhdQ-3Gi9YamUO4mF) 

Turns out you cut it right before the interesting part lol

**Comment by Artdigy** [comment]
Can you please reopen this? He might not have supplied the right information in time but clearly a lot of us are having this issue, man

**Comment by Raytwo** [comment]
I closed it because nobody was providing anything to confirm this was still an issue but sure.

**Comment by Anxietytimmy** [comment]
yeah im having the exact same issue

**Comment by Anxietytimmy** [comment]
![WIN_20210111_15_05_56_Pro](https://user-images.githubusercontent.com/71737812/104248900-38499d80-541f-11eb-867b-9c945dbfc53a.jpg)
this is the crash image

**Comment by Raytwo** [comment]
Same reply as in #43:

Hey there,
Sorry for the lack of answer, I've been busy working on the latest version,

Worry not, this bug is fixed in the upcoming version (1.0.0) that should come out in a day or two.
Please update when the time comes!
