### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by SolelyAli** [Raytwo/ARCropolis#396]
### System Firmware Version

14.1.2

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.6.1

### Version channel

Stable

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

The game either doesn't load an online arena match, leading to the arena crashing (even if I'm not the host of the said arena), or freezes the moment the match ends, forcing me to close the application. This shouldn't be a problem with my mods because I have deleted the ones I've recently installed and this only started happening after today's update to Acropolis.

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  00000000000000ad
    Process Flags:               00000077
    User Exception Address:      0000005d71955000
Exception Info:
    Type:                        Data Abort
    Address:                     000000422e551a75
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   00000000000005f6
    Thread Name:                 ResLoadingThread
    Stack Region:                00000037adda0000-00000037adde0000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000042028d3200
        X[02]:                   00000000000004b3
        X[03]:                   0000000000000000
        X[04]:                   0000000000ffffff
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   000000427fbd9b80
        X[09]:                   000000427fbd9c0c
        X[10]:                   0000000000ffffff
        X[11]:                   0000000a84134000
        X[12]:                   0000000000000018
        X[13]:                   000000422e551a75
        X[14]:                   0000004216551a80
        X[15]:                   0000004215b41ec0
        X[16]:                   0000000a875b8ed8
        X[17]:                   0000000a86cbef30 (nnSdk + 0x339f30) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5EnterEv + 0x0)
        X[18]:                   0000000000000000
        X[19]:                   000000420edfb9e8
        X[20]:                   0000000000ffffff
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   000000000000fb3c
        X[27]:                   0000000000000000
        X[28]:                   00000042173ee06c
        FP:                      00000037adddfd10
        LR:                      0000000a82345e88 (cross2_Release.nss + 0x3541e88)
        SP:                      00000037adddfcd0
        PC:                      0000000a82345fc8 (cross2_Release.nss + 0x3541fc8)
    Stack Trace:
        ReturnAddress[00]:       0000000a82345e88 (cross2_Release.nss + 0x3541e88)
        ReturnAddress[01]:       0000000a82348ea0 (cross2_Release.nss + 0x3544ea0)
        ReturnAddress[02]:       0000000a823471c4 (cross2_Release.nss + 0x35431c4)
        ReturnAddress[03]:       0000000a86cb94b8 (nnSdk + 0x3344b8)
        ReturnAddress[04]:       0000000a86cbd984 (nnSdk + 0x338984)
        ReturnAddress[05]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0037adddfcd0 3c fb 00 00 00 00 00 00 ff ff ff 00 00 00 00 00
                                 0037adddfce0 60 74 8a 02 42 00 00 00 d8 ec ad 0e 42 00 00 00
                                 0037adddfcf0 b3 04 00 00 00 00 00 00 00 32 8d 02 42 00 00 00
                                 0037adddfd00 ff ff ff 00 00 00 00 00 d8 ec ad 0e 42 00 00 00
                                 0037adddfd10 60 fd dd ad 37 00 00 00 88 5e 34 82 0a 00 00 00
                                 0037adddfd20 3c fb 00 00 00 00 00 00 ff ff ff 00 00 00 00 00
                                 0037adddfd30 60 74 8a 02 42 00 00 00 d8 ec ad 0e 42 00 00 00
                                 0037adddfd40 b3 04 00 00 00 00 00 00 00 32 8d 02 42 00 00 00
                                 0037adddfd50 80 43 0d 01 42 00 00 00 cf 01 00 00 00 00 00 00
                                 0037adddfd60 e0 fd dd ad 37 00 00 00 a0 8e 34 82 0a 00 00 00
                                 0037adddfd70 00 00 00 00 00 00 00 00 08 a4 29 00 3d 54 06 00
                                 0037adddfd80 b0 fd dd ad ff ff ff 00 80 ad b7 86 0a 00 00 00
                                 0037adddfd90 cf 3f 21 17 42 00 00 00 88 fe dd ad 37 00 00 00
                                 0037adddfda0 80 79 11 03 42 00 00 00 9c 3f 21 17 42 00 00 00
                                 0037adddfdb0 01 00 00 00 00 00 00 00 80 9a ac 0e 42 00 00 00
                                 0037adddfdc0 80 74 8a 02 42 00 00 00 d8 ec ad 0e 42 00 00 00
    TLS Address:                 0000006154a3e000
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 006154a3e000 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e020 53 46 43 4f 00 00 00 00 00 00 00 00 eb ca d2 c4
                                 006154a3e030 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e040 68 13 43 db 00 00 00 00 10 00 00 00 00 00 00 00
                                 006154a3e050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006154a3e0f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           7
    Module 00:
        Address:                 0000000a7eddc000-0000000a7ee00000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
