### ISSUE TITLE
No Sound Effects Being Played

### ISSUE THREAD

**Issue by MikeyProHD** [Raytwo/ARCropolis#397]
I tested this spoofing mod using a Mr. L mod that was set to go over the custom c08 slot (Link to the mod here: https://t.co/16aDUg0B0W). In training mode with two Luigi's present, I discovered that whether or not you're player 1 with the mod enabled, the CPU Luigi won't play any voice lines. There are also no sound effects relating to rolling, spot dodging, jumping (The double jump sound effect plays, though), no walking or running beside from the universal stage walking sound effect, no crouching nothing for his final smash, etc. The hit sound effects seem to work fine, though.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
