### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by AlexFenlon** [Raytwo/ARCropolis#40]
I've been having a problem with arcropolis crashing since I updated to Smash update 9.0.1 and ever since crashing every time I tried to use the mod. Since the latest update of arcopolis there has been an error code 2--0069 and I click details and it says "0 Error:0x2ee602" 
Any help is much appreciated.

**Comment by Raytwo** [comment]
The path of your mod is too long (> 255 characters). Rename directories to make it shorter than that.

**Comment by AlexFenlon** [comment]
> The path of your mod is too long (> 255 characters). Rename directories to make it shorter than that.

All I did was install the mod and the folders exefs and romfs goes into its normal directory (atmosphere/contents/01006A800016E000). All I had installed is Arcropolis. I do not see how I am able to rename directories if the switch requires this folder for smash?
