### ISSUE TITLE
[Incorrect behavior] Selecting music with added char slots for DLC chars cause inf load

### ISSUE THREAD

**Issue by Demonslayerx8** [Raytwo/ARCropolis#402]
### System Firmware Version

14.1.2

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.6.2

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### Expected behavior

Selecting a vanilla or added song on SSS, then picking an added char slot, will make it inf load on VS screen, but if not selecting a song, then it'll work fine (via DLC char additions).

Vanilla char slot additions are fine with music selection. There's no crash report or any logs at all. Can be easily reproduced.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
