### ISSUE TITLE
libarcropolis.nro is corrupted | Can't be deleted | Can't be overwritten

### ISSUE THREAD

**Issue by EdgarUstian** [Raytwo/ARCropolis#41]
I have tried to update Arcropolis to the newest version after updating atmosphere and hekate to the latest version for it to work with Switch 11.0 but the libarcropolis.nro file in my SD card is corrupted with size being 0 KB and when deleted just shows up back in my SD card again.
![image](https://user-images.githubusercontent.com/27697916/103324753-d0568880-4a16-11eb-8994-7b56979bd636.png)

What is a workaround for that so that I can get some mods working on my switch again

**Comment by Raytwo** [comment]
Uuuuuuuuuh how is this supposed to be a ARCropolis issue? if the file on your SD is corrupted that is not something I can personally fix, lol.
