### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by justintime0057** [Raytwo/ARCropolis#420]
### System Firmware Version

14.1.2

### Atmosphere Version

1.3.2

### Smash Version

13.0.1

### ARCropolis Version

3.7.2/3.7.1

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

Was prompted for an update for ARCropolis 3.7.2 before Smash loaded up. Clicked yes and it downloaded. After the next boot, it asked if I wanted to install (as opposed to the previous "download" prompt), and I clicked yes again. It did show the splash screen of the new update, but never loaded Smash after proceeding. It then gave me error code **2--0069**, stating 

> thread has panicked at 'called 'Result::unwrap()' on an 'Err' value: Custom { kind: Other, error: "Failed to mount the filesystem accessor" }', src\fuse\arc.rs:93:14]}]}]}]}]}]}]}]}]}]}]}]}]}]

I figured something was wrong with the ARCropolis auto updater, so I went and manually downloaded the 3.7.2 release.zip and then overwrote all the files within my SD, but still got the same error.

I then figured that I should just go back to the previous version of ARCropolis that worked (3.7.1), manually downloaded that release.zip and overwrote the files _again_ back to what they originally were, but still get the error.

Lots of posts show the error code I have, but I have not seen any with the exact message attached to the error code. Any help is appreciated, and I can provide any further info anyone may need. The crash report posted below is from the most recent crash, meaning it is after I manually overwrote my SD files with the release.zip 3.7.1 version of ARCropolis. Thank you.

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  00000000000001a0
    Process Flags:               00000077
    User Exception Address:      000000291d1e1000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000002930
    Thread Name:                 Thread_0x0000007CEB69E670
    Stack Region:                00000037c40e2000-00000037c4122000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000003700000000
        X[02]:                   00000037c4121898
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000007cebdcb5f8
        X[20]:                   00000037c4121928
        X[21]:                   0000007cebdcb000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000010
        X[25]:                   0000000000000004
        X[26]:                   0000004fed624603
        X[27]:                   0000000000007369
        X[28]:                   6c6f706f72435241
        FP:                      00000037c41218f0
        LR:                      0000007ceb203034 (nnSdk + 0x7e034) (_ZN2nn6applet18StartLibraryAppletENS0_19LibraryAppletHandleEPv + 0xb4)
        SP:                      00000037c41218c0
        PC:                      0000007ceb203038 (nnSdk + 0x7e038) (_ZN2nn6applet18StartLibraryAppletENS0_19LibraryAppletHandleEPv + 0xb8)
    Stack Trace:
        ReturnAddress[00]:       0000007ceb5423bc (nnSdk + 0x3bd3bc) (_ZN2nn3web19ShowOfflineHtmlPageEPNS0_26OfflineHtmlPageReturnValueERKNS0_22ShowOfflineHtmlPageArgE + 0x8c)
        ReturnAddress[01]:       0000004fed5db6ec (arcropolis + 0x1296ec)
        ReturnAddress[02]:       0000007ceb4b94b8 (nnSdk + 0x3344b8)
        ReturnAddress[03]:       0000007ceb4bd984 (nnSdk + 0x338984)
        ReturnAddress[04]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0037c41218c0 f0 18 12 c4 37 00 00 00 04 6b 54 eb 7c 00 00 00
                                 0037c41218d0 99 0e 00 00 00 00 00 00 00 90 e5 eb 7c 00 00 00
                                 0037c41218e0 00 00 ee 08 0a 00 00 00 00 50 87 15 0a 00 00 00
                                 0037c41218f0 40 19 12 c4 37 00 00 00 bc 23 54 eb 7c 00 00 00
                                 0037c4121900 00 00 08 00 00 00 00 00 00 f5 b3 e6 7c 00 00 00
                                 0037c4121910 1c d0 53 93 22 07 00 00 00 00 00 00 00 00 00 00
                                 0037c4121920 00 50 87 15 0a 00 00 00 00 00 00 00 00 00 00 00
                                 0037c4121930 00 00 ee 08 0a 00 00 00 20 1a 12 c4 37 00 00 00
                                 0037c4121940 80 1f 12 c4 37 00 00 00 ec b6 5d ed 4f 00 00 00
                                 0037c4121950 03 46 62 ed 4f 00 00 00 00 00 00 00 00 00 00 00
                                 0037c4121960 00 00 ee 08 0a 00 00 00 00 00 00 00 00 00 00 00
                                 0037c4121970 c8 9f 5d ed 4f 00 00 00 10 1c 12 c4 37 00 00 00
                                 0037c4121980 00 a6 1b 03 0a 00 00 00 b3 ad 68 ed 4f 00 00 00
                                 0037c4121990 0e 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00
                                 0037c41219a0 03 00 00 00 00 00 00 00 00 71 75 00 0a 00 00 00
                                 0037c41219b0 02 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
    TLS Address:                 0000002f83872a00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002f83872a00 06 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a10 02 00 00 00 26 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a20 53 46 43 4f 00 00 00 00 00 00 00 00 b3 0f 1e d6
                                 002f83872a30 00 00 00 00 00 00 00 00 0a 00 00 00 00 00 00 00
                                 002f83872a40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a50 b6 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a60 53 46 43 49 01 00 00 00 0c 00 00 00 00 00 00 00
                                 002f83872a70 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872a90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872aa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872ab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872ac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872ad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872ae0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002f83872af0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           10
    Module 00:
        Address:                 0000007ce35dc000-0000007ce3600000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000007ce3600000-0000007ce3602000
        Name:                    nnrtld

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
