### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by HeroFromDust** [Raytwo/ARCropolis#429]
### System Firmware Version

15.0.0

### Atmosphere Version

1.4.0

### Smash Version

13.0.1

### ARCropolis Version

3.7.2

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

Ever since the new switch update came out (15.0.0), after installing the new atmosphere update to play the mods again, captain falcon is unplayable. 
At first, I thought it was my mods but even without all my mods it still crash after starting a match with him.
I updated to the most recent version of ARCropolis but the issue keep happening 

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000083
    Process Flags:               00000077
    User Exception Address:      0000003e24239000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000000
Crashed Thread Info:
    Thread ID:                   0000000000000252
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000000000903ba
        X[02]:                   000000000009fd51
        X[03]:                   0000000000000008
        X[04]:                   000000491ab45260 (cross2_Release.nss + 0x3541260)
        X[05]:                   0000000000000000
        X[06]:                   0000000000000001
        X[07]:                   0000000cd63cbd20
        X[08]:                   0000000cc0478498
        X[09]:                   0000000000018010
        X[10]:                   0000000000000018
        X[11]:                   0000000000000000
        X[12]:                   0000000000018008
        X[13]:                   0000000000ffffff
        X[14]:                   00000029f4984658
        X[15]:                   ffffffffffffffff
        X[16]:                   000000491fdb8ee8
        X[17]:                   000000491f4bf020 (nnSdk + 0x33a020) (_ZN2nn2os6detail36InternalCriticalSectionImplByHorizon5LeaveEv + 0x0)
        X[18]:                   000000491fc25c38
        X[19]:                   00000000000903ba
        X[20]:                   000000000000030b
        X[21]:                   0000000cc0478000
        X[22]:                   000000491c934000
        X[23]:                   0000000cc0490530
        X[24]:                   0000000000000007
        X[25]:                   0000000cc0491498
        X[26]:                   000000000000030b
        X[27]:                   000000491c934000
        X[28]:                   0000000cc04913b8
        FP:                      0000000cd63cbd90
        LR:                      000000491ab63810 (cross2_Release.nss + 0x355f810)
        SP:                      0000000cd63cba70
        PC:                      000000491ab639e0 (cross2_Release.nss + 0x355f9e0)
    Stack Trace:
        ReturnAddress[00]:       0000004917c0ffbc (cross2_Release.nss + 0x60bfbc)
        ReturnAddress[01]:       00000049179b25b0 (cross2_Release.nss + 0x3ae5b0)
        ReturnAddress[02]:       0000004917c5cb2c (cross2_Release.nss + 0x658b2c)
        ReturnAddress[03]:       0000004918ae2350 (cross2_Release.nss + 0x14de350)
        ReturnAddress[04]:       0000004918961d54 (cross2_Release.nss + 0x135dd54)
        ReturnAddress[05]:       000000491ab4d800 (cross2_Release.nss + 0x3549800)
        ReturnAddress[06]:       000000491ab40538 (cross2_Release.nss + 0x353c538)
        ReturnAddress[07]:       000000491adcf4ac (cross2_Release.nss + 0x37cb4ac)
        ReturnAddress[08]:       000000491f4bcf28 (nnSdk + 0x337f28) (_ZN2nn2os6detail17CallFiberFunctionEPFPNS0_9FiberTypeEPvES4_ + 0x14)
    TLS Address:                 0000003b92d47000
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 003b92d47000 00 00 01 00 09 00 00 00 00 c0 28 00 78 a9 3c d6
                                 003b92d47010 53 46 43 4f 00 00 00 00 00 00 00 00 99 5d e2 a4
                                 003b92d47020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d47030 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 003b92d47040 01 00 87 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 003b92d47050 28 00 87 01 78 a9 3c d6 0c 00 28 00 00 00 00 00
                                 003b92d47060 00 00 00 00 18 00 00 00 50 bd 3c d6 0c 00 18 00
                                 003b92d47070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d47080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d47090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 003b92d470f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           8
    Module 00:
        Address:                 00000049175dc000-0000004917600000
        Name:                    [00000000]
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 01:
        Address:                 0000004917600000-0000004917602000
        Name:                    nnrtld
        Module Id:               285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    Module 02:
        Address:                 0000004917604000-000000491afcb000
        Name:                    cross2_Release.nss
        Module Id:               B9B166DF1DB90BAFFBD8027EB0DF14D6949D6A11000000000000000000000000
    Module 03:
        Address:                 000000491ea4a000-000000491edb7000
        Name:                    multimedia
        Module Id:               60C6EDBBFCEBD4176CC301D5D9CB5A6F094F9360000000000000000000000000
    Module 04:
        Address:                 000000491f15f000-000000491f178000
        Name:                    Skyline
        Module Id:               B44280982D6BBFA90259E041B53C1889D3F10328000000000000000000000000
    Module 05:
        Address:                 000000491f185000-000000491f6c6000
        Name:                    nnSdk
        Module Id:               5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
    Module 06:
        Address:                 0000003428b67000-0000003428cd5000
        Name:                    arcropolis
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
    Module 07:
        Address:                 000000639516b000-0000006395230000
        Name:                    training_modpack
        Module Id:               0000000000000000000000000000000000000000000000000000000000000000
Thread Report:
Number of Threads:               30
Threads[00]:
    Thread ID:                   000000000000023c
    Thread Name:                 MainThread
    Stack Region:                00000042ace53000-00000042acf53000
    Registers:
        X[00]:                   00000042acf4fc98
        X[01]:                   00000042acf4fc9c
        X[02]:                   0000000000000001
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000042acf4fcb0
        LR:                      000000491f4be444 (nnSdk + 0x339444) (_ZN2nn2os6detail30InterProcessEventImplByHorizon4WaitEjb + 0x34)
        SP:                      00000042acf4fc80
        PC:                      000000491f50e900 (nnSdk + 0x389900)
    Stack Trace:
        ReturnAddress[00]:       000000491f553fb8 (nnSdk + 0x3cefb8) (NvOsEventWait + 0x88)
        ReturnAddress[01]:       000000491f55b608 (nnSdk + 0x3d6608)
        ReturnAddress[02]:       000000491f5a5694 (nnSdk + 0x420694)
        ReturnAddress[03]:       000000491f5ac200 (nnSdk + 0x427200)
        ReturnAddress[04]:       000000491ae72c60 (cross2_Release.nss + 0x386ec60)
        ReturnAddress[05]:       000000491ad4aafc (cross2_Release.nss + 0x3746afc)
        ReturnAddress[06]:       00000049178c9cf0 (cross2_Release.nss + 0x2c5cf0)
        ReturnAddress[07]:       000000491f422a2c (nnSdk + 0x29da2c) (_ZN2nn4init5StartEmmPFvvES2_ + 0x4c)
        ReturnAddress[08]:       00000049176000c0 (nnrtld + 0xc0)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
