### ISSUE TITLE
Trying to create a config file crashes 

### ISSUE THREAD

**Issue by Anxietytimmy** [Raytwo/ARCropolis#43]
When the game boot it says it will create a config file, when i press ok, atmosphere just instantly crashes
![WIN_20210111_15_05_56_Pro](https://user-images.githubusercontent.com/71737812/104250633-d5f29c00-5422-11eb-8f01-26c5154e21af.jpg)
This is what it shows in crash

**Comment by Artdigy** [comment]
I have this exact thing, too. Reinstalling seems to do no good and it is certainly not a mod problem

**Comment by Artdigy** [comment]
But timmy maybe in the future check to see if a bug report already exists and just add to it, you don't wanna overwhelm Raytwo

**Comment by Raytwo** [comment]
Hey there,
Sorry for the lack of answer, I've been busy working on the latest version,

Worry not, this bug is fixed in the upcoming version (1.0.0) that should come out in a day or two.
Please update when the time comes!
