### ISSUE TITLE
[Feature] Aditional fighter & stage support

### ISSUE THREAD

**Issue by Bibidimah21** [Raytwo/ARCropolis#431]
### Provide details

Anti-Fake this. Arcropolis works with custom fighter & stages support Goes c00 instead of original's c08 or next, additional fighters & stages with .nro unique requires, additional fighter folder like BrawlEx better.

### How should it be implemented?

Arcropolis 3.8 is going support like Paid DLC.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.

**Comment by Bibidimah21** [comment]
Reopen this
