### ISSUE TITLE
New mods don't load on next boot, game must be restarted and booted a second time for new mods to show up

### ISSUE THREAD

**Issue by mkPrieur** [Raytwo/ARCropolis#437]
### System Firmware Version

15.0.0

### Atmosphere Version

1.4.0

### Smash Version

13.0.1

### ARCropolis Version

3.8.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

When new mods are added to the mods folder, the next boot into smash should load these new mods. This does not happen and the game must be restarted and booted up a second time for these new mods to appear. The "New mods detected. Would you like to enable them?" prompt still appears on the first boot into the smash, and even if "Yes" is selected, the game still must be booted up a second time (the prompt does not appear on the second boot, but the mods show up).

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
