### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by Nin10Doug** [Raytwo/ARCropolis#441]
### System Firmware Version

15.0.0

### Atmosphere Version

1.4.0

### Smash Version

13.0.1

### ARCropolis Version

3.8.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [X] During the loading for a battle
- [X] At random
- [ ] After a long time playing

### Details

Crash on Vs Screen.
When loading into a match after a few seconds seeing the character portraits, the game crashed.

Mods used:
-Fury Bowser (White) c07
-Samus Revision v.2 c00
-Mega Mewtwo X c05
-Twilight Princess Ganondorf c01
-Brawl Wolf c04
-Pokemon Trainer Gold c02 (The pokemons have zero mods
-2B/A2 c07
-Sothis Regalia Byleth c07

### Crash report

Atmosphère Crash Report (v1.7):
Result:                          0xCA8 (2168-0006)

Process Info:
    Process Name:                Application
    Program ID:                  01006a800016e000
    Process ID:                  0000000000000144
    Process Flags:               00000077
    User Exception Address:      0000004b7de1e000
Exception Info:
    Type:                        User Break
    Address:                     000000644e30e998 (nnSdk + 0x389998)
    Break Reason:                0x0
    Break Address:               0000000000000000
    Break Size:                  0x0
Crashed Thread Info:
    Thread ID:                   0000000000002162
    Thread Name:                 TaskWorker2
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000000000000000
        X[02]:                   0000000000000000
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000124294f2c0
        LR:                      000000644e2b8180 (nnSdk + 0x333180) (nnosBreak + 0x10)
        SP:                      000000124294f2b0
        PC:                      000000644e30e994 (nnSdk + 0x389994)
    Stack Trace:
        ReturnAddress[00]:       000000644e49ec10 (nnSdk + 0x519c10) (__nnmusl_GetTlsValue + 0x0)
        ReturnAddress[01]:       000000644e450d84 (nnSdk + 0x4cbd84)
        ReturnAddress[02]:       0000006449bcd05c (cross2_Release.nss + 0x37c905c)
        ReturnAddress[03]:       0000006449d5a9fc (cross2_Release.nss + 0x39569fc)
        ReturnAddress[04]:       0000006449d5a910 (cross2_Release.nss + 0x3956910)
        ReturnAddress[05]:       0000006449d48ce0 (cross2_Release.nss + 0x3944ce0)
        ReturnAddress[06]:       0000006449d433d4 (cross2_Release.nss + 0x393f3d4)
        ReturnAddress[07]:       0000006449d432e4 (cross2_Release.nss + 0x393f2e4)
        ReturnAddress[08]:       0000006449d45930 (cross2_Release.nss + 0x3941930)
        ReturnAddress[09]:       0000006449d456e4 (cross2_Release.nss + 0x39416e4)
        ReturnAddress[10]:       0000006449d3340c (cross2_Release.nss + 0x392f40c)
        ReturnAddress[11]:       0000006449d53b80 (cross2_Release.nss + 0x394fb80)
        ReturnAddress[12]:       0000006449d36864 (cross2_Release.nss + 0x3932864)
        ReturnAddress[13]:       0000006449d302d0 (cross2_Release.nss + 0x392c2d0)
        ReturnAddress[14]:       0000006449d30238 (cross2_Release.nss + 0x392c238)
        ReturnAddress[15]:       0000006449d30130 (cross2_Release.nss + 0x392c130)
        ReturnAddress[16]:       0000006449d2fc80 (cross2_Release.nss + 0x392bc80)
        ReturnAddress[17]:       0000006449d2f9b0 (cross2_Release.nss + 0x392b9b0)
        ReturnAddress[18]:       0000006449d30c40 (cross2_Release.nss + 0x392cc40)
        ReturnAddress[19]:       0000006449be2160 (cross2_Release.nss + 0x37de160)
        ReturnAddress[20]:       0000006449bdf638 (cross2_Release.nss + 0x37db638)
        ReturnAddress[21]:       00000064499ebea8 (cross2_Release.nss + 0x35e7ea8)
        ReturnAddress[22]:       0000006449c8c590 (cross2_Release.nss + 0x3888590)
        ReturnAddress[23]:       0000006449c91308 (cross2_Release.nss + 0x388d308)
        ReturnAddress[24]:       0000006449a05d7c (cross2_Release.nss + 0x3601d7c)
        ReturnAddress[25]:       00000064499d3b80 (cross2_Release.nss + 0x35cfb80)
        ReturnAddress[26]:       00000064499c5a70 (cross2_Release.nss + 0x35c1a70)
        ReturnAddress[27]:       0000006447be2550 (cross2_Release.nss + 0x17de550)
        ReturnAddress[28]:       00000064497a3998 (cross2_Release.nss + 0x339f998)
        ReturnAddress[29]:       00000064467aa3ec (cross2_Release.nss + 0x3a63ec)
        ReturnAddress[30]:       00000064467b3438 (cross2_Release.nss + 0x3af438)
        ReturnAddress[31]:       0000006446a8b5a4 (cross2_Release.nss + 0x6875a4)
    TLS Address:                 00000048a9887e00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0048a9887e00 00 00 01 00 09 00 00 00 40 20 28 00 78 f7 94 42
                                 0048a9887e10 53 46 43 4f 00 00 00 00 00 00 00 00 99 5d e2 a4
                                 0048a9887e20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887e30 00 00 00 00 01 00 00 00 01 00 00 00 00 00 00 00
                                 0048a9887e40 01 00 85 01 06 41 28 c0 0b 00 00 00 00 00 00 00
                                 0048a9887e50 28 00 85 01 78 f7 94 42 12 00 28 00 00 00 00 00
                                 0048a9887e60 00 00 00 00 18 00 00 00 50 0b 95 42 12 00 18 00
                                 0048a9887e70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887e80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887e90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887ea0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887eb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887ec0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887ed0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887ee0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0048a9887ef0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
