### ISSUE TITLE
Arcopolis Crashes on "Config" creation.

### ISSUE THREAD

**Issue by Alo81** [Raytwo/ARCropolis#45]
Arcropolis fully crashes Atmosphere when attempting to update Config file.  I have fully emptied my Smash contents folder and reinstalled just Arcropolis and the crash still occurs.  

Running Skyline Logger returns these results before the Switch crashes to Atmospheres crash screen.  

> [skyline_main] Begining initialization.
[And64InlineHook] inline hook 0x1fbdf47960->0x1fbdd0a578 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fbe09b2c0->0x1fbdd0f848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fbe09b300->0x1fbdd0f848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fbe077000->0x1fbdd0a570 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fbdeb23d0->0x1fbdd0a61c successfully! 4 bytes overwritten
[skyline_main] Mounted Rom (0x0)
[skyline_main] text: 0x1fb6404000 | rodata: 0x1fb9c3e000 | data: 0x1fbb0ec000 | bss: 0x1fbd5f5000 | heap: 0x6867e00000
[SafeTaskQueue] Starting thread.
[SafeTaskQueue] Thread started.
[skyline_main] Mounted SD (0x0)
[PluginManager] Initializing plugins...
[PluginManager] Opening plugins...
[PluginManager] Read rom:/skyline/plugins/libarcropolis.nro
[PluginManager] Loading plugins...
[PluginManager] Loaded 'rom:/skyline/plugins/libarcropolis.nro'
[PluginManager] Running `main` for rom:/skyline/plugins/libarcropolis.nro
[HashesMgr] Failed to read "rom:/skyline/hashes.txt" "(Result code: 514)"
[And64InlineHook] inline hook 0x1fb99ca474->0x1fb63dc000 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fb97bb1e8->0x1fb63dc024 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fb97bbd08->0x1fb63dc048 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fb97bb8f8->0x1fb63dc06c successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fb97bb988->0x1fb63dc090 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x1fb9c1a230->0x3ee48854b4 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x1fb99cd3b0->0x3ee4885ac8 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x1fb9a18460->0x3ee48856e8 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x1fb97b7d70->0x3ee487b6fc successfully! 20 bytes overwritten
ARCropolis v1.0.1 - File replacement plugin is now installed
[PluginManager] Finished running `main` for 'rom:/skyline/plugins/libarcropolis.nro' (0x0)
[handleNnFsMountRom] Prevented game from double mounting as 'rom'
[TcpLogger] Logger initialized.

Atmospheres' Fatal Reports returns the following: 

> Atmosphère Fatal Report (v1.1):
Result:                          0x4A2 (2162-0002)

Program ID:                      010000000000100f
Process Name:                    LibAppletOf
Firmware:                        11.0.1 (Atmosphère 0.17.1-master-49f07b06)
General Purpose Registers:
Start Address:                   0000000000000000
Stack Trace:
        ReturnAddress[00]:       000000072d29ba58
        ReturnAddress[01]:       000000072d678d70
        ReturnAddress[02]:       000000072d678794
        ReturnAddress[03]:       000000072d036680
        ReturnAddress[04]:       000000072d03684c
        ReturnAddress[05]:       000000072d038a7c
        ReturnAddress[06]:       000000072d04100c
        ReturnAddress[07]:       000000072d041258
        ReturnAddress[08]:       000000072d03c8b4
        ReturnAddress[09]:       000000072d03ced8
        ReturnAddress[10]:       000000072d004b60
        ReturnAddress[11]:       000000072d00455c
        ReturnAddress[12]:       000000072d1d4328
        ReturnAddress[13]:       000000072d229344
        ReturnAddress[14]:       000000072d3d81f4
        ReturnAddress[15]:       000000072d0000d4
        ReturnAddress[16]:       0000000000000000
        ReturnAddress[17]:       0000000000000000
        ReturnAddress[18]:       0000000000000000
        ReturnAddress[19]:       0000000000000000
        ReturnAddress[20]:       0000000000000000
        ReturnAddress[21]:       0000000000000000
        ReturnAddress[22]:       0000000000000000
        ReturnAddress[23]:       0000000000000000
        ReturnAddress[24]:       0000000000000000
        ReturnAddress[25]:       0000000000000000
        ReturnAddress[26]:       0000000000000000
        ReturnAddress[27]:       0000000000000000
        ReturnAddress[28]:       0000000000000000
        ReturnAddress[29]:       0000000000000000
        ReturnAddress[30]:       0000000000000000
        ReturnAddress[31]:       0000000000000000

**Comment by Solotato** [comment]
I have also run into this issue with a near-identical log.

**Comment by Solotato** [comment]
This persists in the newest update as well (1/26/21)

**Comment by Raytwo** [comment]
Have you guys downloaded it through GitHub or through the auto-updater?

**Comment by Alo81** [comment]
I haven't tested with the newest update, but with the last I had tried both auto-updater and GitHub.

**Comment by Raytwo** [comment]
I remember pushing a broken update on the update server for a few minutes (for 1.0.1), but if you tried both it should be working fine now.
If you happen to get a regular Nintendo error window, please send me what the details (there is a button for it) say so I can at least know where the error comes from.

If you can, send me the entire .log file, that way I can try to track what's happening.

**Comment by Solotato** [comment]
From logger:
[skyline_main] Begining initialization.
[And64InlineHook] inline hook 0x774e347960->0x774e10a578 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x774e49b2c0->0x774e10f848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x774e49b300->0x774e10f848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x774e477000->0x774e10a570 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x774e2b23d0->0x774e10a61c successfully! 4 bytes overwritten
[skyline_main] Mounted Rom (0x0)
[skyline_main] text: 0x7746804000 | rodata: 0x774a03e000 | data: 0x774b4ec000 | bss: 0x774d9f5000 | heap: 0xb38a00000
[SafeTaskQueue] Starting thread.
[SafeTaskQueue] Thread started.
[skyline_main] Mounted SD (0x0)
[PluginManager] Initializing plugins...
[PluginManager] Opening plugins...
[PluginManager] Read rom:/skyline/plugins/libarcropolis.nro
[PluginManager] Loading plugins...
[handleNnFsMountRom] Prevented game from double mounting as 'rom'
[PluginManager] Loaded 'rom:/skyline/plugins/libarcropolis.nro'
[PluginManager] Running `main` for rom:/skyline/plugins/libarcropolis.nro
[HashesMgr] Failed to read "rom:/skyline/hashes.txt" "(Result code: 514)"
[And64InlineHook] inline hook 0x7749dca474->0x77467dc000 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7749bbb1e8->0x77467dc024 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7749bbbd08->0x77467dc048 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7749bbb8f8->0x77467dc06c successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x7749bbb988->0x77467dc090 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x774a01a230->0x4fbf19b4b4 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x7749dcd3b0->0x4fbf19bac8 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x7749e18460->0x4fbf19b6e8 successfully! 20 bytes overwritten
[And64InlineHook] inline hook 0x7749bb7d70->0x4fbf1916fc successfully! 20 bytes overwritten
ARCropolis v1.0.1 - File replacement plugin is now installed
[PluginManager] Finished running `main` for 'rom:/skyline/plugins/libarcropolis.nro' (0x0)
[TcpLogger] Logger initialized.

It wasn't a general nintendo error, it was an atmos crash. And I dl'd the newest one after u fixed the errors within the previous one, still no dice for me tho.

I attached my atmos error log here:
[01611853902_010000000000100f.log](https://github.com/Raytwo/ARCropolis/files/5888914/01611853902_010000000000100f.log)

**Comment by Raytwo** [comment]
If that's the full content of your crash report, I'm sorry to say the error comes from elsewhere.
This report is way too empty to be correct in the first place.

Also of note is that your crash report is version 1.1 which is quite outdated (my latest is 1.5 for instance)
Consider updating your Atmosphere installation and updating your Switch if needed then try again.

If you still encounter the issue with everything updated, please reopen a new issue about it!

**Comment by Alo81** [comment]
As a follow up, completely removing and replacing my Atmosphere folder, then reinstalling Arcropolis seems to have resolved this.  Seems like there may have been a clash with something else I had installed.

**Comment by Raytwo** [comment]
Strange, but glad to hear this was not a bug!

**Comment by Hyphendrip** [comment]
> As a follow up, completely removing and replacing my Atmosphere folder, then reinstalling Arcropolis seems to have resolved this. Seems like there may have been a clash with something else I had installed.

I think I have the same problem as you have.

Can you please tell me how did you "completely remove and replace" atmosphere?
Like, literally completely remove and replace everything in your atmosphere folder, then you reinstall arc, or you just remove the content id folder of the game, replace it, and then reinstall with arc?

**Comment by GarnetSunset** [comment]
On 0.9.6 I'm experiencing a similar issue. 

```
[WinError 10061] No connection could be made because the target machine actively refused it
Couldn't connect to socket! Trying again in 5 seconds.
[WinError 10061] No connection could be made because the target machine actively refused it
Socket Connection Success!
[skyline_main] Begining initialization.

[And64InlineHook] inline hook 0x3159eee960->0x3159cb1578 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x315a0422c0->0x3159cb6848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x315a042300->0x3159cb6848 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x315a01e000->0x3159cb1570 successfully! 4 bytes overwritten
[And64InlineHook] inline hook 0x3159e593d0->0x3159cb161c successfully! 4 bytes overwritten
[skyline_main] Mounted Rom (0x0)
[skyline_main] text: 0x3152204000 | rodata: 0x3155b6e000 | data: 0x315707d000 | bss: 0x315959c000 | heap: 0x5cc2200000
[SafeTaskQueue] Starting thread.
[SafeTaskQueue] Thread started.
[skyline_main] Mounted SD (0x0)
[PluginManager] Initializing plugins...
[PluginManager] Opening plugins...
[PluginManager] Read rom:/skyline/plugins/libarcropolis.nro
[PluginManager] Loading plugins...
[PluginManager] Loaded 'rom:/skyline/plugins/libarcropolis.nro'
[PluginManager] Running `main` for rom:/skyline/plugins/libarcropolis.nro
[ARC::Config
] Configuration file successfully created



0
Error: 0x0

[handleNnFsMountRom] Prevented game from double mounting as 'rom'
[TcpLogger] Logger initialized.```
