### ISSUE TITLE
Ditto matchups with sound not working

### ISSUE THREAD

**Issue by foolishhabits** [Raytwo/ARCropolis#46]
The problem is as the title states. My switch seems to keep crashing when I try to do the Lucas ditto. The character slot has unique sounds on it to reflect the original PK sounds from the game and I would love to live in a world where I can bake my cake and eat it too. Is there any fix for being able to have these 2 Lucas's play against each other?

**Comment by ThatNintendoNerd** [comment]
This is a known problem with previous ARCropolis releases. Are you using the latest version of ARCropolis now?

**Comment by Raytwo** [comment]
As stated in the changelog for release v1.0.0, support for deprecated versions is dropped, sorry.
Please update to the latest version and if you still need help, reopen an issue.
