### ISSUE TITLE
Skyline plugin has panicked on 1.0.3

### ISSUE THREAD

**Issue by dexkcs** [Raytwo/ARCropolis#48]
![image](https://user-images.githubusercontent.com/80136312/110189800-6e3b4a80-7dee-11eb-9cf3-a11c8f4082f0.jpg)

**Comment by DragonFru2** [comment]
Same results here ![image](https://user-images.githubusercontent.com/80143845/110196840-2f6cbb00-7e15-11eb-9a8a-35c000276a18.jpeg)I tried replacing atmosphere files with a different version of ARCopolis but it's the same. : (

**Comment by AwesomeKirito** [comment]
i got the same shit

**Comment by DragonFru2** [comment]
If this gets you then just replace your root folders with the atmosphere 0.18.1 folders once you open it. Here's the link [](https://github.com/Atmosphere-NX/Atmosphere/releases)

**Comment by DragonFru2** [comment]
https://github.com/Atmosphere-NX/Atmosphere/releases didn't know if it actually was sent last message for some reason lol sorry about that

**Comment by AwesomeKirito** [comment]
Im still getting the error

**Comment by Lagmobile** [comment]
Also on atmosphere 0.18.1. Also getting the same error.

**Comment by ProtoscanV1** [comment]
getting the same error on 0.18.1.

**Comment by DragonFru2** [comment]
Try to delete your root atmosphere folder altogether then put that other atmosphere folder into your sdmc. That update probably affected the atmosphere from said card still as an additional information. That way it's just only the original files stored there without the update errors.

**Comment by dexkcs** [comment]
> Try to delete your root atmosphere folder altogether then put that other atmosphere folder into your sdmc. That update probably affected the atmosphere from said card still as an additional information. That way it's just only the original files stored there without the update errors.

I'm new to modding, do I lose anything for deleting the atmosphere folder? I know there's game IDs in there so I do not want to lose anything for doing this. Also, is the root atmosphere folder the one you see right when you boot up the sd card?

**Comment by DragonFru2** [comment]
You won't lose anything if you're actually gonna delete the atmosphere folder affected by the update first. It should delete all the unnecessary errors it make during the boot. The atmosphere folder you'll find in the link itself will replace it with pretty much everything intact without that ARCoplois update issue for Skyline Plugins.

**Comment by Coolsonickirby** [comment]
Hey there everyone.
There was a bug with the file discovery. Here's a build that should work.
[https://cdn.discordapp.com/attachments/506286717519659023/817640270631141396/release.zip](https://cdn.discordapp.com/attachments/506286717519659023/817640270631141396/release.zip)

**Comment by ProtoscanV1** [comment]
Can confirm the new build works!

**Comment by Raytwo** [comment]
Hey there,

I'm aware of all the current issues and I'm sorry about the lack of prior testing, that's my bad.

May I suggest you set the "beta_updates" field of your configuration (``sd:/atmosphere/contents/01006A800016E000/romfs/arcropolis.toml``) to "true" so you can get temporary fixes until things are stable again?

Also please note that your Atmosphere version has nothing to do so it is pointless to delete anything. Please don't spread misinformation @DragonFru2.

**Comment by AI2550** [comment]
Yeah so I followed everything you said an it still does not work.

**Comment by Raytwo** [comment]
Please try the latest release (1.0.4) which should now work the same as 1.0.1. If you still encounter issues, please open a separate issue.
