### ISSUE TITLE
[Panic] Brief description of the issue

### ISSUE THREAD

**Issue by Pika914PR** [Raytwo/ARCropolis#487]
### System Firmware Version

15.0.1

### Atmosphere Version

1.4.0

### Smash Version

13.0.1

### ARCropolis Version

3.12.0

### Version channel

Stable

### SD card formatting

FAT32

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Steps to reproduce

It only seem to happen whenever i add the libsmashline_hook inside the plugins folder atmosphere/contents/01006A800016E00/romfs/Skyline/plugins

### Details

![IMG_20221227_102241111](https://user-images.githubusercontent.com/121503287/209727471-c7efa63e-6fc7-4af0-bd25-56744096dec1.jpg)
Side note any version of the mod causes the the panick to happen

### Minimal modpack to reproduce the panic

Hewdraw Remix(hdr) plugins smashline_hook

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
