### ISSUE TITLE
[Quality of life] Search mods folder recursively for new mods

### ISSUE THREAD

**Issue by asdfghjkl403622** [Raytwo/ARCropolis#493]
Hello!

I recently installed a bunch of mods which at first didn't work, until I realized that the unzipper put the mods into a containing folder. 

having the mods be discovered recursively would allow for people to have organizational folders for mods and make it easier to use.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
