### ISSUE TITLE
Skyline plugin has panicked

### ISSUE THREAD

**Issue by Prexon339** [Raytwo/ARCropolis#499]
Error Code: 2--0069 

thread has panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF
while parsing a value", line: 1, column: 0)', C:\Users\Raytwo\.cargo\git
\checkouts\skyline-config-986ba11fcbe3faf4\3d27e98\src\lib.rs:298:12

No clue what this means or how to fix it, it happened right after I added the Shiny Soul Silver version of PS2 on gamebanana, and adding the "Parallel Meta Knight" skin.

New(ish) to modding so if I can get a simple explanation that'd be amazing :)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
