### ISSUE TITLE
Newest DLC not showing up on CSS

### ISSUE THREAD

**Issue by ajtempest** [Raytwo/ARCropolis#50]
When i boot vanilla smash, my css is complete, but when i load with mods im missing pyra/mythra.

**Comment by DragonFru2** [comment]
This happens to me with Sephiroth previous patch. What I would do is to check/uncheck a small amount group of mods to load over and over until you found that particular issue with Pyra and Mythra.

**Comment by DragonFru2** [comment]
Replays will also trigger a mario stock icon if I have Sephiroth saved in said replays but it shows Mario's stock icon displayed incorrectly as to replace him as well. Another notice is to check if they even got their music back and stage name on the stage list. The stage could visually be there and be played on, but you won't see the name of it at all. But that's a check before going into the css.

**Comment by itsmeft24** [comment]
your mods are outdated. please do not post your problems with mods on the github issues page. if you need help updating/removing mods, you can join the ult modding discord here: https://discord.gg/ASJyTrZ
