### ISSUE TITLE
Map load crash

### ISSUE THREAD

**Issue by foolishhabits** [Raytwo/ARCropolis#51]
My battlefield no longer loads and it just crashes every time now, how do I get a working battlefield?

**Comment by foolishhabits** [comment]
I think it's because I incorrectly uninstalled a mod for the battlefield skin. How do I allow it to revert to regular battlefield so it doesn't give me problems?

**Comment by Raytwo** [comment]
If you're using 1.0.2/1.0.3, please check issue #48
