### ISSUE TITLE
[Crash] Short summary of the context

### ISSUE THREAD

**Issue by TheQueensAce** [Raytwo/ARCropolis#515]
### System Firmware Version

16.0.1

### Atmosphere Version

1.5.1

### Smash Version

13.0.1

### ARCropolis Version

3.14.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [X] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

It says, "ARCropolis has panicked! Please open the details and send a screenshot to the developer, then close the game."

### Crash report

```shell
I'm not sure what this means, but the details say, "ARCropolis has panicked at 'TlsConnector::connect: Handshake failed with the following result: 107131', C:\Users\Raytwo\.cargo\git\checkouts\rustnative-tls-e1c2f7824b5e2733\f202fca\src\imp\nnsdk.rs:386:17
```

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
