### ISSUE TITLE
[Panic] Brief description of the issue

### ISSUE THREAD

**Issue by Fentynator** [Raytwo/ARCropolis#520]
### System Firmware Version

latets

### Atmosphere Version

latest

### Smash Version

13.0.1

### ARCropolis Version

latest

### Version channel

Stable

### SD card formatting

exFat

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Steps to reproduce

I have no clue about reproducing the error

### Details

![image](https://user-images.githubusercontent.com/130315675/230795214-a43bd0f8-f6d5-415a-85b2-1f9f77fad67d.png)

I keep getting this error when trying to run smash on ryujinx, none of my mods are messing with it (deactivating all didn't do anything) 

### Minimal modpack to reproduce the panic

no clue

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
