### ISSUE TITLE
[Qualify of Life] Brief description of the change

### ISSUE THREAD

**Issue by Ee4320** [Raytwo/ARCropolis#525]
### Explain the improvement(s).

Does it have to be like this? I’m not tech savvy in the slightest. I always get an ARCropolis has no config error when I launch it in SSBU. I’ve tried lots of thing and none of them have worked. It happens when I use ARCadia, and even when I do launch SSBU normally it gives me the prompt but the mod doesn’t show.

### Provide extra details

Idk how it would be implemented I just need help on what to do to fix the config file issue

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
