### ISSUE TITLE
[Incorrect behavior] Brief description of the issue

### ISSUE THREAD

**Issue by MADZGaming** [Raytwo/ARCropolis#529]
### System Firmware Version

16.0.3

### Atmosphere Version

1.5.4

### Smash Version

13.0.1

### ARCropolis Version

3.14.0

### Version channel

Stable

### SD card formatting

exFat

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

when I try to load smash it crash saying "The Software was Closed because an error occurred." before the intro even shows up and I've done every I needed to do in order to get it setup

### Screenshot

![IMG_2132 1](https://github.com/Raytwo/ARCropolis/assets/94149145/d0a4786d-a57f-4313-9ebe-d04f96c5ec5c)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.

**Comment by MADZGaming** [comment]
> Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.

my bad
