### ISSUE TITLE
[Feature] NUS3Bank patching

### ISSUE THREAD

**Issue by DShip91** [Raytwo/ARCropolis#530]
### Provide details

I'd like to have a way to patch NUS3Bank files in a similar fashion to how NUS3Audio, PRC, and MSBT files can be patched so that users can have multiple mods that edit the same NUS3Bank file without having to merge them all together.

### How should it be implemented?

Ideally, there would be a custom filetype for patched version of NUS3Bank files (Patch3Bank, maybe? idk) that ARCropolis would then use to patch the NUS3Bank in question. However, I don't know the intricacies of creating patches for Ultimate's game files so I don't know how this would work.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
