### ISSUE TITLE
[Panic] Brief description of the issue

### ISSUE THREAD

**Issue by aecdoub** [Raytwo/ARCropolis#538]
### System Firmware Version

16.0.3

### Atmosphere Version

1.5.2

### Smash Version

13.0.1

### ARCropolis Version

Couldn’t reach

### Version channel

Stable

### SD card formatting

FAT32

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Steps to reproduce

The panic occurs whenever smash bros. first boots up. After the Nintendo switch screen ARCropolis will panic. Even with no mods present (or the mods folder renamed) a new one will emerge and the panic will happen again. The game itself still functions when the .nro file is removed.

### Details

![ECAE8E8F-A803-4215-B4F8-B23C9C114852](https://github.com/Raytwo/ARCropolis/assets/141498164/190917dc-345a-470e-a5ee-3efd94ef00ee)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
