### ISSUE TITLE
Ryujinx support is currently broken

### ISSUE THREAD

**Issue by Raytwo** [Raytwo/ARCropolis#539]
Greetings,

It has come to my attention that some of the latest Ryujinx releases break ARCropolis support.  
The reasons for that are not worth getting into, but I've been told that this will be addressed shortly and complaints should be addressed to them directly.

Until then, please downgrade to [version 1.1.977](https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.977) to keep playing on emulator or use ARCropolis 4.0.0.

**Comment by Sweezy75** [comment]
Very well I will give it a try

**Comment by BigBoss320** [comment]
It seems that even Suyu or Yuzu donesn't work (or i am messing up something but what?)
