### ISSUE TITLE
Myra and Pyra DLC not working

### ISSUE THREAD

**Issue by PersistedLine** [Raytwo/ARCropolis#54]
When I go to the character selection screen Myra and Pyra aren't there but their DLC stage is there but the music is not working and I don't know how to fix this and every time I go online I see someone using Mario over Myra and the game crashes. I need help, please.

**Comment by itsmeft24** [comment]
your mods are outdated. please do not post your problems with mods on the github issues page. if you need help updating/removing mods, you can join the ult modding discord here: https://discord.gg/ASJyTrZ
