### ISSUE TITLE
[Crash] error code 2--0069 "The software is aborting."

### ISSUE THREAD

**Issue by BiaxialRain305** [Raytwo/ARCropolis#545]
### System Firmware Version

16.0.0

### Atmosphere Version

1.5.0

### Smash Version

13.0.1

### ARCropolis Version

3.14.0

### Version channel

Stable

### SD card formatting

exFat

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [X] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [X] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

Upon starting the game, loads a little then gives an error popup. Forces you to check the game for errors, it then finds errors and wants you to redownload the game, doing so won't change anything, same error pops up.
See https://github.com/Raytwo/ARCropolis/issues/324.

Steps taken to find solution:
1. Manually tried reinstalling ARCropolis to the latest stable version v3.14.0, problem persisted.
2. Removed all my mods, attempted again, and problem was resolved.
3. Went through each mod to manually find the mod that was causing the issue... (Took Forever)
4. Found it happening with https://gamebanana.com/mods/449187. (I one slotted it to C00)
Fixed after removing this mod not sure why it occurs.
 
Will also mention the plugins I had not sure if they are relevant or not:
libarc_randomizer_folder.nro
libarcropolis.nro
libcss_preserve.nro
libhazards_toggle.nro
libnn_hid_hook.nro
libno_auto_bgm.nro
libnro_hook.nro
libone_slot_eff.nro
libOne_Slot_Victory_Themes.nro
libsmashline_hook.nro
libsonic_eagle.nro
libstage_alts.nro

![20230913_154754](https://github.com/Raytwo/ARCropolis/assets/30487503/bf96deff-3173-4e76-843f-1cbee006b0ad)
![20230913_153019](https://github.com/Raytwo/ARCropolis/assets/30487503/401d7995-b79f-43dc-9979-e2d9d0719860)

### Crash report

```shell
N/A
```

### Minimal modpack to reproduce the crash

https://gamebanana.com/mods/449187

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
