### ISSUE TITLE
[Feature] Multi-Mod Folder Support

### ISSUE THREAD

**Issue by SuperSmashPastel** [Raytwo/ARCropolis#548]
### Provide details

Posted this on GameBanana because I was thinking of a new feature that we need for ARCropolis.

[https://gamebanana.com/threads/224284](https://gamebanana.com/threads/224284)

since V4.0.0 doesn't support the Multi-mod folder but I am hoping if you guys can add Multiple Mods, and of course I do mod Super Smash Bros. Ultimate by making my own modpack, so I set up some decoy folders and the decoy files like the config.json and whatnot. because I wanted to make myself a big roster with the pack of folders in one folder.

For @Raytwo if he and his team can implement the feature

### How should it be implemented?

The Feature works by Creating a folder, for your mods. name anything you want with spaces, open up the empty folder, Create a mod folder or drag and drop the mod into the empty folder. like Stage, Fighter, UI, etc.

Here's how it should look:
The Main Multi-Mod Folder
![image](https://github.com/Raytwo/ARCropolis/assets/145744391/a4fed140-5cb4-4a5f-89a8-da7a1d5b71b6)
If inside of the Mod inside the folder.
![image](https://github.com/Raytwo/ARCropolis/assets/145744391/553cac98-7acb-4039-9de4-3c0c4e21adc7)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
