### ISSUE TITLE
After Installing, Game No Longer Starts

### ISSUE THREAD

**Issue by ThisNekoGuy** [Raytwo/ARCropolis#56]
I installed ARC, extracted [this mod](https://gamebanana.com/gamefiles/16428) to the `/romfs/arc` directory that seems to work for other people, am on the latest Atmosphere version, and receive this error (with no code) on launch every time I try to start the game:
![20210318_032820](https://user-images.githubusercontent.com/28468662/111595593-2f30d000-87c4-11eb-8a41-e1c7440a5cbf.jpg)

**Comment by Raytwo** [comment]
Sorry but the error you're getting is unrelated to ARCropolis itself. You probably installed it poorly?
If you installed ARCropolis through FTP, make sure to do it through SD. If you're not on the latest version, make sure to upgrade.

**Comment by ThisNekoGuy** [comment]
I'll install it via SD then
I am on the latest version though, I just installed it

**Comment by ThisNekoGuy** [comment]
Also, can you explain the directory structure?
```arcroplois > workspaces > Example > arc / umm```?
