### ISSUE TITLE
"Unable to display page" error 2808-1037

### ISSUE THREAD

**Issue by DesexedDoggo** [Raytwo/ARCropolis#561]
### System Firmware Version

17.0.0

### Atmosphere Version

1.6.2

### Smash Version

13.0.1

### ARCropolis Version

4.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

It should open the arcropolis mod manager but instead I get error code 2808-1037 with a message saying "Unable to display page"

### Screenshot

![17069922725141514896681284282146](https://github.com/Raytwo/ARCropolis/assets/94494804/0852ac67-4681-4d84-9f3c-e9793dc7df74)

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
