### ISSUE TITLE
[Panic] Smash crash when starting a game with mods on

### ISSUE THREAD

**Issue by grvndmasterp** [Raytwo/ARCropolis#573]
### System Firmware Version

17.0.1

### Atmosphere Version

1.6.2

### Smash Version

13.0.2

### ARCropolis Version

4.0.2

### Version channel

Stable

### SD card formatting

FAT32

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Steps to reproduce

updated smash, arcropolis, and hekate

now when i start a game online/offline > smash crashes

### Details

ACropolis has panicked at TisConnector::connect: nn:socket:Connect
returned the following result: 110. L:1.cargo\git\checkouts\rust-native-tls
e1c217824b5e2733\202fca (src\imp\nnsdk.rs:308:13

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
