### ISSUE TITLE
Crash with mods

### ISSUE THREAD

**Issue by Ditto30** [Raytwo/ARCropolis#575]
Smash loaded up as normal with mods. I went to smash to see if mods functioned the way I wanted, and I selected by rules where i don't pick a stage. Right after picking that, the music stopped, and the game crashed.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
