### ISSUE TITLE
Sharing .nuanmb files in the config.json to Robin's second alt (c01) causes the game to load indefinatly when selecting said alt.

### ISSUE THREAD

**Issue by AParticularUser** [Raytwo/ARCropolis#580]
### System Firmware Version

17.0.1

### Atmosphere Version

1.6.2

### Smash Version

13.0.2

### ARCropolis Version

4.0.2

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

When selecting Robin's second alt, the game should load the match as expected with the relevant files being replaced.

### Minimal modpack to reproduce the panic

Any config.json that shares a .nuanmb file to the second alt.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
