### ISSUE TITLE
eshop doesnt go to mod manager

### ISSUE THREAD

**Issue by ilikessbutoonlink** [Raytwo/ARCropolis#584]
### System Firmware Version

17.0.2

### Atmosphere Version

1.7.0

### Smash Version

13.0.2

### ARCropolis Version

4.0.2

### Version channel

Stable

### SD card formatting

exFat

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### Expected behavior

there should be a pop up to enable new mods but it doesnt happen and there is no writing of arcropolis ver 4.0.2 and eshop doesnt go to mod manager

### Screenshot

i cant, i have to be quick

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
