### ISSUE TITLE
Mod menu won't open (Ryujinx)

### ISSUE THREAD

**Issue by Chetiboi** [Raytwo/ARCropolis#585]
### System Firmware Version

17.0.0

### Atmosphere Version

1.7.0

### Smash Version

13.0.2

### ARCropolis Version

4.0.2

### Version channel

Stable

### SD card formatting

FAT32

### Can this incorrect behavior be consistently reproduced?

Yes

### Configuration

- [X] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Expected behavior

When I go to the mod menu and click A, it makes a sound but it doesn't open and no matter how much you click it, it doesn't open.

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
