### ISSUE TITLE
SSBU Update 13.0.3

### ISSUE THREAD

**Issue by userbouy** [Raytwo/ARCropolis#590]
### Explain the improvement(s).

Nintendo just released a new update for smash ultimate, resulting into broken plugins, including Arcropolis. 

People on Smash 13.0.2 that use mods, DO NOT UPDATE YOUR GAME UNTIL IMPORTANT PLUGINS ARE FIXED!!!

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
