### ISSUE TITLE
arcropolis.toml missing

### ISSUE THREAD

**Issue by MrUnusual** [Raytwo/ARCropolis#60]
When launching ARCadia I get an error that says "ARCropolis config file not detected! Please run Smash Ultimate with ARCropolis set up! I launched Super Smash Bros Ultimate prior up to the title screen, but no arcropolis.toml was generated. I copied all of the folders from the release.zip correctly as instructed, but after launching Super Smash Bros Ultimate and then checking my sd card for the file in sd:/atmosphere/contents/01006A800016E000/romfs/, arcropolis.toml is still not in there. I'm on cfw 11.0.1 and running Super Smash Bros. Ultimate 11.0.0

**Comment by Raytwo** [comment]
That just sounds like you installed it poorly. To confirm you did it well, check on the title screen if ARCropolis' version is displayed.
