### ISSUE TITLE
[Crash] Yuzu get's stuck loading ROM indefinitively

### ISSUE THREAD

**Issue by StShAzzy** [Raytwo/ARCropolis#601]
### System Firmware Version

19.0.0

### Atmosphere Version

Emulated

### Smash Version

13.0.2

### ARCropolis Version

4.0.2

### Version channel

Stable

### SD card formatting

FAT32

### Can the crash be consistently reproduced?

Yes

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### At what moment does the crash happen?

- [X] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] During the Smash ball loading on boot
- [ ] Before the opening cutscene, but only sometimes
- [ ] On the Stage Select Screen
- [ ] On the Character Select Screen
- [ ] During the loading for a battle
- [ ] At random
- [ ] After a long time playing

### Details

oddly enough, installing it on Smash 13.0.3 works partially, it does write http data to show the web applet, but doesn't create config folders nor edit the game execution in any way (doesn't replace the smash version in the menu)

looking forward to get help in any capacity, even for more tests to figure out the potential problem

### Crash report

```shell
unavailable (didn't crash)
```

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
