### ISSUE TITLE
error code: 2- 0069 arcropolis has panicked at index out of bounds: the len is 648200 but the index is 648389', src\replacement\addition.rs:425:31

### ISSUE THREAD

**Issue by LargeBarge99** [Raytwo/ARCropolis#607]
### System Firmware Version

19.0.1

### Atmosphere Version

1.0/s

### Smash Version

13.03

### ARCropolis Version

latest version as of 11/10/2024

### Version channel

Beta

### SD card formatting

FAT32

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [ ] Irrelevant/Not provided

### Steps to reproduce

error pop after a couple minutes of loading

### Details

error code: 2- 0069 arcropolis has panicked at index out of bounds: the len is 648200 but the index is 648389', src\replacement\addition.rs:425:31

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
