### ISSUE TITLE
[Crash][ARCropolis 2.0.0-beta] Wario bike retexture causes the game to hang then crash

### ISSUE THREAD

**Issue by kalomaze** [Raytwo/ARCropolis#61]
### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.18.1``
Smash version: ``11.0.1``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32``

### Expected behavior
The game should have continued running as normal, and if I had started a match with two Warios, only one Wario should have had a unique bike texture. Additionally, each slot should have had its proper texture outside of dittos.

### What happened and what's the context?
I was playing the game with the latest ARCropolis beta, offline. I went to the main Smash mode, picked a ruleset, chose a stage (stage did not seem to impact the chances of crashing, as I have tested Battlefield, Random, and Random Battlefield leading to the same results). 

On the Character Select Screen, I chose Wario's 5th costume (c04). The game freezes on the CSS and hangs for a few seconds before displaying the generic "A software error has occured." The only mod active at the time was the IKON Wario recolor mod. No other plugins besides the beta ``libarcropolis.nro`` plugin were enabled. This mod is unique in that it contains a recolored texture for Wario's bike for the c04 costume, which is usually completely shared across Wario's alternate slots. The recolored bike texture is ``def_wariobike_001_col.nutexb``

[IKON Wario (c04).zip](https://github.com/Raytwo/ARCropolis/files/6233414/IKON.Wario.c04.zip) (from thatoneguy928's IKON skin pack originally sourced from here: https://gamebanana.com/skins/180104).

I had removed the UI of the mod as seen in the ZIP uploaded, but no differences were noted in the error with the UI active. I also tried removing Wario's body folder recolor, keeping only the bike texture, and the freeze leading to a error still happened.

### Screenshot(s)
N/A

### Configuration
[infos]
version = "2.0.0-beta"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/Mod Developing"
extra_paths = []

[updater]
server_ip = "178.62.31.147"
beta_updates = true

[logger]
logger_level = "Info"

[misc]
debug = true
region = "us_en"

### Crash report
[01617157167_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6233400/01617157167_01006a800016e000.log)

**Comment by Raytwo** [comment]
A new beta has been released that should fix a lot of issues, can you please try it again and reopen an issue if the problem still arises?
