### ISSUE TITLE
Error Code: 2--0069

### ISSUE THREAD

**Issue by DizGuyWasTaken** [Raytwo/ARCropolis#612]
### System Firmware Version

19.0.1|AMS 1.8.0|S

### Atmosphere Version

1.8.0

### Smash Version

13.0.3

### ARCropolis Version

4.0.6

### Version channel

Stable

### SD card formatting

FAT32

### Configuration

- [ ] Legacy discovery
- [ ] Modern discovery (>= 3.0.0)
- [X] Irrelevant/Not provided

### Steps to reproduce

I removed the most recent mods for SSBU I added to see if it could fix the problem, I kept mods I knew worked without issue but after trying to boot the games three times the panic came up. I've tried booting it again updating all the skyline plugins to the same problems happening, last try was removing all plugins to the game booting up without the mods. After an hour of going through stuff, I discovered the crash report logs via the Atmosphere and crash_report folders, looked for the latest one at the bottom and viewed it in Word. It turns out it was the mod Damage Sounds for Zombie and Enderman, I figured this out by looking at the first thing that listed "(zombie_enderman_sounds)". I'm not sure If it's the mod Itself or something for it I'm missing, but after removing the mod Smash boots up again with the mods.

### Details

![2024121117563800-1AB131B6E6571375B79964211BB3F5AE](https://github.com/user-attachments/assets/842a52dd-fac8-4b5c-b15c-863556776717)

### Minimal modpack to reproduce the panic

https://gamebanana.com/sounds/65695

**Comment by Raytwo** [comment]
Issues are only meant for ARCropolis contributors, please read the [guidelines](https://github.com/Raytwo/ARCropolis/issues/288) to report an issue or suggest a change.
