### ISSUE TITLE
[Infinite loading][ARCropolis 2.0.0-beta] List of characters causing an infinite loading

### ISSUE THREAD

**Issue by Demonslayerx8** [Raytwo/ARCropolis#62]
### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.16.1``
Smash version: ``11.0.1``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32``

### Expected behavior
Should load into a match, but instead just Inf Loads on VS Screen.

### What happened and what's the context?
Offline, These are the chars that I've found that inf loads on my end.
Mythra, Shulk, [Byleth](https://gamebanana.com/skins/183334), [Jigglypuff](https://gamebanana.com/skins/182474). [Cloud](https://gamebanana.com/skins/184439), Olimar (or [Alph ](https://gamebanana.com/skins/171178)in this case).
I did notice KH1 Cloud working for you, but he seems to inf load for me, even with no swing.prc added.

### Screenshot(s)
https://cdn.discordapp.com/attachments/515774032352903168/826650866357895188/My_Great_Capture_Screenshot_2021-03-30_19-51-24.png

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6233521/arcropolis.zip)

### Crash report
no crash report  if it just inf loads lmao

**Comment by kalomaze** [comment]
Joker infinite loads. Tested via [Fierce Deity Joker](https://gamebanana.com/skins/183885) which contains shared textures
Pichu infinite loads. Tested via [White Spiky Eared Pichu](https://gamebanana.com/skins/181827) which contains a shared numatb

**Comment by Segtendo** [comment]
Captain Falcon had an infinite load for me. Test it with [Proto Man Falcon](https://gamebanana.com/skins/184645) on c01.

**Comment by Demonslayerx8** [comment]
Update:
There's currently 12 characters that require an alt to get the mod to work
Bayo, Captain, Cloud, Ike, Corrin, Link, Byleth, Piranha Plant, Robin, Olimar/Alph, Wario, Wiifit and who else?
Corrin, Byleth, Robin, and Wiifit require both male and female in game to load into a match.

Piranha Plant and Captain Falcon requires c00 to load into a match. Wario requires classic and biker to load. Bayo requires Bayo1 and 2 to load in, Cloud requires soldier and AC to work; Soldier seems to work fine on it's own tho? Link requires alt outfit to load into match. Alph mods requires Olimar and vice versa.

Littlemac, Pichu and Jigglypuff will be tested later.

**Comment by Angstdiscord** [comment]
In addition to what DSX8 posted, it seems that mario infi loads with mods on any of the slots, at least thats been my experience.

**Comment by Demonslayerx8** [comment]
Update3:
Can confirm that there's a numdlb/nusrcmdlb conflict going on when those files are shared. Affected characters are..
Bayonetta, Cloud, Ike, Corrin (Kamui), Link, Byleth (Master), Piranha Plant (Packun), Olimar/Alph (Pikmin), Wario, and WiiFit

When there are multiple mods for the same character alt, for example KH Cloud and Zeke, the numdlb/nusrcmdlb is shared with the slots, but doesn't get unshared.

**Comment by Raytwo** [comment]
Hey guys, thanks a lot for the valuable feedback. Since beta4 just released I'll be closing this issue since most infos are now outdated.

For anybody checking this thread, please consult the Wiki instead for an up-to-date list of remaining issues: [Wiki](https://github.com/Raytwo/ARCropolis/wiki/Arcropolis-Beta-4-2.0.0)
