### ISSUE TITLE
[Panic][ARCropolis 1.0.5] "Failed to fill whole buffer" on the Vs. loading screen

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [Raytwo/ARCropolis#64]
### Your setup
System firmware version: Latest
Atmosphère version: Latest
Smash version: Latest
ARCropolis version: Latest
microSD card format: FAT32

### Reproducibility 
Everytime I load SSBU it Paniks

### What's the context?
Loading Screan

### Screenshot(s)
![image](https://user-images.githubusercontent.com/79018578/113360230-5ab0d000-9317-11eb-91d9-4d77e4300a74.png)

**Comment by Pixelplayz2215YT** [comment]
What do I do? This is my first time using Archropolis.

**Comment by Raytwo** [comment]
Could you try deleting the file with "lut" in the name in the game's romfs?

**Comment by Pixelplayz2215YT** [comment]
I can try, I'm not home rn, but I'll let you know

**Comment by arcenedon** [comment]
i'm having a similar issue, with the exact error. i did the same thing that was suggested in the comments, and mods still don't load. im on the same setup as the person who put this issue up.

**Comment by Raytwo** [comment]
If you can provide a way to reproduce the issue, I'll reopen it.
