### ISSUE TITLE
[Crash][ARCropolis 2.0.0-beta3] Trying to load voice mods causes a crash

### ISSUE THREAD

**Issue by MewtwoFanz** [Raytwo/ARCropolis#65]
## Crash report
The software closed because an error occurred
This happens every time I try to load voice mods

### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.18.0``
Smash version: ``11.0.1``
ARCropolis version: ``2.0.0-beta3``
microSD card format: ``FAT32``

### Reproducibility 
I can reproduce this by trying to load any kind of voice mods other than the Silent Male Pokemon Trainer Mod.

### What happened and what's the context?
Playing offline, with mods, trying to boot the game

### Configuration
[https://drive.google.com/file/d/1W0VC_Sg84M5nRLfjAcfdD_vV4K4oXqdi/view?usp=sharing](url)

### Crash report
[01617319263_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6246942/01617319263_01006a800016e000.log)

[https://drive.google.com/file/d/1epMHPhd9IZthpQSz6PbFNwbkZPhQ3DU8/view?usp=sharing](url)

**Comment by Angstdiscord** [comment]
From my experience this seems to be specifically caused by loading voice mods in the way that 0.9.6 did. Basically naming the vc file over the slot it's over

ex vc_captain_c01, vc_captain_c02 etc.

Loading them without the slot added seems to successfully boot. 

I've added this to the wiki for reference.

**Comment by Raytwo** [comment]
Thank you for your feedback. A new beta has been released that should fix a lot of issues, please try it again and reopen an issue if the problem still arises.
