### ISSUE TITLE
arcropolis crashing when trying to create a unsharing lookup table

### ISSUE THREAD

**Issue by Chromerexe** [Raytwo/ARCropolis#66]
every time i try to launch smash with a fresh install of arcropolis, it creates the config file no problem, but when it tries to create the unsharing lookup table, it stays in a black screen, and after some time, it crashes, and everytime i try to launch again it crashes again until i put another fresh install , in witch it just happens the same thing over and over

**Comment by setherroni** [comment]
The same is happening for me. I am unable to use my mods now since the last update.

**Comment by Coolsonickirby** [comment]
Please create an issue using one of the issue templates.
