### ISSUE TITLE
[Crash] [1.0.5] Nutexb of size bigger than Decompressed size crash

### ISSUE THREAD

**Issue by ClaudevonRiegan** [Raytwo/ARCropolis#67]
### My setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.17.1``
Smash version: ``11.0.1``
ARCropolis version: ``1.0.5``
microSD card format: ``FAT32``

### Reproducibility 
The Uncompressed Nutexb provided below will always crash on current size (0x555EB0) greater than Decompressed Size (0x155EB0), regardless of any style you attempt it but will work if current size is lesser than Decompressed size. Goes over c00 cloud.

[faulty_nutexb.zip](https://github.com/Raytwo/ARCropolis/files/6271640/faulty_nutexb.zip)

### What happened and what's the context?
Crashes as soon as you select the said slot with the Nutexb or during load screen when you selected fighter (Cloud here).

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6255208/arcropolis.zip)

### Crash report
[01617563038_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6255210/01617563038_01006a800016e000.log)

**Comment by Raytwo** [comment]
Fixed as of ARCropolis 2.0.0
