### ISSUE TITLE
[Crash] [ARCropolis 2.0.0-beta] Crash while trying to update the configuration

### ISSUE THREAD

**Issue by BlancBestGirl** [Raytwo/ARCropolis#71]
### Your setup
System firmware version: 11.0.1
Atmosphère version: 0.18.1
Smash version: 11.0.1
ARCropolis version: 2.0.0-beta
microSD card format: FAT32

### Reproducibility 
Crashes switch after it tries to update config files to latest format

### What happened and what's the context?
Atmosphere crashes when arcropolis tries to update config file

### Configuration

[arcropolis.txt](https://github.com/Raytwo/ARCropolis/files/6268423/arcropolis.txt)
renamed to .txt so github would take the file

### Crash report
[01612508583_050000baddad0000.log](https://github.com/Raytwo/ARCropolis/files/6268428/01612508583_050000baddad0000.log)

**Comment by BlancBestGirl** [comment]
Deleted all of the arcopolis files and reinstalled 2.0 beta, and it crashed when making the config file

**Comment by Raytwo** [comment]
Ok well, I'm just not going to help someone who uses Tinfoil, sorry.
