### ISSUE TITLE
[Crash] [2.0.0 beta3] Crash on Boot

### ISSUE THREAD

**Issue by Remna0w0** [Raytwo/ARCropolis#74]
### Your setup
System firmware version: ``12.0.0``
Atmosphère version: ``0.19.1``
Smash version: ``11.0.1``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32`` 

### Reproducibility 
I'm not sure what causes it, but I do have a folder of every mod that caused it. Perhaps there's a common denominator? 
[Broke Mods.zip](https://github.com/Raytwo/ARCropolis/files/6321196/Broke.Mods.zip)
All of these mods work fine on 1.0.5.

### What happened and what's the context?
When launching the game, the Switch logo displays for a few seconds, presumably loading, before it gives the "The software was closed because an error occurred." message.

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6321200/arcropolis.zip)

### Crash report
[01618412121_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6311787/01618412121_01006a800016e000.log)

**Comment by Remna0w0** [comment]
Update: I tried disabling all mods that I have and the game was able to launch, so it must be some mod that I have installed. I will be looking into which one it is.

**Comment by daftmario** [comment]
Same issue, along with another person on youtube. I've tried everything to my unpatched switch, and even with no mods installed it still fails to load past the error screen. I guess I will just wait until the new version.

**Comment by Remna0w0** [comment]
> Same issue, along with another person on youtube. I've tried everything to my unpatched switch, and even with no mods installed it still fails to load past the error screen. I guess I will just wait until the new version.

You can also just use 1.0.5 in the meantime. That's what I'm doing.

**Comment by daftmario** [comment]
You're right, I did consider this but I wasn't too sure if it would work or not, but thanks!

**Comment by Raytwo** [comment]
Thank you for your feedback. A new beta has been released that should fix a lot of issues, please try it again and reopen an issue if the problem still arises.
