### ISSUE TITLE
[Panic][ARCropolis version] Cant even boot up the game, immediately get this pop up error

### ISSUE THREAD

**Issue by SquishyMp4** [Raytwo/ARCropolis#76]
### Your setup
System firmware version: ``12.0.1``
Atmosphère version: ``0.19.1``
Smash version: ``11.0.1``
ARCropolis version: ``1.1.0``

### What's the context?
Cant even boot up Ult without a crash. Even without mods and with only arc active.

### Screenshot(s)
![2021041912490800-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/82856467/115331882-c2af4500-a164-11eb-9cd5-6544d4ad9101.jpg)
![2021041912482300-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/82856467/115331888-c4790880-a164-11eb-8fbb-8e29df81668c.jpg)

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6340392/arcropolis.zip)

**Comment by Raytwo** [comment]
The error is related to us displaying a web page on boot which could crash because of a lack of memory.
This should have been fixed since, but if not, feel free to reopen an issue.
