### ISSUE TITLE
Arcropolis 1.1.1

### ISSUE THREAD

**Issue by glazedonut** [Raytwo/ARCropolis#77]
Error code 2-0069

0
Error: 0x2f6202

“Software aborted” on startup for Arcropolis version 1.1.1. Worked fine for 1.1.0, but has been an issue after the 1.1.1 update.

**Comment by Fenriraga** [comment]
Same issue just occured for me, was also using 1.1.0 and updated after re-opening the game

**Comment by Genwald** [comment]
Please use the issue templates to make sure that you include the needed info. That is a popup to give extra info, the game should have crashed just after, so use that template.

**Comment by Raytwo** [comment]
As Genwald say, please reopen an issue following one of the templates provided.
