### ISSUE TITLE
[Crash] [v1.1.1] Software aborts on startup

### ISSUE THREAD

**Issue by jozz024** [Raytwo/ARCropolis#78]
## Crash report
![2021042003150000-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/74272560/115368600-db335580-a18c-11eb-91d7-087fcb040c0c.jpg)

### Your setup
System firmware version: ``12.0.1``
Atmosphère version: ``0.19.1``
Smash version: ``11.0.1``
ARCropolis version: ``1.1.1``
microSD card format: ``exFAT``

### Reproducibility 
It is reproduced every time the game is opened.

### What happened and what's the context?
At the game startup it gives an abort error, and then the game crashes. it happens with all mods disabled and all plugins (besides arcropolis itself) disabled.
### Configuration

[arcropolis.toml.txt](https://github.com/Raytwo/ARCropolis/files/6342084/arcropolis.toml.txt)

### Crash report
[01618908055_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6342087/01618908055_01006a800016e000.log)

**Comment by Aonumiles** [comment]
Same issue here. I think it has to do with Nintendo's last 12.0.1 firmware update... Maybe ARCropolis isn't compatible with it yet?

**Comment by jozz024** [comment]
> Same issue here. I think it has to do with Nintendo's last 12.0.1 firmware update... Maybe ARCropolis isn't compatible with it yet?

that isn't the case, cause if i'm remembering correctly arcropolis doesn't interfere with anything the system does

**Comment by Aonumiles** [comment]
> 
> 
> > Same issue here. I think it has to do with Nintendo's last 12.0.1 firmware update... Maybe ARCropolis isn't compatible with it yet?
> 
> that isn't the case, cause if i'm remembering correctly arcropolis doesn't interfere with anything the system does

Yeah you're right. Well, I tried two things so far: 
- launching the game without ARCropolis (obviously it worked but no mods)
- deleting all my mods, reinstalling ARCropolis and starting everything from the begining, it still doesn't work

I believe we're not the only ones having this issue, I hope someone will find what's wrong and an answer to it.

**Comment by Lukayaba** [comment]
> > > Same issue here. I think it has to do with Nintendo's last 12.0.1 firmware update... Maybe ARCropolis isn't compatible with it yet?
> > 
> > 
> > that isn't the case, cause if i'm remembering correctly arcropolis doesn't interfere with anything the system does
> 
> Yeah you're right. Well, I tried two things so far:
> 
> * launching the game without ARCropolis (obviously it worked but no mods)
> * deleting all my mods, reinstalling ARCropolis and starting everything from the begining, it still doesn't work
> 
> I believe we're not the only ones having this issue, I hope someone will find what's wrong and an answer to it.

I and other people are having this issue.

**Comment by jozz024** [comment]
yes, this is a known issue at the moment.

**Comment by Lukayaba** [comment]
Okay, this isn't a solution per se but is a temporary fix. Download v1.1.0 here https://github.com/Raytwo/ARCropolis/releases/download/v1.1.0/release.zip and when it asks if you want to update on startup, **say no**. That worked for me, just don't use v1.1.1 for now

**Comment by Aonumiles** [comment]
> 
> 
> Okay, this isn't a solution per se but is a temporary fix. Download v1.1.0 here https://github.com/Raytwo/ARCropolis/releases/download/v1.1.0/release.zip and when it asks if you want to update on startup, **say no**. That worked for me, just don't use v1.1.1 for now

Thank you!

**Comment by toothbrushbutt** [comment]
> > Okay, this isn't a solution per se but is a temporary fix. Download v1.1.0 here https://github.com/Raytwo/ARCropolis/releases/download/v1.1.0/release.zip and when it asks if you want to update on startup, **say no**. That worked for me, just don't use v1.1.1 for now
> 
> Thank you!

am also having the same issue, this solution worked fine for me

**Comment by jam1garner** [comment]
Fixed in 1.1.2, create a new issue if the problem persists.
