### ISSUE TITLE
[Panic][ARCropolis 1.1.3] Panic after Results Screen 

### ISSUE THREAD

**Issue by wahrio** [Raytwo/ARCropolis#80]
### Your setup
System firmware version: ``12.0.1``
Atmosphère version: ``0.19.1``
Smash version: ``11.0.1``
ARCropolis version: ``1.1.3``
microSD card format: ``exFAT``

### Reproducibility 
Seems as though it is a random occurrence

### What's the context?
Offline, on Results Screen

### Screenshot(s)
![2021042618003400-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/83251344/116157785-9000d180-a6bb-11eb-98e6-0a6b174f514e.jpg)

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6380692/arcropolis.zip)

**Comment by Raytwo** [comment]
Very weird, considering a web dialog shouldn't show up at this point in time. Probably some very rare occurrence that won't be easily debugged, sorry.
