### ISSUE TITLE
I'm not getting an arcropolis config file

### ISSUE THREAD

**Issue by lucluc27** [Raytwo/ARCropolis#84]
I've downloaded everything I can find, including old versions, but I'm not getting a config file

**Comment by AwesomeKirito** [comment]
You gotta run smash and it'll download itself

**Comment by lucluc27** [comment]
I’ve done that a couple of times and i still haven’t gotten one

**Comment by AwesomeKirito** [comment]
You connected to the internet?

**Comment by lucluc27** [comment]
Yeah I am

**Comment by lucluc27** [comment]
Actually, Im getting a config file, but arcropolis cant find it for some reason.

**Comment by lucluc27** [comment]
Could still use some help

**Comment by Raytwo** [comment]
Ok so:
First, ARCropolis does not "download" a configuration, it creates one.
Secondly, I'm closing this issue because you did not use an issue template (Incorrect behavior/Crash report/Panic).
Please reopen one using an issue template if the problem persists
