### ISSUE TITLE
[Panic][2.0.0-beta3] Panic when starting Ultimate with a mod loaded

### ISSUE THREAD

**Issue by TheTubbyBear** [Raytwo/ARCropolis#85]
### Your setup
System firmware version: ``12.0.3``
Atmosphère version: ``0.19.4``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta3``
microSD card format: ``FAT32``
### Reproducibility 

This issue occurs anytime I load this model swap mod for F-Byleth (c01). The Panic occurs immediately when trying to load the game, I do not get to the start menu.

Mod: 
[Petra (Byleth c01).zip](https://github.com/Raytwo/ARCropolis/files/6765539/Petra.Byleth.c01.zip)

### What's the context?

Crash happens immediately upon trying to boot Ultimate. I enter the ARCropolis menu, select the mod, launch Ultimate, and the crash occurs shortly after.

The mod worked on the previous version of Ultimate. I have another mod that works on this set up.

### Screenshot(s)
Error Code: 2-0069

Thread '<unnamed>' panicked at 'Lookup table file does not contain entry for 'sd:/ultimate/mods/Petra (Byleth c01)/fighter/master/model/body/c01/model.numatb' (0x2ada37d268)', src\replacement_files.rs:186:21

### Configuration
[Configuration.zip](https://github.com/Raytwo/ARCropolis/files/6765536/Configuration.zip)

**Comment by Raytwo** [comment]
Thank you for your feedback. A new beta has been released that should fix a lot of issues, please try it again and reopen an issue if the problem still arises.
