### ISSUE TITLE
[skyline panic][ARCropolis v1.1.3] skyline Panic on the loading screen 

### ISSUE THREAD

**Issue by VIC118** [Raytwo/ARCropolis#86]
## Panic report
[Sentences between [brackets] should be removed before posting.]

[Before posting, make sure to check if the ARCropolis version appears on the title screen. If it does not, you did not install it properly and should not open an issue. This also means the panic comes from another plugin.]

[Only issues related to the latest major version, which is the leftmost number (e.g., ``2`` in version ``2.0.0``), are considered.]
[The previous statement does not apply if the only release in a major version is a beta.]
[Finally, any issues where the user is using SX OS or ReiNX are not considered and issues with said CFW should not be submitted.]

### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.18.1``
Smash version: ``11.0.1``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32`` or ``exFAT``

### Reproducibility 
[Can you reproduce the crash/infinite load? If so, is it random, every time you try, etc.? If you can, please provide a zip/rar with the minimum amount of files to reproduce the issue.]

### What's the context?
[Were you playing offline? Online? With mods? Was it during the Vs. loading screen? On the CSS? On the SSS? ...]

### Screenshot(s)
[If a panic window with a code ending in ``69`` shows up, please select "Details" and provide a screenshot of the message. If you cannot provide a screenshot, write down the message in its entirety.]

### Configuration
[Post your configuration file located in ``sd:/atmosphere/contents/01006A800016E000/romfs/arcropolis.toml`` here.]

**Comment by Raytwo** [comment]
Next time, reply to the various questions of the issue please. You literally only filled the "Your setup" part.
Closing this, reopen one and fill the form if you still encounter the issue.
