### ISSUE TITLE
[Crash][2.0.0-beta4] Pacman issue persists with Steve, as well as more Pac-Man info

### ISSUE THREAD

**Issue by HyperNuke632** [Raytwo/ARCropolis#87]
System firmware version: 12.1.0
Atmosphère version: 0.19.5
Smash version: 12.0
ARCropolis version: 2.0.0-beta4
microSD card format: FAT32

Reproducibility

The game crash that happens upon PacMan spawning a hydrant also happens with Steve Anvil (down-air). If you use down air with mods offline the game crashes, and it crashes online, regardless of port or if you have mods or not. It is the same situation with Pac-Man. 

Mod:
Any mod for Steve will have this game crash if Anvil is used. But online, it will crash without mods as well if Anvil is used. The same applies to Pac-Man and his hydrant.

What's the context?
The crash happens immediately upon trying to use Steve's down-air. Probably due to the same error as Pac-Man, as specified. 

Error Code: None. The game closes. 

Configuration:
[configuration.zip](https://github.com/Raytwo/ARCropolis/files/6835808/configuration.zip)

**Comment by blu-dev** [comment]
Please check the latest beta to see of that resolves your issue. If it does, the issue will be closed. If it doesn't please respond with the crash report and I will continue looking into it. Thanks!

**Comment by blu-dev** [comment]
As I have not seen a reply, and beta-5 appears to have solved the issue for others who have this same report, I will be closing this issue.
