### ISSUE TITLE
[Crash] [2.0.0-beta5] Pac-Man hydrant/Steve anvil still crashing

### ISSUE THREAD

**Issue by jobrien97** [Raytwo/ARCropolis#88]
### Your setup
System firmware version: 12.1.0
Atmosphère version: 0.19.5
Smash version: 12.0
ARCropolis version: 2.0.0-beta5
microSD card format: FAT32

### Reproducibility 
Spawning hydrant with Pac-Man still crashes, both on slots with only Pac-Man edited and slots with hydrant edited. Same case with Steve and anvil.

### What happened and what's the context?
Playing offline, crashes immediately upon hydrant/anvil spawn.

### Configuration
[arcrop-config.zip](https://github.com/Raytwo/ARCropolis/files/6836945/arcrop-config.zip)

### Crash report
[01626641869_01006a800016e000[1].log](https://github.com/Raytwo/ARCropolis/files/6836943/01626641869_01006a800016e000.1.log)

**Comment by blu-dev** [comment]
Updated with the correct upload, please redownload
