### ISSUE TITLE
[Incorrect behavior][ARCropolis 2.0.0 beta 5] Pyra & Mythra's swing.prc is no longer shared

### ISSUE THREAD

**Issue by KirbGuy** [Raytwo/ARCropolis#90]
System firmware version: 12.1.0
Atmosphère version: 0.19.5
Smash version: 12.0.0
ARCropolis version: 2.0.0-beta5
microSD card format: FAT32

Expected behavior & Context
I have an edited swing.prc file for both of them to remove their bust physics, however, it only seems to apply to their first alt, (c00) when it would apply to all their alts in previous versions.

Configuration
[infos]
version = "2.0.0"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "0.0.0.0"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"

**Comment by Demonslayerx8** [comment]
That's cause you need to copy the file to every single slot now. If you want it to be shared again, ur free to downgrade back to 1.1.3.

**Comment by blu-dev** [comment]
I am going to close this issue, as the unsharing of this file is intentional. As DSX8 said, please copy the `swing.prc` to all of their slots. My apologies for any confusion!

**Comment by blu-dev** [comment]
Also, my apologies for the description of the release not being clear about what will/won't break. Many mods relied on shared files to save file space. As that is no longer an option, many mods will break and either require updating from the mod creator or the user will need to change files.

**Comment by KirbGuy** [comment]
Not sure why I assumed .prc files wouldn't be affected by the patch, my apologies.
