### ISSUE TITLE
[Incorrect behavior][ARCropolis 2.0.0] Peach unsharing issue

### ISSUE THREAD

**Issue by ClaudevonRiegan** [Raytwo/ARCropolis#92]
### My setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.19.1``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta5``
microSD card format: ``FAT32``

### Expected behavior
Peach (c00 slot only) should work normally unmodded.

### Reproducibility 
Just use any skin mod on peach except c00.

### What happened and what's the context?
Peach c00 tends to glitch out with mod on any slot but other unmodded slots are still working fine.

### Screenshot(s)
![2021072001213200-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/63413745/126220309-ccf75135-f188-458a-8c77-f0d6c3748765.jpg)
![2021072001221800-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/63413745/126220315-fda313ea-52bf-4da4-bad7-aad3106b4a61.jpg)
![2021072001230300-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/63413745/126220318-96d6e3d9-99f8-4c3c-b86e-0ee4a6bc9baf.jpg)

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/6843624/arcropolis.zip)

**Comment by Angstdiscord** [comment]
This is most likely just a swing.prc issue where it doesn't belong. I don't think arc is doing this.

**Comment by ClaudevonRiegan** [comment]
> This is most likely just a swing.prc issue where it doesn't belong. I don't think arc is doing this.

You can be right here, but not to forget this issue was also present back in beta 3 when swing.prc was not unshared, that said it was pretty buggy because DSX had them unshared on ganondorf. I will check it out and see if removing all swing.prc lead to same issue or not.

**Comment by Raytwo** [comment]
Claude is unreliable confirmed.
