### ISSUE TITLE
[Incorrect behavior][ARCropolis version] Files with a regional indicator do not load properly

### ISSUE THREAD

**Issue by ExtortFZ** [Raytwo/ARCropolis#93]
### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32``

### Expected behavior
The stage mods [Kalos City](https://gamebanana.com/mods/145620) and [Midgarville](https://gamebanana.com/mods/297568) are not loading properly. For Kalos City, the main stage is loaded as the default Town and City stage, and for Midgarville the platform is the normal Smashville platform. This has not happened on the previous version of Arcropolis. 

### Reproducibility 
This incorrect behavior occurs every single time. 

### What happened and what's the context?
Offline against a CPU

### Screenshot(s)
![Kalos City](https://user-images.githubusercontent.com/87678756/126243243-49c926ed-cdbd-4b1f-a0ae-bcde64207298.jpg)
![Midgarville](https://user-images.githubusercontent.com/87678756/126243244-6cd286ca-23d6-47db-9b54-78721cf2abdb.jpg)

### Configuration
[My Arcropolis.toml](https://www.mediafire.com/file/qq82bmbc84ana5e/arcropolis.toml/file)

**Comment by Puncake12** [comment]
I'm having the same issue with this one: https://gamebanana.com/mods/145623

**Comment by Angstdiscord** [comment]
Mine doesn't even make it this far, just crashes when trying to load Kalos City.

**Comment by Angstdiscord** [comment]
Can't speak for Midgarville but Kalos City has been updated to work with the beta and you should no longer have this issue after updating.

**Comment by Raytwo** [comment]
Considering this was for 2.0.0-beta (There were 8 betas for it), I'll close this for now. 
If this is a remaining issue on 2.0.0 stable (if you managed to grab it before I took it down), please reopen an issue.
