### ISSUE TITLE
[Crash] [ARCropolis 2.0.0 beta5] Dark Samus crashes

### ISSUE THREAD

**Issue by Syko7956** [Raytwo/ARCropolis#95]
### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta5``
microSD card format: ``FAT32``

### Reproducibility 
It does not matter who wins. If the game finishes with Dark Samus winning or dying, the game hangs and crashes. If you start a match and quit (No Contest), the game will not crash.

### What happened and what's the context?
This happened to two friends with the same setup. No mods related to Dark Samus and/or the opponent. 
Offline; ingame. With other mods but unrelated to the issue. 

### Configuration
https://cdn.discordapp.com/attachments/416648220433711116/867036544648609842/arcropolis.toml

### Crash report
https://cdn.discordapp.com/attachments/416648220433711116/867036909176225802/01626787713_01006a800016e000.log

![](https://cdn.discordapp.com/attachments/416648220433711116/867037008350150676/01626787713_01006a800016e000.jpg)

**Comment by Demonslayerx8** [comment]
Can confirm that it DOES indeed crash on match win.

**Comment by Puncake12** [comment]
> Can confirm that it DOES indeed crash on match win.

Oh wow, this should be fixed ASAP, especially since Dark Samus is popular online.

**Comment by TeriosKrim** [comment]
Can also confirm with video proof https://youtu.be/DQZNHWod9tU

**Comment by 0xR00KIE** [comment]
can confirm it happens to me too. can close the game to get out of it though.
