### ISSUE TITLE
[Incorrect behavior][2.0.0-beta6] Custom music is not loading

### ISSUE THREAD

**Issue by Puncake12** [Raytwo/ARCropolis#97]
## Bug report

Custom music is not playing in game.

### Your setup
System firmware version: ``11.0.1``
Atmosphère version: ``0.18.1``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32`` or ``exFAT``

### Expected behavior
Custom Music should have played but it didn't.

### Reproducibility 
Happens every time I boot it up.

### Configuration
[cfg.txt](https://github.com/Raytwo/ARCropolis/files/6858247/cfg.txt)

**Comment by Blabacon** [comment]
I can confirm this. It happened to me as well.

**Comment by Vaillances** [comment]
Can confirm as well, all the custom songs do appear in Sound Test but when trying to play one, nothing is heard and the bar stays at 00:00

**Comment by Angstdiscord** [comment]
Can confirm this specifically breaks in beta-6. 
It also breaks custom intro movies

**Comment by Knuxfan24** [comment]
Another confirmation, music replacements work but ones added through Sma5hMusic do not.

**Comment by Blabacon** [comment]
I believe (I'm not a coder so you can take this as a grain of salt) that it could be due to the one slot voice mods.

**Comment by GarnetSunset** [comment]
As an extension of this it appears the "opening" videos don't seem to work either, since it TOO is in "stream;"

**Comment by MewtwoFanz** [comment]
I can confirm this as well, as custom music from Smash 5 Music and custom intros do not work.
