### ISSUE TITLE
[Crash] [ARCropolis 2.0.0-beta5, 2.0.0-beta7, 2.0.0-beta8] All solo Pokemon Trainer Pokemon causing crashes while loading during All Star Smash/Spirit Battles

### ISSUE THREAD

**Issue by SorcererPonse** [Raytwo/ARCropolis#98]
## Crash report
Making the game load Squirtle in either All Star Smash or Spirit Battle(and possibly other modes) causes the game to immediately crash while loading, though strangely, using solo Squirtle and making Squirtle load through using Pokemon Trainer on Training or Smash allows him to load properly without any crashes. This is consistent and happens without any other additional plugins or mods besides ARCropolis and Skyline. This also extends to Ivysaur and Charizard.

### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta5, 2.0.0-beta7, 2.0.0-beta8``
microSD card format: ``exFAT``

### Reproducibility 
Simply play All-Star Smash and try to get to Squirtle. Or, fight the Blue Pikmin spirit in Spirit Battle or on the Spirit Board. Any Pokemon Trainer Pokemon battle outside of Smash and Training will cause it. This includes Ivysaur and Charizard.

### What happened and what's the context?
Playing singleplayer modes like All-Star Smash and Spirit Battle and attempting to fight anything involving a solo Squirtle will cause the game to crash while it attempts to load the character in. It's consistent even without any additional mods installed, though he can still be used in modes like Training and Smash. This also extends to Ivysaur and Charizard.

### Configuration
https://drive.google.com/file/d/1vkzj042O3dd_fLh6YA1EBn-2EfvnbTgH/view?usp=sharing

### Crash report
https://drive.google.com/file/d/1nqqOiK5osCIl5_4WP4EJo8s05ypsaYmc/view?usp=sharing - Picture at time of crash
https://pastebin.com/QUMwDmh5 - Crash Log
https://drive.google.com/file/d/1ma24XM-PQud3FHTd74kJBxrPEtAyXmO5/view?usp=sharing - Picture at time of crash during Spirit Battle
https://pastebin.com/0DrKrdQB - Crash Log from Spirit Battle crash

If more crash logs are needed, I will gladly provide them.

**Comment by Raytwo** [comment]
Thanks for the feedback.
Sadly, while we're aware of this, we currently have no way of fixing this past 2.0.0 and have a few priorities for what we consider a stable build:
* Does not break offline Melee or online modes
* Does not break any fighter when it comes to gameplay

While we'll keep in mind that this is a bug and will need fixing one day, eventually, I'll have to close this issue for now as we simply have no way to take care of it and it is not high on the bugfixes priority.
